### ISSUE TITLE
[Question] No test results for testrail even when the report is being generated with reportData

### ISSUE THREAD

**Issue by clundstedt-m** [cenfun/monocart-reporter#10]
Hey there! I'm completely new with this reporter and gotta say that it is amazing, nonetheless when trying to integrate with Testrail I'm kinda lost since every time I run my tests I'm getting the error message saying that no test results for testrail are available, but my report-file is still being generated without any issues (both .html & .json).

Here's a look at my **playwright.config.ts**: 
```
  reporter: [
    ['list'],
    ['monocart-reporter', {
        name: "My Test Report - Playwright Automated",
        outputFile: "./test-results/monocart_report.html",
        onEnd: async (reportData, capability) => {
          console.log('onEnd hook start');
          const testrail = require('./utils/testrail.js');
          await testrail(reportData, capability);
        }
    }]
  ],
```

And what I currently have in my **testrail.js:**

```
require('dotenv').config()
const Testrail = require('testrail-api');
const EC = require('eight-colors');
module.exports = async (reportData, capability) => {

    const options = {
        host: 'https://myInstance.testrail.io',
        user: process.env.TESTRAIL_USERNAME,
        password: process.env.TESTRAIL_PASSWORD
    };

    if (!options.password) {
        EC.logRed('[testrail] require a password');
        return;
    }

    const client = createClient(options);

    EC.logCyan('[testrail] collect test results ...');
    const results = [];

    // add testrail case id to comments
    /**
     * @testrail 2126
     */
    // test('Test case', async () => { });

    capability.forEach((item) => {
        if (item.type === 'case' && item.testrail) {
            // 1 Passed
            // 5 Failed
            const status_id = item.ok ? 1 : 5;
            results.push({
                case_id: item.testrail,
                status_id: status_id,
                comment: ''
            });
        }
    });

    if (!results.length) {
        EC.logRed('[testrail] no test results for testrail');
        return;
    }
    console.log(`[testrail] got test results: ${results.length}`);


```

I've tried installing the testrail-api dependency directly, logging the output (still getting reportData) and even creating a Test Suite with the same name into Testrail prior to executing it, but got no luck, is there something else I'm missing? Do I have to actually "mark" each and every test case that I want to be collected?

Here's an screenshot of my results if it serves for some purpose

![Screen Shot 2023-04-04 at 14 06 51](https://user-images.githubusercontent.com/81565080/229880344-0eb63c3d-dffc-4045-b529-3b098a3f673c.png)

Sorry for the silly question in advance and once again, amazing job with this reporter !! 🚀

**Comment by cenfun** [comment]
the error message means that no testrail id be collected. 
please check the testrail id comments in your tests like:
```js
// add testrail case id to comments
    /**
     * @testrail 2126
     */
test('Test case', async () => { });
```
"@testrail 2126" means testrail id is 2126
then check the reporter config, make sure comments to be collected:
```js
// playwright.config.js
module.exports = {
    reporter: [
        ['monocart-reporter', {  
            name: "My Test Report",
            outputFile: './test-results/report.html',
            // additional custom visitor for columns
            visitor: (data, metadata, collect) => {
                // auto collect data from comments
                const comments = collect.comments();
                if (comments) {
                    Object.assign(data, comments);
                }
            }
        }]
    ]
};
```
please try again. let me know if any questions.

**Comment by clundstedt-m** [comment]
Oh so the ID given at the comment like:
  * @testrail 2126
 Is a number that I get to assign to it on my own right? or does it depend/come from somewhere from the actual testrail project that I want to import results into?
 
 Sorry for the silly questions again :C

**Comment by cenfun** [comment]
yes the id(s) should come from the actual testrail project, you have to create all the test cases in testrail first, testrail will generate the id(s)
so @testrail 2126 will connect playwright tests with testrail test cases

**Comment by clundstedt-m** [comment]
> yes the id(s) should come from the actual testrail project, you have to create all the test cases in testrail first, testrail will generate the id(s) so @testrail 2126 will connect playwright tests with testrail test cases, you need to manually manage the relationship Then the playwright test results can be correctly sent to the Testrail results

Oh that makes sense, I'll try this out and see how it goes
Thanks once again cenfun!

**Comment by clundstedt-m** [comment]
Had no luck with the changes :(, still no collected test results, what I did was:

Created the test case into testrail, it got assigned the **_id = 3670_**
<img width="1206" alt="Screen Shot 2023-04-05 at 12 18 06" src="https://user-images.githubusercontent.com/81565080/230142488-a94bee46-ad60-4685-8e39-3ba0cf37cac7.png">



At my test case I added the comment with the corresponding test id:
```
    /**
    * @testrail 3670
    */
  test.only('Creating Static Asset - Other', async ({page}) => {
    const assetsPage = new AssetsPage(page);
    await assetsPage.assetGridLoads()
    await assetsPage.createAssetGroupByJSON("Other", "Other")
  });
});
```

At my `playwright.config.ts` I made sure that the comments were being collected by the visitor:
```
    ['monocart-reporter', {
        name: "My Test Report - Playwright Automated",
        outputFile: "./test-results/monocart_report.html",
        // additional custom visitor for columns
        visitor: (data, metadata, collect) => {
          const comments = collect.comments();
          if (comments) {
              Object.assign(data, comments);
          }
        },  
        onEnd: async (reportData, capability) => {
          console.log('onEnd hook start');
          const testrail = require('./utils/testrail.js');
          await testrail(reportData, capability);
        }
    }]
```

And after running it, I'm still getting no collected results 😢 
![Screen Shot 2023-04-05 at 12 22 18](https://user-images.githubusercontent.com/81565080/230143116-d903da9f-fe50-44b5-be26-32bebca8f7a3.png)

Could it have to be with the way I'm creating the test cases into TestRail itself??

Sorry for all the nuisances with my questions but I'm really eager to get this working alongside TestRail here.

thanks in advance for your help as always!

**Comment by cenfun** [comment]
can you create a repo for this? so i can debug it locally.

**Comment by clundstedt-m** [comment]
> can you create a repo for this? so i can debug it locally.

I mean I can but it won't serve much tbh as you won't be able to access any url from it as we clearly use .env files for everything, but I'll share it anyway since maybe you can spot something that I might be missing :(

you should already be able to see it [here](https://github.com/clundstedt-m/fzplaywright-copy-cl)

**Comment by cenfun** [comment]
I mean a demo repo is good enough. I just check your repo and found the root cause in console log:
Unable to parse fzplaywright-copy-cl\src\e2e\tests\assets\asset-actions.spec.ts: 'import' and 'export' may appear only with 'sourceType: "module"' (1:0)
Im tring to resolve it

**Comment by cenfun** [comment]
please try following
- I just made some changes to your repo: https://github.com/clundstedt-m/fzplaywright-copy-cl/commit/680ffa1afe9ac06ff957c708dd5c2ea91e6cb487
- first, update latest version "monocart-reporter": "^1.6.6" (support for typescript comments)
- add "type": "module" to your package.json, make sure using "import" not "require"
- replace all require with import
- add parser options to visitor 
```js
visitor: (data, metadata, collect) => {
  // https://babeljs.io/docs/babel-parser
  const comments = collect.comments({
    sourceType: "module"
  });
  if (comments) {
      Object.assign(data, comments);
  }
}
```
thanks for your cases to fix typescript parser issue

**Comment by clundstedt-m** [comment]
Awesome!, will take my stab at it on my end as soon as we're done with an SSO upgrade, thanks for this!, btw will close the issue briefly just in order to test it and not having to create another one if something else arises for this particular.

Thanks once again ! and will keep you posted on how it goes

**Comment by clundstedt-m** [comment]
Sorry for taking so long in checking and closing this, checked during the weekend and it worked like a charm, thanks for all your help and guidance, and once again amazing work with the reporter!!!
