### ISSUE TITLE
建议将测试用例名称的tag字符直接渲染

### ISSUE THREAD

**Issue by jiawen94** [cenfun/monocart-reporter#101]
你好晨风：
我最近升级到2.4.1之后发现，原先测试用例标题的tag字符是直接渲染成色块的，新版本没有直接渲染，而是显示@XXX原始字符，在标题后面追加渲染的字符串。我觉得旧版本的渲染方式更优雅美观，希望可以改过来。
谢谢~
![image](https://github.com/cenfun/monocart-reporter/assets/29114225/55b5614a-91c1-4d8f-b4c9-715c72118c74)
![image](https://github.com/cenfun/monocart-reporter/assets/29114225/fac1d401-c382-45ab-a55a-9f53a384436e)

**Comment by cenfun** [comment]
是的，这是Playwright官方新版(1.42)的一个改动，它支持单独写tag，看这里 https://playwright.dev/docs/test-annotations#tag-tests
也就是不用在test的title写tag了，数据与title分离了，为了官方Playwright保持一致就成这样了，官方html报告也是这样的，title里面的只是显示成文字

当然实在要支持原来的也行，因为存在2部分的tag，所以得去掉重复的，你觉得呢，还是说写成新的格式的？

**Comment by jiawen94** [comment]
刚才试了下tag的新特性，确实可以写在title里面，也可以单独写。
我觉得：
如果tag在title里面，直接按照原来的渲染；如果tag单独写，则单独渲染。
不知道这样的处理逻辑是否合理

**Comment by cenfun** [comment]
可以，等我改好发个新版

**Comment by cenfun** [comment]
试试 monocart-reporter@2.4.2

**Comment by jiawen94** [comment]
谢谢！新版本试了下，满足期望的效果。
