### ISSUE TITLE
Merge playwright and vitest v8 coverage reports

### ISSUE THREAD

**Issue by fsblemos** [cenfun/monocart-reporter#102]
Hi, first of all, thank you for this amazing project it's a life saver.

So, I generated two reports with two different settings:

Playwright:

```js
{
    name: 'e2e tests with playwright',
    outputFile: path.resolve(e2eReportsDir, 'monocart-report.html'),
    logging: 'debug',
    coverage: {
      outputDir: e2eCodeCoverageDir,
      sourcePath: filePath => {
        const prefix = 'localhost-6006/';

        if (filePath.startsWith(prefix)) {
          return filePath.slice(prefix.length);
        }

        return filePath;
      },
      lcov: true,
      reports: [
        ['raw'],
        ['v8']
    }
  };
}
```

Vitest:

```js
{
    name: 'unit tests with vitest',
    outputFile: path.resolve(unitReportsDir, 'monocart-report.html'),
    outputDir: unitCodeCoverageDir,
    lcov: true,
    logging: 'debug',
    reports: [
      ['raw'],
      ['v8']
    ]
  }
```

Playwright runs over a Storybook server, and gives me the following report:

<img width="1881" alt="image" src="https://github.com/cenfun/monocart-reporter/assets/14933454/35ee730a-6a2b-42f5-a828-b064fd789515">

And vitest:

<img width="1914" alt="image" src="https://github.com/cenfun/monocart-reporter/assets/14933454/1556b8ee-2a36-458a-8e2b-fc23e97f90b0">

Then I have a merge config:

```js
 {
    name: 'Merged Coverage Report',
    inputDir: [
      path.resolve(__dirname, '../reports/e2e/coverage/raw'),
      path.resolve(__dirname, '../reports/unit/coverage/raw')
    ],
    outputDir: path.resolve(__dirname, '../reports/merged'),
    reports: [['v8-json'], ['v8'], ['console-summary'], ['lcov']]
  }
```

My issue is, the sourcemap is correctly being loaded and it shows the coverage correctly for both cases (including in the HTML report, de BgButton.vue is rendered perfectly considering the sourcemap). But when I merge both, they don't match since the merge understands they are different files.

I found that the merge is done by a hash id based on filePath and source code. The file path is matching, but as we can see in the images above, the generated source code from storybook run and node vitest are different so they are not understood as the same file.

Shouldn't the merge consider the "pretty" source mapped file instead of the raw ones? Am I missing something?

**Comment by cenfun** [comment]
![image](https://github.com/cenfun/monocart-reporter/assets/334577/39ad8506-cbde-426e-91b8-e8694081bc77)

I note that you used option `logging=debug`, so there are some files in the list just for debug, see the debug icon:
![image](https://github.com/cenfun/monocart-reporter/assets/334577/3ab8e09a-7ea8-43cd-b4be-d708ac30f9ec)
We can't merge the coverage of these debug files because they have different content, even if the paths are the same. In fact we should ignore the debug files, please sets `logging=info`.

When the sourcemap is correctly being loaded and the source files should be in the list. see icon:
![image](https://github.com/cenfun/monocart-reporter/assets/334577/83c5911d-c648-4bf5-b665-a112ce13bc45)
We have the opportunity to merge the coverage of these files if their paths and contents are the same.

**Comment by fsblemos** [comment]
Before setting to debug mode, I was debugging with console logs inside the code when I realized the generated ids should match for merging, and that the id depends on the source code, then I turned it on to check. 

Without the debug mode, here's the merge result:

<img width="1525" alt="image" src="https://github.com/cenfun/monocart-reporter/assets/14933454/9c347384-bb2c-4d2e-8e05-147ebd657037">

You can see two `BgButton.vue`, they were not merged and I suspect that is because of the different source codes, since the generated id is still different event with the same sourcePath:

<img width="1503" alt="image" src="https://github.com/cenfun/monocart-reporter/assets/14933454/e4dcc077-6cc5-4140-a509-d9be262357e0">

**Comment by cenfun** [comment]
yes, in order to merge, there are two conditions:
1, same content, I note two `BgButton.vue` should be same content both are 3181 bytes
2, same path, according to the screenshot of the list, they are in different directories.
- looks like first one is `src/components/button/BgButton.vue/BgButton.vue`
- and second one is `src/component/button/BgButton.vue`
Please try `sourcePath` option to unify the path, for example:
```js
{
    sourcePath: {
        // replace double `BgButton.vue` with single one
        "BgButton.vue/BgButton.vue": "BgButton.vue"
    }
}
```


![image](https://github.com/cenfun/monocart-reporter/assets/334577/92962b2a-4841-4f4a-86d4-15973994c948)

**Comment by fsblemos** [comment]
The paths are the same (the item 5 is out of the BgButton group there with item 1), but I was actually trying to figure out why they are showing separated in the report.

In the last screenshot I shared, the source path printed are the same but the generated ids are different.

I've tried before but gonna try some more options with sourcePath. But as far as I could get until now I don't think the path is the problem, because they look right in the report and in the console log :/

**Comment by cenfun** [comment]
OK, let me clarify two types of files:
- 1, entry file (filter by `entryFilter`)
The entry file include coverage data(required), source(required) and sourcemap(optional) like:
  - url `http://localhost:6006/src/components/button/BgButton.vue` => sourcePath `src/components/button/BgButton.vue`
  - url `file:///users/ernanda/workdev/bridge/src/components/button/BgButton.vue` => sourcePath `src/components/button/BgButton.vue`
Note that the `sourcePath` is just the file path converted from url, not the path of its source. 
If the sourcemap is correctly being loaded, this entry file will be removed or become a debug file.

2, source file (filter by sourceFilter)
The source file is extracted from the sourcemap. It doesn't include any coverage data, it only contains the source code.
It also has a `url` and `sourcePath` which converted from the url. 

The path what we are talking about is the `sourcePath` of the source file, not the `sourcePath` of the entry file.
I'm not sure if I've explained it clearly. or see [here](https://github.com/cenfun/monocart-coverage-reports?tab=readme-ov-file#using-entryfilter-and-sourcefilter-to-filter-the-results-for-v8-report)

**Comment by fsblemos** [comment]
Thank you for clarifying, it makes sense.

By adding the sourcePath `sourcePath: { 'src/components/button/': '' }` to the unit setup, I got the following:

<img width="2076" alt="image" src="https://github.com/cenfun/monocart-reporter/assets/14933454/d4682d3d-357f-40a4-b21e-12b654634819">


Then added the follwing to the e2e:

```js
sourcePath: filePath => {
        const prefix = 'localhost-6006/';

        if (filePath.startsWith(prefix)) {
          return filePath.replace('src/components/button/', '').slice(prefix.length);
        }

        return filePath;
}
```

Also added a filter to ignore entries from other sources to the e2e (like localhost, etc): `entryFilter: '**/src/components/button/!(*.stories).{ts,vue}',`:

<img width="2019" alt="image" src="https://github.com/cenfun/monocart-reporter/assets/14933454/e45cd79b-a50b-4a2e-afe2-eefcef978c18">



Now I feel they are much more likely to merge, but I'm still missing something (probably something related to that different URL in the table?):

<img width="1712" alt="image" src="https://github.com/cenfun/monocart-reporter/assets/14933454/6bbcce66-0758-45a5-aa1e-e3fb33d45e59">

**Comment by fsblemos** [comment]
Actually, based on you explanation, that URL is the entry file URL and it should not interfere on the merge (only the source path, which seems correct now). But looks like the entry file URL being different also change the merge result?

**Comment by fsblemos** [comment]
oh, that's it! perfect:

<img width="1341" alt="image" src="https://github.com/cenfun/monocart-reporter/assets/14933454/9cdeb36b-2562-4ae9-a491-615a3986dcbb">

Thank you very much!

Just one last silly question: how can I keep the grouping I had before normalizing the path? Is it possible to keep the source path in the report only?

**Comment by cenfun** [comment]
Good question. 
It supposed to be complete source path like `src/components/button/BgButton.vue` rather than `BgButton.vue`. 
However, this path comes from the sourcemap. It should be a issue with the sourcemap if the path is not complete.
I'm not sure there's a good approach, but you might try adding dir for these specific files.
```js
{
    sourcePath: (filePath) => {
        if (!filePath.includes("/")) {
            return ``src/components/button/${filePath}`;
        }
        return filePath;
    }
}
```

**Comment by fsblemos** [comment]
hmm, I get it.. vitest is running with my Vite config, so as the Storybook with `@storybook/vue3-vite` but merging the same config:

```
// .storybook/main.js
module.exports = {
  ...
  framework: {
    name: '@storybook/vue3-vite',
    options: {}
  },
  async viteFinal(sbConfig) {
    return mergeConfig(sbConfig, myViteConfig); 
  }
};

```

Since unit tests are coming with the full path, maybe is something related with the storybook's vite config, I'll check on this and share here. Maybe I share a minimal reproduction if don't figure it out.

Thank you for all your work, help and patience!

**Comment by cenfun** [comment]
I tried Storybook@8 today and found that the sourcemaps it generates might be non-standard (test with both vite and webpack)
You can try following before finding a better approach:
- `monocart-coverage-reports` version >= 2.7.1
- using the `dirname` of `distFile`
```js
import path from 'path';
const coverageOptions = {

  sourcePath: (filePath, info) => {
        if (!filePath.includes('/') && info.distFile) {
            return `${path.dirname(info.distFile)}/${filePath}`;
        }
        return filePath;
    }

};
```
