### ISSUE TITLE
Post monocart-reporter installation, execution happens only on chrome

### ISSUE THREAD

**Issue by edwardjobs** [cenfun/monocart-reporter#104]
Post monocart-reporter installation, execution happens only on chrome/first browser in config file.
was there any config file change/update needed?
if i uninstall monocart-reporter package, i can run on all browsers.
again after installation, the execution happens only on chrome browser or /first browser in config file.
also by default the execution is headless even i opted for headless=false.

Thank you.

**Comment by cenfun** [comment]
Can you provide us reproduction steps? So we can reproduce it locally?

**Comment by edwardjobs** [comment]
I have 8 tests in one file and monocart-reporter not installed yet.
enabled 3 browsers in config file and executed the file and got 24 test results.
then installed monocart-reporter:
$ npm i -D monocart-reporter

added 62 packages, and audited 71 packages in 10s

5 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

added below options to config file:
const date = new Date().toISOString().slice(0, 10); //2022-10-10
const outputDir = `./test-results/${date}`;
module.exports = {
  reporter: [
    ['list'],
    ['monocart-reporter', {
      name: `NursingHomeAssessment-html-report ${date}`,
      outputFile: `${outputDir}/index.html`,
      trend: './test-results/report.json',

      // custom columns
      columns: (defaultColumns) => {

        // insert custom column(s) before a default column
        const index = defaultColumns.findIndex((column) => column.id === 'duration');
        defaultColumns.splice(index, 0, {
          // define the column in reporter
          id: 'owner',
          name: 'Owner',
          align: 'center',
          searchable: true,
          styleMap: {
            'font-weight': 'normal'
          }
        })
      },
    }
    ]
  ]
};

Ran the same file with same command as before:
now the execution is headless
the execution happened only on chrome which is my 1st option in config file.
report generated for only 8 tests and other 2 browsers are not executed on.

now i commented chrome in config file and ran again:
this time again 8 tests are executed on Edge browser but Firefox is not used for execution.

i uninstalled monocart-reporter and uncommented chrome and ran same file with 8 tests:
now i got 24 test results and browsers are opened even i did not change headless true or false.

if you are looking for specific details, please let me know.

**Comment by cenfun** [comment]
That's weird.  Technically speaking, custom reporter will not affect the operation of Playwright.
here is a exmaple for multiple browsers:
https://github.com/cenfun/monocart-reporter-examples/blob/main/tests/projects/playwright.config.js
It seems works well
![image](https://github.com/cenfun/monocart-reporter/assets/334577/a6b8d9cf-4247-4650-bef8-5b76f59dbb07)
Did you used latest version of Playwright? and what is the version of monocart-reporter, and also Node.js version?

**Comment by cenfun** [comment]
Can you share the full playwright config file?
You said that you enabled 3 browsers in config file, I didn't see these in the config you provided.
![image](https://github.com/cenfun/monocart-reporter/assets/334577/3e0fb4da-7753-490a-87c9-65d30eae852e)

**Comment by edwardjobs** [comment]
Please see the full config file:

import { defineConfig, devices } from '@playwright/test';
// playwright.config.ts
import { PlaywrightTestConfig } from '@playwright/test';

const config: PlaywrightTestConfig = {
  // For browser actions
  testMatch: /.*\.js/,
  use: {

  },

}
const configa = {
  use: {
    screenshot: 'on',
    setTimeout: 600000,

  },
  launchOptions: {
    slowMo: 2000,
    args: ["--start-maximized"],
  },
};

const date = new Date().toISOString().slice(0, 10); //2022-10-10
const outputDir = `./test-results/${date}`;
module.exports = {
  reporter: [
    ['list'],
    ['monocart-reporter', {
      name: `NursingHomeAssessment-html-report ${date}`,
      outputFile: `${outputDir}/index.html`,
      trend: './test-results/report.json',

      // custom columns
      columns: (defaultColumns) => {

        // insert custom column(s) before a default column
        const index = defaultColumns.findIndex((column) => column.id === 'duration');
        defaultColumns.splice(index, 0, {
          // define the column in reporter
          id: 'owner',
          name: 'Owner',
          align: 'center',
          searchable: true,
          styleMap: {
            'font-weight': 'normal'
          }
        })
      },
    }
    ]
  ]
};
//export default config;

export default defineConfig({
  testDir: './tests',
  // testDir: './pomtests',
  /* Run tests in files in parallel */
  fullyParallel: false,
  retries: 0,
  testMatch: ["login.test.ts"],
  /* Fail the build on CI if you accidentally left test.only in the source code. */
  forbidOnly: !!process.env.CI,
  workers: process.env.CI ? 1 : undefined,
  /* Reporter to use. See https://playwright.dev/docs/test-reporters */
  reporter: [["dot"], ["json", { outputFile: "test-result.json" }], ["html", { open: "always" }],

  /* Shared settings for all the projects below. See https://playwright.dev/docs/api/class-testoptions. */
  use: {
    /* Base URL to use in actions like `await page.goto('/')`. */
    // baseURL: 'http://127.0.0.1:3000',
    baseURL: "",
    headless: false,
    /* Collect trace when retrying the failed test. See https://playwright.dev/docs/trace-viewer */
    trace: 'on-first-retry',
    //screenshot: 'only-on-failure',
    screenshot: 'on',
    //video: 'retain-on-failure',
    video: 'on',

  },


  /* Configure projects for major browsers */
  projects: [
    {
      name: 'chromium',
      // use: { ...devices['Desktop Chrome'] },

      use: {
        ...devices['Desktop Chromium'],
        viewport: null,

        launchOptions: {
          args: ["--start-maximized"]
        }
      },
    },

    {
      name: 'Microsoft Edge',
      use: {
        // Supported Microsoft Edge channels are: msedge, msedge-beta, msedge-dev, msedge-canary
        channel: 'msedge',
        launchOptions: {
          args: ["--start-maximized"]
        }

      },
    },

    {
      name: 'firefox',
      use: { ...devices['Desktop Firefox HiDPI'], launchOptions: { args: ["--start-maximized"] } }, //device names can be displayed when ctrl+space is pressed inside the devices array[]
    },

    /*
  
      {
        name: 'webkit',
        use: { ...devices['Desktop Safari'] },
        
      },
      
  
  },
  
  // Test against mobile viewports. 
       {
         name: 'Mobile Chrome',
         use: { ...devices['Pixel 5'] },
       },
       {
         name: 'Mobile Safari',
         use: { ...devices['iPhone 12'] },
       },
  
      // Test against branded browsers. 
       {
         name: 'Microsoft Edge',
         use: { ...devices['Desktop Edge'], channel: 'msedge' },
       },
       {
         name: 'Google Chrome',
         use: { ...devices['Desktop Chrome'], channel: 'chrome' },
       },
       */

    // Run your local dev server before starting the tests 
    // webServer: {
    //   command: 'npm run start',
    //   url: 'http://127.0.0.1:3000',
    //   reuseExistingServer: !process.env.CI,
    // },
  ],
});

**Comment by cenfun** [comment]
I found the problem, you have the wrong playwright config with a syntax error.
You can't write the js code `export default defineConfig(` and `module.exports = {` in the same file.

**Comment by edwardjobs** [comment]
No. I use typrescript I'm beginner with JS.

**Comment by cenfun** [comment]
I guess so and wish you luck.
It recommend you to use some tools such as `VSCode` and `ESLint`, they can alert you if there are any syntax errors.
