### ISSUE TITLE
merge() doesn't honor trace traceViewerUrl option

### ISSUE THREAD

**Issue by brianlwatson** [cenfun/monocart-reporter#105]
Using version 1.7.13

I have a case where I'm merging reports where the traceViewerUrl is set in the sharded jobs (via playwright.config.ts > reporters) and then those artifacts are then passed to a new domain (ci job) where the traceViewerUrl needs to be set manually. I tried setting the new desired traceViewerUrl in the merge function, but the traceViewerUrl value seems to be coming from the sharded reports still.

Example:
If my shards were originally created in playwright.config.ts with a traceViewerUrl of https://ci-account/jobs/123, https://ci-account/jobs/124, https://ci-account/jobs/125, and then I merge the sharded results in https://ci-account/jobs/126, I'd like to be able to set traceViewerUrl in the merge script (similar to the merge example from the docs) like so:

await MonocartReporter.merge(reportDataList, {
    ...
    traceViewerUrl: 'https://ci-account/jobs/126'
...})

However, it seems that the merged result is still using the traceViewerUrl from one of the shards (123/124/125) where the sharded data might not be available at that url anymore.

Am I missing something or is this not supported?

**Comment by cenfun** [comment]
It should be fixed in version monocart-reporter@2.4.3
you can set `traceViewerUrl` in the merge script
```js
await MonocartReporter.merge(reportDataList, {
...
traceViewerUrl: 'https://ci-account/jobs/126'
...
})
```
