### ISSUE TITLE
[REQUEST] Integration with browser stack tc management

### ISSUE THREAD

**Issue by jensencp7** [cenfun/monocart-reporter#107]
Hi Cen,

Hope you are well ! Please can we get integration to browser stack tc .. It would be great to update test results etc from monocart

Please see the below docs 

https://www.browserstack.com/docs/test-management/api-reference/test-runs#add-test-result-to-test-run

**Comment by cenfun** [comment]
Thanks, i will give it a try and see if it works.

**Comment by cenfun** [comment]
I added a example here: https://github.com/cenfun/monocart-reporter-examples/tree/main/integrations/browserstack

I can't create test run with api, it response `{ status: 500, error: 'Internal Server Error' }`, I don't know why. 
but I can add test case result to a exits test run.

**Comment by jensencp7** [comment]
ok thanks Cen, let me iron out the issues , ill do more testing with browserstack then we can add this as an official integration into monocart and update the documentation , if you are happy with this ? Please close for now

**Comment by cenfun** [comment]
sounds great. please let know if any feedback for the issue. I will update the example and test if it works then. thnaks
