### ISSUE TITLE
]Question] - How to correct configure custom tags?

### ISSUE THREAD

**Issue by Aroot42** [cenfun/monocart-reporter#11]
Hello.
I create custom tags in my playwright.config file
![image](https://user-images.githubusercontent.com/100360547/230081210-3276f552-cba8-474f-8e9b-5533dfc29a54.png)
After executing the tests, I opened the report file only to find that it contained tags that were completely different from the ones I had specified in the configuration. Instead of displaying only the test names that had the '@' symbol in their tags, the report included all code chunks that had the '@' symbol.
![image](https://user-images.githubusercontent.com/100360547/230082031-91e3ce91-ea27-4af0-bf69-08d513c13af6.png)

**Comment by cenfun** [comment]
this is a bug, I will fix it. 
It should not collect TAGs from Step's title

**Comment by Aroot42** [comment]
I have update report to [v1.6.6](https://github.com/cenfun/monocart-reporter).
I create custom tags in my playwright.config file
![image](https://user-images.githubusercontent.com/100360547/230560610-dc3ad6ce-dde3-4f79-ad6e-a9b152247c4a.png)
But in my report I cannot see any tags
![image](https://user-images.githubusercontent.com/100360547/230560782-ac705036-1f65-4950-9fbd-a61df6d68ebe.png)

**Comment by cenfun** [comment]
do you have added any those tags in test title?
for example
test(" title @passed ", ()=> {})
Not that passed, failed , flaky in your tags is tag name, not status.

**Comment by i-novo** [comment]
Is it expected that tags are collected from `test` only, now they are not collected from descriptions?

**Comment by cenfun** [comment]
yes. tags are collected from `test` only
- tag works with playwright `--grep`  https://playwright.dev/docs/test-annotations#tag-tests
- `descriptions` is a custom column?  custom column collect from comments. The definition of tag conflicts with the definition of annotation, both are starts with `@`

**Comment by i-novo** [comment]
oh, sorry I meant _test.describe_ ("@tag") in most cases I use tags in the _test.describe_ (not to overload _test_ text) to grep them by script

**Comment by cenfun** [comment]
@i-novo  sorry for the side effects, ·test.describe· has been restored for tags in version monocart-reporter@1.6.8
