### ISSUE TITLE
[Suggest ] 建议 playwright的进程被ctrl +c 或者vscode 插件 关闭后，monocart-reporter仍输出报告

### ISSUE THREAD

**Issue by jiawen94** [cenfun/monocart-reporter#117]
现状：
使用微软的默认的html测试报告，当我将playwright的npx进程ctrl+c 杀掉（或者vscode 插件的中止按钮）后，仍然会出现测试报告；
![image](https://github.com/cenfun/monocart-reporter/assets/29114225/631be047-46ee-40e5-90b0-fb8d19683663)

使用monocart-reporter进行测试，如果ctrl+c 杀进程（或者vscode 插件的中止按钮），monocart-reporter不会生成报告
期望：
使用monocart-reporter进行测试，如果ctrl+c 杀进程（或者vscode 插件的中止按钮），monocart-reporter也生成报告。
因为就算是手工终断playwright，我也想看到前面运行过的test cases的报告详情

**Comment by cenfun** [comment]
是了一下，ctrl+c 杀进程，好像不行，官方的html报告也没有，你确定不是之前的html缓存？
如果是点停止按钮，我不知道你说的是在哪的停止，我看下能不能重新
当从一般意义来说，进程终止了是不可能继续运行的，难道是实时生成的报告？

**Comment by jiawen94** [comment]
电脑不在身边，这个我明后天验证一下

**Comment by jiawen94** [comment]
中途ctrl+c后会提示Terminate batch job (Y/N)? ，我输入y继续中断
测试前删除过playwright-report文件夹，测试后也比对过报嘎的测试时间，应该不是之前的缓存。
我简单设计了三个case，在第二个case进行了暂停。官方html报告能正常输出
![image](https://github.com/cenfun/monocart-reporter/assets/29114225/4097d9f3-5d62-4d7b-a000-dc8c011af1da)
![image](https://github.com/cenfun/monocart-reporter/assets/29114225/88e391f2-5577-4e46-9cdd-318292860fc7)

```
import { test, expect } from '@playwright/test';

test('test0', async ({ page }) => {
  await page.goto('https://www.baidu.com/');
  await page.locator('#kw').click();
  await page.locator('#kw').fill('playwright');
  await page.getByRole('button', { name: '百度一下' }).click();

});

test('test1', async ({ page }) => {
  await page.goto('https://www.baidu.com/');
  await page.locator('#kw').click();

  await page.waitForTimeout(5_000)
  await page.locator('#kw').fill('hehehe');
  await page.getByRole('button', { name: '百度一下' }).click();


});

test('test2', async ({ page }) => {
  await page.goto('https://www.baidu.com/');
  await page.locator('#kw').click();


  await page.waitForTimeout(5_000)
  await page.locator('#kw').fill('hehehe');
  await page.getByRole('button', { name: '百度一下' }).click();
});

```

**Comment by cenfun** [comment]
我也是测试之前删除html的文件夹，ctrl+c后并没有产生任何html的文件
- 一次ctrl+c后输入y终止试过
- 连续多次ctrl+c终止也试过
不知道你用的什么版本和操作系统还有nodejs版本，不知道有没有关系
要不，你把你这个简单例子提交到一个仓库吧，我clone下来按照你的步骤试试
如果能重现，应该追踪html的实现方式，谢谢

**Comment by jiawen94** [comment]
好的，仓库准备好了跟你说下
版本信息：
node: 20.10
Playwright Test v1.42.1
windows11

终端为vscode底下的windows powershell终端（未开管理员模式）

**Comment by jiawen94** [comment]
仓库 https://github.com/jiawen94/playwright-code-snippet

**Comment by cenfun** [comment]
看起来好像真的可以，你这个仓库，我按ctrl+c就立即显示`To open last HTML report run`说明已经触发了生成报告
我研究一下，谢谢这个例子

**Comment by cenfun** [comment]
然后，我增加了'monocart-reporter'好像也可以触发，只是稍微慢一点，要不你再试试？
```sh
Running 3 tests using 1 worker

  ✘  1 [debug] › test-1.spec.ts:3:5 › test0 (727ms)
终止批处理操作吗(Y/N)?
  1 interrupted
    [debug] › test-1.spec.ts:3:5 › test0 ───────────────────────────────────────────────────────────
  2 did not run
[MR] generating report data ...
[MR] generating test report ...
[MR] My Report
┌─────────────┬────────────────────┐
│ Tests       │ 3                  │
│ ├ Passed    │ 0 (0.0%)           │
│ ├ Flaky     │ 0 (0.0%)           │
│ ├ Skipped   │ 3 (100.0%)         │
│ └ Failed    │ 0 (0.0%)           │
│ Steps       │ 14                 │
│ Suites      │ 1                  │
│ ├ Projects  │ 1                  │
│ ├ Files     │ 1                  │
│ ├ Describes │ 0                  │
│ └ Shards    │ 0                  │
│ Retries     │ 0                  │
│ Errors      │ 0                  │
│ Logs        │ 0                  │
│ Attachments │ 2                  │
│ Artifacts   │ 0                  │
│ Playwright  │ v1.42.1            │
│ Date        │ 2024/5/13 11:33:56 │
│ Duration    │ 2.1s               │
└─────────────┴────────────────────┘
[MR] html report: test-results/report.html (json: test-results/report.json)
[MR] view report: npx monocart show-report test-results/report.html

To open last HTML report run:

  npx playwright show-report

y
```
而我自己的项目，好像无论是html还是monocart都没有触发报告
我感觉是playwright本身的问题，因为自定义报告，包括官方的报告，实际上就是监听回调事件执行而已，这个回调事件得playwright内核通知报告
- 如果通知了，无非是先后执行的问题，html顶多在monocart前面执行
- 如果因为某些条件没有通知，那么都没有通知，总不可能偏心，只通知自带的html不通知第三方自定义的
- 还有个问题就是终止后的条件限制，毕竟终止了，不允许运行太多太长的任务，可能就被playwright掐掉了也不一定

但目前来说，我还没有找到html里面有什么特别的代码来处理这个特殊情况

**Comment by jiawen94** [comment]
在这个demo里面，我加了monocart-reporter，ctrl+c也能输出报告。而我自己的项目里面却无法输出报告，不清楚是不是项目里面增加了一些功能模块而触发了“ctrl+c中断无法输出报告”的问题。这个复现条件蛮奇怪的，我后面按照你的分析思路验证一下

**Comment by cenfun** [comment]
嗯，谢谢，我也会继续研究一下，感觉还是执行时间限制的问题，如果工作量大，就来不及执行所有的任务
