### ISSUE TITLE
[Bug] in the testrail.js Skipped tests are marked as passed in Testrail testrun 

### ISSUE THREAD

**Issue by craitose** [cenfun/monocart-reporter#118]
**Describe the bug**
In playwright when running tests in series , if the first test fails the others are skipped. Monocart then generates a report that the first test failed and the skipped tests passed. I believe it's because in the testrail.js we have `const status_id = item.ok ? 1 : 5` and also Testrail does not have a skipped status 

**To Reproduce**
- Version: 2.3.1
- Node Version: 20.9.0
- Have you tried the latest version (including node), and does the issue still exist? 
- Steps to reproduce the actual behavior:
1. Execute a playwright test in series
2. Make sure that the 1st test fails
3. Open Testrail and observe the testrun

**Expected behavior**
Expect the skipped tests to have the 'untested' status

**Errors or Screenshots**
Any captured error messages, or add screenshots to help explain your problem.

**Make a minimal reproduction**
- Provide the minimal, reproducible code and options of the bug.
```js

```
- Or provide a GitHub repository with a minimal (but complete) example and simple/clear steps on how to reproduce the bug. 

The simpler you can make it, the more likely we are to successfully verify and fix the bug.

**Additional context**
Tests that have been skipped should not have a status assigned when run in series

**Comment by cenfun** [comment]
Please refer to the following changes:
```js
// 1 Passed
// 2 Untested
// 5 Failed
let status_id = item.ok ? 1 : 5;
if (item.caseType === 'skipped') {
    status_id = 2;
}
```

**Comment by craitose** [comment]
The above changes mark all tests as blocked

**Comment by cenfun** [comment]
Can you add a status id for untested? or what's your untested id? 
Can Testrail use custom status id?

**Comment by craitose** [comment]
There is no status id for untested, so skipped tests should not get a status

**Comment by cenfun** [comment]
This should be the wrong place to ask questions about Testrail. As I know, you can add additional custom statuses under Administration > Customizations in TestRail.
see https://support.testrail.com/hc/en-us/articles/7077935129364-Statuses#getstatuses

**Comment by craitose** [comment]
I am not asking a question about testrail, I am pointing out that monocart gives a status to testcases that have not run

**Comment by cenfun** [comment]
OK, monocart is a playwright custom reporter, I don't think playwright have the status `untested`
see here https://playwright.dev/docs/api/class-testcase

**Comment by cenfun** [comment]
I suggest you go to the Playwright official [community](https://github.com/microsoft/playwright/issues) to see if they can provide an "untested" status for test cases.

**Comment by craitose** [comment]
I changed the code to this:
```
let comment;
if (item.caseTypeId === 'skipped') {
status_id = null;
comment = 'skipped on : ${currentProjectName} > ${item.title}'
 }
else {
comment = 'executed on : ${currentProjectName} > ${item.title}'
}
```
