### ISSUE TITLE
[BUG] - Incorrect Playwright version displayed in report

### ISSUE THREAD

**Issue by Aroot42** [cenfun/monocart-reporter#12]
Hello.
It seems I found a problem with incorrect displaying Playwright version is report.
I have a branch with alpha version 'Playwright v1.33.0-alpha-apr-3-2023'. I work in this branch and run tests. After that I change branch with version '"@playwright/test": "^1.32.1",'
![image](https://user-images.githubusercontent.com/100360547/230083713-b9d4723d-20bd-4123-b5c6-bd7de4454912.png)
But report display alpha version from first branch
![image](https://user-images.githubusercontent.com/100360547/230083832-5636adf3-e12a-421d-a909-a04b45ab8de0.png)

**Comment by cenfun** [comment]
did you reinstalled @playwright/test?
the version is come from playwright config:
https://github.com/cenfun/monocart-reporter/blob/main/lib/generate-data.js#L83
so can you clean npm cache, reinstall dependencies and test again?

**Comment by Aroot42** [comment]
Yes, you are right. I have check playwright version
_npx @playwright/test --version
Version 1.33.0-alpha-apr-3-2023_
That surprised me. I was expecting to see a version that was made in this thread.
