### ISSUE TITLE
github summary

### ISSUE THREAD

**Issue by BrunoCD** [cenfun/monocart-reporter#120]
Is there a way to print the output of the summary to github so it can be seen at the end of the run?

**Comment by cenfun** [comment]
It should print the summary to github by default.
![image](https://github.com/cenfun/monocart-reporter/assets/334577/a923800c-b836-4c57-b1a5-ada296631151)
see https://github.com/cenfun/monocart-reporter/actions/runs/9231893508/job/25402398312
And also you can print anything you want with `onEnd` hook
```js
// playwright.config.js
module.exports = {
    reporter: [
        ['monocart-reporter', {  
            name: "My Test Report",
            outputFile: './test-results/report.html',
            // async hook after report data generated
            onEnd: async (reportData, helper) => {
                console.log(reportData.summary);

                // find a test by title
                const myCase = helper.find((item, parent) => item.type === 'case' && item.title.includes('inline tag'));
                console.log(myCase && myCase.title);

                // find a suite by title
                const mySuite = helper.find((item, parent) => item.type === 'suite' && item.title.includes('new syntax'));
                console.log(mySuite && mySuite.title);

                // filter failed cases
                const failedCases = helper.filter((item, parent) => item.type === 'case' && item.caseType === 'failed');
                console.log(failedCases.map((it) => it.title));

                // Iterate all items
                helper.forEach((item, parent) => {
                    // do something
                });

            }
        }]
    ]
};
```

**Comment by BrunoCD** [comment]
I understand that this is part of the run. Since, I am sharding the tests:
npx playwright test --shard=1/4, etc
I want the output to show up in the SUMMARY page of github with the total number of tests instead of the individual shards
Let's say if shards have 20 tests per, and I have 4 shards, I want to see:
Playwright Results
![image](https://github.com/cenfun/monocart-reporter/assets/3846358/867879e5-3da1-4ca6-9a69-cf8f13c156f3)


Is this possible ? How?

**Comment by cenfun** [comment]
Yes, of course. see [Merge Shard Reports](https://github.com/cenfun/monocart-reporter?tab=readme-ov-file#merge-shard-reports)
