### ISSUE TITLE
[Bug] 通过vscode官方扩展运行playwright，monocart报告的自定义字段会重复展示

### ISSUE THREAD

**Issue by jiawen94** [cenfun/monocart-reporter#122]
**Describe the bug**
通过vscode官方扩展运行playwright，monocart报告的自定义字段会重复展示
如图，自定义的owner 和mantisBT 字段重复出现，规律是运行几次就重复几次，除非重启vscode。
![image](https://github.com/cenfun/monocart-reporter/assets/29114225/8cd795af-b6fc-4e7c-846e-fc61a60f12c8)
目前这个问题只出现在vs code里面运行，命令行运行没有这种问题

**To Reproduce**
- Version: 
"monocart-reporter": "^2.4.8",
"playwright/test": "^1.44.1",
vscode playwright插件 1.1.6
macOS 14.5

- Have you tried the latest version (including node), and does the issue still exist?  
Yes

- provide a GitHub repository with a minimal (but complete) example and simple/clear steps on how to reproduce the bug. 
https://github.com/jiawen94/playwright-code-snippet/tree/monocart-issue-122

**Comment by cenfun** [comment]
It should be fixed, try monocart-reporter@2.4.9

**Comment by jiawen94** [comment]
谢谢，2.4.9 测试OK了

**Comment by jiawen94** [comment]
发现changelog的fixed repeated columns (#122)对应的版本写错了，应该是2.4.9而非2.4.8

**Comment by cenfun** [comment]
感谢提醒，下次改一下就行
