### ISSUE TITLE
[Feature Request] 希望详情里面得Steps支持虚拟滚动

### ISSUE THREAD

**Issue by 52flutter** [cenfun/monocart-reporter#125]
我们得场景有粗粒度得场景和精细用例，粗场景根据UI规范来进行全页面扫描，因此steps可能非常长，打开报告卡顿。或者支持配置默认只显示失败得也可以

**Comment by cenfun** [comment]
在详细页面是吧？目前是默认显示所有，点击后才能仅显示错误，你是说加一个配置默认仅显示错误？
能说一下你们的steps最多有多少么？如果能给个测试数据更好（上传一个json报告）
这样比较好根据数量来自动优化性能

**Comment by 52flutter** [comment]
有邮箱不

**Comment by 52flutter** [comment]
或这加个wx？

**Comment by cenfun** [comment]
发邮箱吧 cenfun@qq.com

**Comment by 52flutter** [comment]
已发送，注意查收

**Comment by cenfun** [comment]
没想到这个case的steps有8k多，原来的功能是支持点击定位到step的，这样如果要改成虚拟动态渲染，改动不小

**Comment by 52flutter** [comment]
或者加个筛选 可以配置成默认加载失败得

**Comment by 52flutter** [comment]
开关

**Comment by 52flutter** [comment]
还有个问题就是这个
![image](https://github.com/cenfun/monocart-reporter/assets/11569655/c1b75e1d-386d-4fcb-a936-027e62d78844)
这个筛选按钮 没办法过滤出来叶子节点的错误

**Comment by cenfun** [comment]
![image](https://github.com/cenfun/monocart-reporter/assets/334577/db30fbde-9f2c-43c0-ba98-87ef6a62ad9f)
新版本将考虑分离steps，这样才能解决性能问题，而且可以支持搜索

**Comment by cenfun** [comment]
@52flutter 试试新版本monocart-reporter@2.5.0
还是使用回了原有的方式，但也实现了列表动态渲染，就算上万条应该都不会有性能问题了
