### ISSUE TITLE
[Question] how to access the report from remote server

### ISSUE THREAD

**Issue by stevez** [cenfun/monocart-reporter#129]
I would like to publish the reports to a remote server, so that I can view them from the browser, also collect the historical data.
I would like you to provide the suggestions or solutions:
- recommend a better server to render your report 
- best way to publish report
- examples

Thank you

**Comment by cenfun** [comment]
> recommend a better server to render your report

The generated report is just HTML and js files. There is no requirement for server rendering. The report is rendered directly on the client side by the browser.  Any server that supports HTTP or HTTPS is OK.

> best way to publish report

Just upload the static files to server. It would be better if compress all files into one zip file and then upload it.

> examples

Use datetime as the `outputDir`
```js
// playwright.config.js
// attachments outputDir and report outputFile used same folder
const date = new Date().toISOString(); //2024-06-26T23:58:13.983Z
const outputDir = `./test-results/${date}`;
module.exports = {
    outputDir: outputDir,
    reporter: [
        ['monocart-reporter', {  
            name: `My Test Report ${date}`,
            outputFile: `${outputDir}/index.html`
        }]
    ]
};

// after uploading to server
// http://your.report.site/test-results/-06-26T23:58:13.983Z

```

> collect the historical data

There is a way to generate a trend chart, it requires to provide the data json of the prerious report.
```js
// playwright.config.js
module.exports = {
    reporter: [
        ['monocart-reporter', {  
            name: "My Test Report",
            outputFile: './test-results/report.html',
            // connect previous report data for trend chart
            trend: './prerious-report-dir/index.json'
        }]
    ]
};
```
You can use the CI artifacts, every time save the report files to artifacts, and download the prerious artifacts for `trend`.
