### ISSUE TITLE
[BUG] - Incorrect time in report

### ISSUE THREAD

**Issue by Aroot42** [cenfun/monocart-reporter#13]
Hello.
I noticed that the time in the report is not correct.
![image](https://user-images.githubusercontent.com/100360547/230084825-f6c4393e-5530-42af-a1fe-1b494c3d37af.png)
97,367 ms = 1 min 37 sec. But report show 1m 53s

Proposal
Display test duration in min and second, not in ms. Or add key in config

**Comment by Aroot42** [comment]
Maybe it time for global-setup part of code? Can in be separated or included separate row in report?
![image](https://user-images.githubusercontent.com/100360547/230094306-b9e3ba02-d3ea-4a53-864f-a0f5cb2c0b96.png)

**Comment by cenfun** [comment]
maybe, it takes time to run any code. I'm afraid it cannot be separated because don't know which part is.
