### ISSUE TITLE
[Bug] debug shows warning message: added empty files for all: undefined  for 'all" config

### ISSUE THREAD

**Issue by stevez** [cenfun/monocart-reporter#131]
**Describe the bug**
playwright config sample: 
all: {
        dir: ['./src'],
        filter: {
            '**/*.tsx': true
        }
    },

Running 2 tests using 2 workers

  ✓  1 [Desktop Chrome] › counter.spec.ts:3:1 › should count by click (2.0s)
  ✓  2 [Desktop Chrome] › app.spec.ts:3:1 › should navigate to the about page (2.1s)
[MCR] added coverage data: istanbul (9ms)
[MCR] added coverage data: istanbul (15ms)
globalTeardown ...
[MCR] added coverage data: istanbul (3ms)

  2 passed (4.1s)
[MR] generating report data ...
[MCR] added empty files for all: undefined
[MCR] added coverage data: istanbul (1ms)

**To Reproduce**
- Version: 2.5.2
- Node Version:  20
- Have you tried the latest version (including node), and does the issue still exist? 
- Steps to reproduce the actual behavior:
1.  checkout my forked example repo with the changes: https://github.com/stevez/nextjs-with-playwright-istanbul/commit/a677203c22befc6cc9784c688509b66186dd4bd7
2.  run npm test
3. show debug message: [MCR] added empty files for all: undefined
4. 

**Expected behavior**

**Errors or Screenshots**
Any captured error messages, or add screenshots to help explain your problem.

**Make a minimal reproduction**
- Provide the minimal, reproducible code and options of the bug.
```js

```
- Or provide a GitHub repository with a minimal (but complete) example and simple/clear steps on how to reproduce the bug. 
https://github.com/stevez/nextjs-with-playwright-istanbul

The simpler you can make it, the more likely we are to successfully verify and fix the bug.

**Additional context**

**Comment by cenfun** [comment]
The `all` option is for `V8` coverage only, not for `istanbul`. 
We don’t have enough time to support all the features of Istanbul, since you can use Istanbul itself via `nyc` rather than `mcr`.
Istanbul is in `mcr` just provide the format of reports.
