### ISSUE TITLE
[Question] Ability to configure default tests' grouping levels before report generation

### ISSUE THREAD

**Issue by anemer** [cenfun/monocart-reporter#137]
Today, monocart reporter displays, in the generated report, the set of tests by levels.

Default enabled levels are : "_Project_", "_File_", and "_Describe_". The "_Step_" level is disabled by default.
In the report's UI, it is possible to enable/disable grouping for each of those levels. And that's great!

Is it possible to configure which levels I want to be enabled/disabled by default, **before report generation**?

Thanks.

**Comment by cenfun** [comment]
please try monocart-reporter@2.6.4 with new option `groupOptions`
```js
// playwright.config.js
module.exports = {
    reporter: [
        ['list'],
        ['monocart-reporter', {  
            name: "My Test Report",
            outputFile: './test-results/report.html',
            groupOptions: {
                group: true,

                shard: true,
                project: true,
                file: true,
                describe: true,
                step: false,

                merge: false
            }
        }]
    ]
};
```

**Comment by anemer** [comment]
Thank you! It works like a charm.
