### ISSUE TITLE
[Bug] Selecting a tag in the dropdown of the search box does not add the tag to the search box, it adds the text of the tag

### ISSUE THREAD

**Issue by edumserrano** [cenfun/monocart-reporter#138]
**Describe the bug**
Selecting a tag in the dropdown of the search box does not add the tag to the search box, it adds the text of the tag. Meaning what is added does not start with "@" char.

**To Reproduce**
- Version: 2.6.3
- Node Version:  20.16.0
- Have you tried the latest version (including node), and does the issue still exist? yes
- Steps to reproduce the actual behavior:
1.  Create a Playwright test with a tag. I used the "latest" way to create tags which is to use the testDetails.Tag array instead of adding the tag to the test name.
2.  Run the test to generate the reporter with monocart-reporter.
3.  Open the report.
4.  Go to the search box, click on it and select one of the tags from the dropdown.
5. The selected tag gets added to the input but without the "@" char at start which means it doesn't filter by the tag it just searches for the tag's text.

**Expected behavior**
After selecting a tag from the dropdown of the search box it should add it to the search box starting with the "@" char so that the filter is performed on the tag and not the text of the tag.

**Errors or Screenshots**
Here I have two tags:
![image](https://github.com/user-attachments/assets/943bed5f-2344-47f3-93ea-1cd5bcda4f67)

Selecting the "Console" tag results in searching for the tag's text:
![image](https://github.com/user-attachments/assets/5ad17dd8-718e-4364-b1da-30cbdc053bc0)

But what it should do is search for the tag itself:
![image](https://github.com/user-attachments/assets/9221c30f-77ec-4502-b71f-50e20389d019)

**Comment by cenfun** [comment]
It should be fixed, please try monocart-reporter@2.6.5

**Comment by edumserrano** [comment]
I can confirm it's fixed. Closing this bug. Thank you @cenfun
