### ISSUE TITLE
[Improve] Possibility colapse test step in test result panel

### ISSUE THREAD

**Issue by Aroot42** [cenfun/monocart-reporter#14]
Hello.
I propose to make it possible to collapse the test steps in the test results pane, as it is done in the main panel.
![image](https://user-images.githubusercontent.com/100360547/230559530-5c66abe5-8541-4791-962f-d7b522478c72.png)

The second improvement is to scroll the test result on the fallen step and, if possible, show a screenshot to the fallen step, and not (not only) in the header of the test resilt.

**Comment by cenfun** [comment]
Thanks for your suggestion, I will think about it

**Comment by cenfun** [comment]
fixed in monocart-reporter@1.6.7 please try it.

**Comment by Aroot42** [comment]
I found bug.
I have next structure
![image](https://user-images.githubusercontent.com/100360547/230843657-70004643-3036-4175-a03f-122b4e5965c2.png)
But when I collapse parent test step 'Fill in Text Field' my test step 'Clear field' is hidden but his steps are displayed
![image](https://user-images.githubusercontent.com/100360547/230843972-9c300e16-40e6-48d3-af81-3b75055b9a81.png)


BUG #2
When I collapse grand parent test step, parent test step is hidden, but child test step is displayed
![image](https://user-images.githubusercontent.com/100360547/230844446-44c41251-ee5c-48d4-8e62-edae99396ee0.png)
![image](https://user-images.githubusercontent.com/100360547/230844485-3b00645a-91ef-47c5-90f0-fd3d18cfd736.png)

**Comment by cenfun** [comment]
fixed to monocart-reporter@1.6.9 please try it

**Comment by Aroot42** [comment]
Great. All works fine.
**Proposal**
Collapse all steps except the fallen step.

**Comment by cenfun** [comment]
good point. I will think about how to implement it

**Comment by cenfun** [comment]
try monocart-reporter@1.6.10
![image](https://user-images.githubusercontent.com/334577/231082108-76045e79-a013-4c74-841e-8ccd9c283762.png)

**Comment by Aroot42** [comment]
That's not exactly what I meant. What I meant was to simply collapse all successful steps and focus the tree on the fallen step (scroll through the tree to the fallen step).
![image](https://user-images.githubusercontent.com/100360547/231108127-21e3eee2-38d5-43f5-aa0a-45d3113bab15.png)

Now, when activating a new slider, it becomes completely unclear at what stage of the test the failure occurred, because everything is hidden.

**Comment by cenfun** [comment]
one more switch button added to version monocart-reporter@1.6.11
![image](https://user-images.githubusercontent.com/334577/231226450-69aefccc-359f-4fe6-87bb-deafaf3bfd0d.png)

**Comment by Aroot42** [comment]
Great, that's exactly what I suggested.

One small improvement - if you activate both sliders, only the second 'Only failed' works. I suggest that when one is 'On', the other should be disabled. Or, when you turn 'On' one, automatically switch the other to the "Off" position.

**Comment by cenfun** [comment]
fixed in monocart-reporter@1.6.12
