### ISSUE TITLE
[Bug] Incorrect duration when using Playwright blob merge-report --reporter="monocart-reporter"

### ISSUE THREAD

**Issue by ssfxate** [cenfun/monocart-reporter#144]
**Describe the bug**
I'm running tests in CD/CD using several agents, like sharding, but doing it manually, depending on the PlayWright project. After the tests are finished, I collect the blob reports and merge them.
For the built-in PW HTML report, all the durations equal the results. In the Monocart reporter, I see milliseconds.

**To Reproduce**
- Version: 2.8.0
- Node Version: 18
- [x] Have you tried the latest version (including node), and does the issue still exist?
- Steps to reproduce the actual behavior:
1. Run a PlayWright test with blob reporter
`npx playwright test --reporter=blob`
2. Merge report from this blob report and use Monocart Reporter as a result
`npx playwright merge-reports --reporter="monocart-reporter" ./blob-report`
3. Open the Monocart Reporter HTML
`npx monocart show-report {yourFolder}/monocart-report.html`

**Expected behavior**
Duration is equal to the time it took to *execute*

Actual Results
Duration is equal to the time it took to *render*

**Errors or Screenshots**
![image](https://github.com/user-attachments/assets/2092863b-5d61-4978-887d-ce00626fbac2)
![image](https://github.com/user-attachments/assets/19d28d35-16a2-4b29-8f97-c6f9de13c8f4)

**Comment by cenfun** [comment]
> Merge report from this blob report and use Monocart Reporter as a result
I don't think this is works.
For monocart reporter, we should use `merge` API, see [Merge Shard Reports](https://github.com/cenfun/monocart-reporter?tab=readme-ov-file#merge-shard-reports)
