### ISSUE TITLE
[Bug] Start time and test run duration not showing at the top of the HTML report

### ISSUE THREAD

**Issue by edumserrano** [cenfun/monocart-reporter#146]
**Describe the bug**
Start time and test run duration not showing at the top of the HTML report.

**To Reproduce**
- Version:  2.8.3
- Node Version:  22.9.0
- Have you tried the latest version (including node), and does the issue still exist? yes
- Steps to reproduce the actual behavior:
1.  Run Playwright with monocart-reporter as one of the reporters.
2.  Open the monocart html report.
3.  Notice that the start time and test run duration do not show at the top of the html report, to the right of the report title, only the icons for the start time and test run duration show.

**Expected behavior**
Start time and test run duration should show at the top of the HTML report.

**Errors or Screenshots**

![image](https://github.com/user-attachments/assets/b636c8a5-f016-4fe9-b29b-ced70013938e)

**Make a minimal reproduction**
You can use [this repo](https://github.com/edumserrano/monocart-merge-cli-demo) to reproduce the issue. The version of monocart-reporter in that repo is `2.8.2` but the bug is also present in that version.

After cloning run `npm test` and then `npx monocart show-report test-reporters/monocart-reporter/monocart-report.html` to view the html report.

**Comment by cenfun** [comment]
it should be fixed in v2.8.4

**Comment by edumserrano** [comment]
I can confirm this is now fixed 👍
