### ISSUE TITLE
[Feature Request] merge CLI: accept compressed files 

### ISSUE THREAD

**Issue by edumserrano** [cenfun/monocart-reporter#147]
Hi @cenfun , hope you're not tired of my feature requests 😅

Following up on the recent implementation of the awesome merge cli after #142, I'd like to request an additional option for the `MonocartReporterOptions` which, when set, would result in monocart-reporter output to be zipped. 

Then with this option it would be nice if the merge CLI accepted a list of Zip files for the merge so that instead of running a command like:

```
npx monocart merge path-to/shard*/index.json -o merged-reports/index.html
```

you could run:

```
npx monocart merge path-to/shards -o merged-reports/index.html
```

Where the `path-to/shards` folder would contain all the zip files from sharded test runs. 

I'm asking for this because I've recently implemented Playwright sharded test runs in my CI pipelines and I always have to zip the contents of the monocart-reporter before I store them as pipeline artifacts so that later in the pipeline these can be downloaded, then extracted and merged.

Compressing the contents of the monocart-reporter is done mainly to save space on the pipeline artifacts, which in some CI systems is also something billable. It also has the performance benefit of quicker uploads/downloads of the pipeline artifacts.

This request is really just a small quality of life  improvement, there's nothing new that this allows you to do that you can't do already today. It just avoids repeating the zip/extract code in all of my pipelines.

I'd also argue that the main usage for Playwright sharded test runs are in automated systems like CI pipelines and these systems you will always end up uploading the sharded results somewhere for later processing, meaning you will always prefer to have a compressed output.

**Comment by edumserrano** [comment]
What I don't know is what would be the best way to add this to the `MonocartReporterOptions`. I'm not sure that a single extra property like `compressOutput` would be enough? Not sure if you want to provide a way for people to choose the name of the generated compressed file. For me I think even if you randomized the name or you based it from the `outputFile` property it might be good enough but not sure.

Any thoughts?

**Comment by edumserrano** [comment]
I also realize that currently the merge CLI is given a glob to a list of json files which contain the monocart report data. In the event of using zip (compressed) files, I think you could implement some standard to get to the json files.

For instance, each zip file must contain at the root a single json file which is the report data. Knowing this, once the merge CLI is given a list of zip files, after extracting each zip file, it can then look for those json files at the root of the extracted directories and use those for the merge operation.

**Comment by cenfun** [comment]
please try monocart-reporter@2.9.0
- using `zip` option to output zip file
```js
// playwright.config.js
module.exports = {
    reporter: [
        ['list'],
        ['monocart-reporter', {  
            name: "My Test Report",
            outputFile: './monocart-report/index.html',
            zip: true
        }]
    ]
};
```
- merging with zip files 
```js
const reportDataList = [
    'docs/shard1/index.zip',
    'docs/shard2/index.zip',
    'docs/shard3/index.zip'
];
await MonocartReporter.merge(reportDataList, {
    name: 'My Merged Report',
    outputFile: 'docs/merged/index.html',
    durationStrategy: 'exclude-idle'
});
```
CLI
```sh
npx monocart merge ./docs/shard*/index.zip
```

**Comment by edumserrano** [comment]
I've tested this and can confirm it's working with version `2.9.2`.

The new `zip` output option didn't quite work as I expected though. When setting `zip` to `true` it compressed the output of the `monocart-reporter` but it also left the uncompressed output in the output folder. For instance:

```
output-folder/
├── index.html
├── index.json
└── index.zip
```

Where what I'd expect would just be the compressed file:

```
output-folder/
└── index.zip
```

**Would you consider deleting the uncompressed output when `zip` is set to `true` ? Or do you have a reason to keep it when `zip` is set to `true`?**

The reason I'm asking is that the main reason for this new `zip` option is for pipeline integration (and sharded test runs). And when I get the zipped output I don't really care about the uncompressed files. Some CI pipeline make it easy for you to upload files from a folder that match a glob, but not all. For instance, in my CI system, what I have to do is delete all the uncompressed files before I can upload the `output-folder` as a pipeline artifact.

**Comment by cenfun** [comment]
I've thought about this issue too, but I haven't found a good reason to delete the uncompressed files.
there are 2 possible solutions:
- 1, using `output-folder/index.zip` as your pipeline artifact
- 2, try new version `monocart-reporter@2.9.3` and customize the zip file path
```
// playwright.config.js
module.exports = {
    reporter: [
        ['list'],
        ['monocart-reporter', {  
            name: "My Test Report",
            outputFile: './monocart-report/index.html',
            zip: “./my-zip-file-dir/my-zip-file-name.zip”
        }]
    ]
};
```

**Comment by edumserrano** [comment]
> I've thought about this issue too, but I haven't found a good reason to delete the uncompressed files

The main reason for me is about what to upload as the pipeline artifact. After running the playwirght tests I want to upload just the zipped file and to do that:

1) I either have to point directly to the zip file to be published. This works fine.
2) I want to upload the playwright reporters directory, where I output all my reporters, because I have more than one reporter that I use. In this case I don't want to keep the uncompressed files when enabling the zip option.

The second scenario is what is happening to me. I'm using 2 reporters at the moment and I either create 2 pipeline artifacts, one for each reporter so that I can point specifically to the zipped file for monocart reporter OR I need to delete the uncompressed files myself and then upload the reporters directory.

I believe the option to choose the directory will also work fine. I'll test that and let you know.

**Comment by edumserrano** [comment]
I've tested version `2.9.3` using a path for the `zip` option and it works but there's a requirement which is not explicit for the user, which is that the name of the zip file must match the name of the output file. 

For instance, if the `outputFile` property specifies an html file named `index.html` then the path used in `zip` property must end with a file named `index.zip`.

I'm assuming that this is tied to the logic you are using to find the HTML and JSON files for the monocart report inside the zipped file? Meaning, you are looking for files inside the zip that match the name of the zip?

Here's the error I get if the filename in the `outputFile` property doesn't match the filename in the `zip` property:

> [MR] failed to read report data file: Z:\repos\azdo-lexis-nexis\Apps.Radix.Libraries\ngx-module-federation-tools\test-reporters\playwright\monocart-reporter\.cache\extracted-1\my.json

The above is using:

```ts
outputFile: path.resolve(monocartReporterOutputDir, "monocart-report.html"),
zip: path.resolve(monocartReporterOutputDir, "my.zip"),
```

Could this restriction be removed or would that be problematic? There should only be one JSON and HTML file at the root of the zip anyway right? So you could find them regardless of the name?

**Comment by cenfun** [comment]
sorry, i forgot test the `merge`, it should be fixed in `monocart-reporter@2.9.4`, please have a try.

**Comment by edumserrano** [comment]
I've tested version `2.9.4` and the issue with the custom zip filename is resolved 🎉

**Comment by edumserrano** [comment]
# Here is my last feedback on this feature

## Current usage

As it stands, my pipeline steps are:

- run playwright sharded test run
- delete all the files from the monocart reporter output dir that aren't a zip
- upload the test reporters dir to a pipeline artifact. The monocart reporter zip and other reporters are uploaded in this step.

Once all the sharded test runs execute:

- download the monocart reporter zip files from the pipeline artifacts
- make sure all the zip files are placed in the same directory. In my case that directory is `./test-reporters/shards/monocart-reporter`.
- run the monocart reporter CLI pointing to the directory where all the monocart reporter zip files have been placed. The merge CLI command looks something like: `npx monocart merge --import tsx ./test-reporters/shards/monocart-reporter/*.zip -c ./playwright.merge-monocart-reports.ts`

**The above is only possible because I'm creating unique names for each of the sharded test runs or else I'd have clashes with files having the same name being on the same directory.**

The way I'm creating unique names for my files is to append the shard of the test to the filename. So my zipped file names are: `monocart-report-1.zip`, `monocart-report-2.zip` and `monocart-report-3.zip`. 

## Quality of life improvement/desired usage

If the `zip` option wasn't a `boolean | string` type but was instead an object like:

```ts
type ZipOption = {
  outputFile: string, // this would be the filepath for the zip, it would behave the same as now when setting the zip property to a string value
  deleteUnzippedOutput: boolean, // this would delete uncompressed output files if enabled
}
```

It would allow the current usage of the `zip` option and extend it with an option to keep only the zipped output if desired. If the `zip` property is not defined then it's like if now it was set to false, if the `zip` option is set to the above object then it's like now when it's enabled and it should obey the zip options provided.

Furthermore, if the `ZipOption .outputFile` property is set then the user is responsible for choosing whatever filename he wants, including generating unique names if required. **However**, if the `ZipOption .outputFile` is NOT set, then it would be great if monocart reporter generated unique file names. You could just append the current shard to the filename that monocart uses by default, which I believe matches the filename of the JSON output file property.

In the end what I mean is that if I set my monocart reporter options like this:

```ts
const monocartOptions: MonocartReporterOptions = {
  name: "Playground app for @ln/ngx-module-federation-tools",
  outputFile: path.resolve(monocartReporterOutputDir, "monocart-report.html"),
  zip: { deleteUnzippedOutput: true },
  ...
}
```

**Then, after a sharded test run, the `monocartReporterOutputDir` would ONLY contain a zip file whose name would be `monocart-report-{the-shard-number}.zip` .**

@cenfun What do you think of this?

## How I'm currently getting the shard number to append to the filename

Currently, I'm setting the `zip` property to: 

```ts
const zip: string | boolean = isShardedTestRun
  ? path.resolve(monocartReporterOutputDir, `monocart-report-${currentShard}.zip`)
  : false;
```

Where the `isShardedTestRun` and `currentShard` values are obtained by inspecting the `process.argv` values. I'm using the [yargs](https://www.npmjs.com/package/yargs) package to parse it like this:

```ts
// this type defines the Playwright CLI options I'm interested in
export type PlaywrightCliOptions = {
  ui: boolean;
  uiPort: number | null;
  uiHost: string | null;
  currentShard: number | null;
  maxShard: number | null;
  grep: string | null;
};

// this parses the process.argv using the yargs package
const parsedArgv = yargs(process.argv.slice(2))
  .options({
    ui: { type: "boolean", default: false },
    uiPort: { type: "number", default: null },
    uiHost: { type: "string", default: null },
    shard: { type: "string", default: null },
    grep: { type: "string", default: null },
  })
  .parseSync();
  
// this creates the PlaywrightCliOptions object from the parsed process.argv values
const playwrightCliOptions: PlaywrightCliOptions = {
  ui: parsedArgv.ui,
  uiPort: parsedArgv.uiPort,
  uiHost: parsedArgv.uiHost,
  grep: parsedArgv.grep,
  currentShard: Number(parsedArgv.shard?.split("/")[0]),
  maxShard: Number(parsedArgv.shard?.split("/")[1]),
};

// in my code the isShardedTestRun variable is set to true as long as the PlaywrightCliOptions .currentShard is not null
```

I'm just sharing the above in case to show how I'm getting the shard value to append to the zip filename in case it helps. I'm sure that if you decide to implement this suggestion you can find your own way to do it.

## What do you think?

If you feel that there's no value in this last quality of life improvement for the `zip` option, then feel free to close this issue.

**Comment by edumserrano** [comment]
Here's the a repo that let's you easily reproduce the problem: [monocart reporter merge CLI bug when using the zip option on linux repro repo](https://github.com/edumserrano/monocart-reporter-merge-cli-zip-linux-bug).

The README should have all the information required about the bug and how to reproduce it. Let me know if you have any issues with it.

**Comment by cenfun** [comment]
> delete all the files from the monocart reporter output dir that aren't a zip

I don't think it's necessary to remove all those files, just ignore it if you use the separated dirs:
```js
const monocartOptions: MonocartReporterOptions = {
  name: "Playground app for @ln/ngx-module-federation-tools",
  outputFile: "./monocartReporterOutputDir/monocart-report.html",
  // different dir for zip artifact
  zip: "./monocartReporterOutputDir-zip/monocart-report.zip",
  ...
}
```

About liunx merge-cli issue, it seems that the `glob` doesn't work, let me figure out why. (I need setup the `docker` on my local PC)

**Comment by cenfun** [comment]
how about this approach
```js
const monocartOptions: MonocartReporterOptions = {
  name: "Playground app for @ln/ngx-module-federation-tools",
  outputFile: "./something-else-dir-do-not-output-to-test-reporters/monocart-report.html",
  // zip for upload as artifact
  zip: "./test-reporters/playwright/monocart-reporter/monocart-report.zip",
  ...
}

```

**Comment by edumserrano** [comment]
> how about this approach

That also doesn't work for me because when I run locally I want the reporter to be in the `test-reporters` dir. Locally I don't run in sharded mode so I just want the reporter to be unzipped and in the expected `test-reporters` dir.

Perhaps to better understand what I mean, for context here's how my monocart-reporter options looks like:

```ts
const monocartReporterOutputDir: string = path.resolve(reportersOutputDir, "monocart-reporter");
const zip: string | boolean = isShardedTestRun
  ? path.resolve(monocartReporterOutputDir, `monocart-report-${currentShard}.zip`)
  : false;
const monocartOptions: MonocartReporterOptions = {
  name: "Playground app for @ln/ngx-module-federation-tools",
  outputFile: path.resolve(monocartReporterOutputDir, "monocart-report.html"),
  zip: zip,
  ...
}
```

This configuration supports running tests in sharded mode and non-sharded mode. In my CI pipelines I run tests using shards but locally I don't. In my CI I only need the ZIP output, locally I only need the unzipped content.

Hope this clarifies my scenario.

**Comment by cenfun** [comment]
Actually, you can set `outputFile` dynamically just like `zip` with `isShardedTestRun`
```js
const outputFile:string = isShardedTestRun 
? path.resolve("path-to/a-ignored-dir", "monocart-report.html") 
: path.resolve(monocartReporterOutputDir, "monocart-report.html");
```
Anyway, I have added new `Object` options `clean` and `outputFile` for `zip`, please try `monocart-reporter@2.9.5` 
```js
{
    // zip: true,
    // zip: `docs/shard${current}-zip/my.zip`,

    zip: {
        // outputFile: `docs/shard${current}-zip/my.zip`,
        clean: true
    }
}
```

### the `merge-cli` issue on Linux
please put `*` in quotes (The * is a special character which is interpreted by some operating systems)
```sh
npx monocart merge './shards/**/*.zip'
```
see https://github.com/tj/commander.js/issues/1576 and https://github.com/tj/commander.js/issues/452

**Comment by edumserrano** [comment]
Regarding [this comment](https://github.com/cenfun/monocart-reporter/issues/147#issuecomment-2399690739):

1) You've updated the `zip` option to support the object type which is great, thank you.
2) I also ask if it would be possible for monocart-reporter to create unique names for the zip file when the user doesn't explicitly set the path for the zip file. So if I set the monocart-reporter options to:

```ts
const monocartOptions: MonocartReporterOptions = {
  name: "Playground app for @ln/ngx-module-federation-tools",
  outputFile: path.resolve(monocartReporterOutputDir, "monocart-report.html"),
  zip: { clean: true },
  ...
}
```

Then, after a sharded test run, the zip filename would be `monocart-report-{some-unique-identifier}.zip` , where:

- The first part of the filename `monocart-report` matches the filename used in the `outputFile` property which is `monocart-report.html`.
- The unique identifier could be anything, in my comment I suggested using the shard number so you'd get zip filenames like `monocart-report-1.zip`, `monocart-report-2.zip`, `monocart-report-3.zip`, etc

Any thoughts on this?

**Comment by edumserrano** [comment]
You are correct. This can already be done by the user. I was asking for it to be built-in into the monocart-reporter library as a default behavior. But that's fine. Perhaps in the future.

I'll close this issue as everything is working as expected. Awesome work @cenfun 🥇
