### ISSUE TITLE
[Feature Request] Add option to exclude idle time when calculating report duration 

### ISSUE THREAD

**Issue by edumserrano** [cenfun/monocart-reporter#148]
After #141 I was able to use the `MonocartReporterOptions.onData` function to implement a [custom calculation](https://github.com/cenfun/monocart-reporter/issues/141#issuecomment-2363493373) for the report duration which excludes idle time.

I would like to know if you would consider including this calculation in the monocart-reporter itself and make it available via an extra option in the `MonocartReporterOptions`. For instance:

```ts
const monocartOptions: MonocartReporterOptions = {
  name: "My report name",
  calculateDurationStrategy: "exclude-idle-time", // should default to "normal"
```

When `calculateDurationStrategy` is set to:

- `normal`: monocart-reporter would use the logic it currently uses to calculate the test run duration. It should also default to this value.
- `exclude-idle-time`: monocart-reporter would use the logic implemented in [this comment](https://github.com/cenfun/monocart-reporter/issues/141#issuecomment-2363493373) to calculate the test run duration.

This request is a quality of life improvement, there's nothing new that this allows you to do that you can't do already today. It just avoids having to repeat the logic to exclude idle time across all my Playwright projects or creating a small NPM package just for that.

**Comment by cenfun** [comment]
please try monocart-reporter@2.9.0 with new option `durationStrategy: 'exclude-idle'`

**Comment by edumserrano** [comment]
I've tested this and can confirm it's working as expected with version `2.9.2`. 👏 Thank you so much @cenfun 🥇
