### ISSUE TITLE
[Feature Request] Consolidate raw code coverage files

### ISSUE THREAD

**Issue by edumserrano** [cenfun/monocart-reporter#149]
Currently when doing a sharded test run with monocart-reporter where you want to collect code coverage you need to specify the `raw` report in coverage options.

What I have found is that in one of the shards I get almost 200MB of raw code coverage files generated. I have many tests and each will create their own raw code coverage file.

Is it possible, at the end of a test run, when using the `raw` report in coverage options, for monocart-reporter to somehow consolidate all the `raw` code coverage files into a single one?

My problem with the large payload of raw code coverage files is somewhat alleviated by compressing the output of monocart-reporter before I upload it to the pipeline but it still results in a file of about 30MB.

**Comment by cenfun** [comment]
I had thought about this issue before, but considering that the artifacts of shard are compressed by default, there is no need to compress it again.
For example in Github Actions, we using `actions/upload-artifact` and `actions/download-artifact` will zip all files into single one.
see https://github.com/actions/upload-artifact?tab=readme-ov-file#altering-compressions-level-speed-v-size

**Comment by edumserrano** [comment]
Yes, that compression is a default of the GitHub action, but note that other CI environments don't provide that by default. For isntance, in Azure Devops that doesn't happen, you need to compress manually before upload and extract after download if you want the same behavior.

However, the more important fact is that even compressed, in my example I get almost 30MB. The reason I get 30MB is because there are many raw code coverage files, one from each test. And there's of course lots of code coverage overlap in between these raw code coverage files so if they could somehow be consolidated at the end of the run it means that my compressed artifact would go down from 30MB to something much smaller, probably around 1MB or similar.

**Comment by cenfun** [comment]
move to https://github.com/cenfun/monocart-coverage-reports/issues/81
