### ISSUE TITLE
[Issue] Comments are not collected

### ISSUE THREAD

**Issue by i-novo** [cenfun/monocart-reporter#15]
Have the next code in config (the same as in documentation): 
```javascript
visitor: (data, metadata, collect) => {

			const parserOptions = {
				// https://babeljs.io/docs/babel-parser
				sourceType: "module"
			}
			const comments = collect.comments(parserOptions);
			if (comments) {
				Object.assign(data, comments);
			}
		},
		trend: 'playwright-report/grid/index.json',
		columns: (defaultColumns) => {

			// insert custom column(s) before a default column
			const durationColumnIndex = defaultColumns.findIndex((column) => column.id === 'duration');
			defaultColumns.splice(durationColumnIndex, 0, 
			{
				// define the column in reporter
				id: 'owner',
				name: 'Owner',
				align: 'center',
				searchable: true,
				styleMap: {
					'font-weight': 'normal'
				}
            },{
				// JIRA column
				id: 'jira',
				name: 'JIRA Key',
				width: 100,
				searchable: true,
				styleMap: 'font-weight:normal;',
				formatter: (valueFormatted, rowItem, columnItem) => {
					const key = rowItem[columnItem.id];
					return `<a href="https://fotoware.atlassian.net/browse/${key}" target="_blank">${valueFormatted}</a>`;
				}
			});
	 	},
``` 
And the next code in the test itself

```javascript
test.describe("test desc", () => {

    /** 
     * @jira xxx-11440
     * @owner I_N
     * @description bla-bal
     * */
    test("test"...
``` 

And as result I have nothing in the report. Is it something wrong in visitor or formatter? Thanks for help

**Comment by cenfun** [comment]
your codes looks  fine, I need reproduce it locally, can you create a demo repo for your issue?

**Comment by i-novo** [comment]
I have tried to create a new demo project and works fine with this config, BUT my main project is not working for some reason (configs are pretty much the same).
It's an error that I see in logs during debug. Versions are the same
<img width="562" alt="Снимок экрана 2023-04-08 в 16 07 38" src="https://user-images.githubusercontent.com/109597178/230725729-f61e0dde-7450-44d4-94ea-bb361fea674f.png">

**Comment by cenfun** [comment]
we use CommonJS by default, do you convert the codes copied from documentation to ESM?

**Comment by i-novo** [comment]
Yes, I have the config file in ESM format

**Comment by cenfun** [comment]
looks there are some JS syntax error in your code like "Missing initializer in const declaration Error in JS"
The "Missing initializer in const declaration" error occurs when a variable is declared using const, but its value is not initialized on the same line.
you have to fix those errors in red first.

**Comment by i-novo** [comment]
I have cleaned the project up via eslint (thanks for that) but still faced the same issue. I debugged and I see where the problem is (besides all ',' commas which were left by mistake but did not affect the code) with the typescript types declaring so the next declaring of functions is the root cause of the issue (everything in bold should be removed to have the report generated):

 export async function updateInternalArchive(archived **: number**, updatedArchivePayload **: InternalArchive** ) **:Promise \<InternalArchive\>** {}

next return is also will break the generating
return (await response.json()) **as InternalArchive**

**Comment by cenfun** [comment]
please try some parse options of babel https://babeljs.io/docs/babel-parser
```js
visitor: (data, metadata, collect) => {
    // auto collect data from comments
    const parserOptions = {
        // https://babeljs.io/docs/babel-parser
        // Indicate the mode the code should be parsed in. 
        // Can be one of "script", "module", or "unambiguous". Defaults to "script".
        sourceType: "module",
        
        plugins: ["typescript"]
        
    }
    const comments = collect.comments(parserOptions);
    if (comments) {
        Object.assign(data, comments);
    }
}
```
![image](https://user-images.githubusercontent.com/334577/230817452-117ac6ab-5a5c-4d13-87a6-10256d2e284c.png)

**Comment by i-novo** [comment]
awesome, it works! the ticket can be closed, thanks!
