### ISSUE TITLE
[Question] Is there a way to collapse all the steps by default

### ISSUE THREAD

**Issue by Jay-Sirju** [cenfun/monocart-reporter#152]
In my current implementation of Monocart, all steps are expanded by default.  How can I configure this so that they are all collapsed by default instead?

**Comment by cenfun** [comment]
![image](https://github.com/user-attachments/assets/8871e4a8-a017-4e76-af3a-852ab097c034)

Config
```js
// playwright.config.js
module.exports = {
    reporter: [
        ['list'],
        ['monocart-reporter', {  
            name: "My Test Report",
            outputFile: './monocart-report/index.html',
            groupOptions: {
                    group: true,
            
                    shard: true,
                    project: true,
                    file: true,
                    describe: true,
                    step: false,
            
                    merge: false
            }
        }]
    ]
};

```

**Comment by Jay-Sirju** [comment]
This doesn't seem to do anything (see attached screenshot).  I do see that there was a Collapse toggle introduced in 1.6.11 that seems to no longer be there.  

![image](https://github.com/user-attachments/assets/882f171a-e7b7-4f67-aeb6-b2b341bddf8a)

**Comment by cenfun** [comment]
You can click this triangle button to collapse all steps
![image](https://github.com/user-attachments/assets/f2136797-da88-452f-869d-2cc49f65f896)

**Comment by Jay-Sirju** [comment]
Sorry I should elaborate.

I want to be able to control which steps are collapsed by default.  I use `test.steps` pretty extensively, so I'd like to only display those and collapse everything else.  I see that I can get that data via visitor, but I haven't been able to figure out how to collapse items like fixtures, etc..

**Comment by cenfun** [comment]
Got it. you want to collapse the first-level steps?
It seems that #14 has been removed since v2+, I think we can add it back.

**Comment by Jay-Sirju** [comment]
Thank you.  I do apologize for the miscommunication

**Comment by cenfun** [comment]
please try monocart-reporter@2.9.1
![image](https://github.com/user-attachments/assets/8f101f2f-8f91-42f6-a956-91d01a01111f)

**Comment by Jay-Sirju** [comment]
Thank you @cenfun
