### ISSUE TITLE
[Help] Duplicate file on coverage reporter html

### ISSUE THREAD

**Issue by phatpna** [cenfun/monocart-reporter#154]
Clear and concise description of the issue
How to make the report contain only the original file and not the fake rendered file?
This is my code to run test

` test.beforeEach(async ({ page }) => {
  await mockApi(page)
  await Promise.all([
    page.coverage.startJSCoverage({ resetOnNavigation: false }),
    page.coverage.startCSSCoverage({ resetOnNavigation: false })
  ]);  
  await page.goto('http://localhost:8080');
  await page.waitForTimeout(5000);
});

test.afterEach(async ({ page }) => {
  const [jsCoverage, cssCoverage] = await Promise.all([
    page.coverage.stopJSCoverage(),
    page.coverage.stopCSSCoverage()
  ]);

  const coverageData = [...jsCoverage, ...cssCoverage];

  await addCoverageReport(coverageData, test.info());

});

test(' Test default showing on page ', async ({ page, mount }) => {

  await page.goto('http://localhost:8080');
  await page.waitForTimeout(5000);
  await page.getByRole('link', { name: 'Absence List' }).click();
  } `
  
  My playwright.config.ts file:
  
![image](https://github.com/user-attachments/assets/14b3d7a5-a2c0-4089-9eaf-aa793e73e5b0)

Example look like that:
![image](https://github.com/user-attachments/assets/8f885c6e-8b20-48fe-b931-3b275f39b5ba)
![image](https://github.com/user-attachments/assets/608e01c3-00e0-40a6-9134-9d8510d3e0a8)

does anyone know why there are 2 files like that, and is there a way I can get just the original file

Thanks in advance

**Comment by cenfun** [comment]
It seems  that it enabled `hot` reload?  try disable it.

**Comment by cenfun** [comment]
Could you please provide a minimal reproducible repo? So I can reproduce and debug the issue locally?

**Comment by phatpna** [comment]
> Could you please provide a minimal reproducible repo? So I can reproduce and debug the issue locally?

I'm so sorry, because this a private repo, i use playwright in the same container with Web, i think maybe you are right. I still can't solve this, but i will try more ways about hot reload. Could you please give me some advices might cause the issue i got ? Thank you in advanced

**Comment by cenfun** [comment]
My suggestion is that don't use `develop mode` which is enabled `hot` reload, but try `preview mode` or `production mode` instead.

❌ npm run dev
✅ npm run build + npm run preview

Or you can try vue component testing, see example:
https://github.com/cenfun/playwright-ct-vue

**Comment by phatpna** [comment]
> My suggestion is that don't use `develop mode` which is enabled `hot` reload, but try `preview mode` or `production mode` instead.
> 
> ❌ npm run dev ✅ npm run build + npm run preview
> 
> No matter which mode, please enable `sourcemap` and `no minify` for the source.
> 
> Or you can try vue component testing, see example: https://github.com/cenfun/playwright-ct-vue

I solved it by change Vue-CLI -> Vite, but i can't guess clearly the reason made it working. By the way, thank you so much
