### ISSUE TITLE
[Bug] Exit status code not set to an error status when the merge CLI fails to find the provided files

### ISSUE THREAD

**Issue by edumserrano** [cenfun/monocart-reporter#155]
**Describe the bug**
The merge CLI returns a zero (OK) status code when it fails due to not being able to find the provided files to merge.

**To Reproduce**
- Version: `2.9.5`
- Node Version:  `v22.9.0`
- Have you tried the latest version (including node), and does the issue still exist? yes
- Steps to reproduce the actual behavior:

1) Run the merge CLI and provide a glob that doesn't return any files. For instance: `npx monocart merge './i-dont-exist/*.zip'`.
2) Note that you get a zero (OK) exit status code even though you get an error message from MR: `[MR] ERROR: no files found with glob: ./i-dont-exist/*.zip`.

**Expected behavior**
A non-zero (not OK) exit status code should be returned by the merge CLI.

**Additional context**

The reason I'm asking for this is because at one point I made a mistake on my glob but my CI pipeline still completed successfully but it should have failed because no files were found to merge. To make the pipeline fail, the merge CLI should return a non-zero exit status code if it fails to merge.

**Comment by cenfun** [comment]
please try monocart-reporter@2.9.6

**Comment by edumserrano** [comment]
I've tested version `2.9.6` and I can confirm this is fixed. Thank you!
