### ISSUE TITLE
[Question] cli.js file is saved with windows line breaks

### ISSUE THREAD

**Issue by aldoreyes** [cenfun/monocart-reporter#156]
Hello, me again :)

Not sure if this has been reported or if you are aware but the file [cli.js](https://github.com/cenfun/monocart-reporter/blob/main/lib/cli.js) is saved with windows line breaks which when executed on unix based hosts it's throwing an error like this `env: node\r: No such file or directory`
(command executed `monocart merge monocart-report/index.json -c mr.config.js`)

Which is similar to this https://github.com/yarnpkg/yarn/issues/8106

After I run this command
`dos2unix node_modules/monocart-reporter/lib/cli.js`

Things start to work again, I can do this on my local machine without a problem but having to do this on pipelines or on every other dev env might be problematic.

**Comment by cenfun** [comment]
Could you please try monocart-reporter@2.9.7?

**Comment by aldoreyes** [comment]
Thanks that fixed it. Loved how you keep up the project.
