### ISSUE TITLE
[Bug] Expect error message is visible despite of test passed

### ISSUE THREAD

**Issue by Aroot42** [cenfun/monocart-reporter#158]
**Describe the bug**
The error message when building Expect is always displayed in the report, regardless of whether the test was successful or failed with an error

**To Reproduce**
```
import { expect, test } from '@playwright/test';

test('test', async ({ page }) => {
    await page.goto('https://www.bing.com/');
    await page.waitForTimeout(5000);

    expect(await page.locator('#bLogo').getAttribute('aria-label'), 'Incorrect aria-label').toEqual(
        'Welcome to Bing Search'
    );
});
```

**Expected behavior**
Expect error message 'Incorrect aria-label' is not displayed in the report is test passed.

**Errors or Screenshots**
Expect error message is visible despite of test passed
![image](https://github.com/user-attachments/assets/41d04bb8-9e74-4665-a371-3096b4fcad2e)

**Comment by cenfun** [comment]
This is a step which is provided by Playwright Test Result API (https://playwright.dev/docs/api/class-testresult#test-result-steps)
Technically, custom reporter won't handle this, such as filtering some steps.
But you can ask for help from the official [Playwright community](https://github.com/microsoft/playwright/issues) to see if these steps can be filtered out from the test results.

**Comment by Aroot42** [comment]
Thanks.
I'll create point for PW team.
