### ISSUE TITLE
[Question] Is there a way to set the name of the report after the test completes?

### ISSUE THREAD

**Issue by craitose** [cenfun/monocart-reporter#159]
hi again Cenfun,

I have a frame work that has multiple test types [regression,sanity,smoke] I want the name of the report to be prefixed with by one of the test types after the test completes i.e "regression report" , "sanity report" .
However, because the report name is set in the config. The config is called before the test completes . If I used an env variable to set the report name after the test completes then that will only be set for the next test and not the test that just completed.

reporter: 
[list],
['monocart-reporter', {
    name: process.env.TEST_TYPE + "report",
]

Any ideas

**Comment by cenfun** [comment]
Using env variables should work if you set `TEST_TYPE` before test start.
> set env TEST_TYPE -> start test -> load config -> test complete -> generate report -> set next env TEST_TYPE -> start next test ...

Also, you can try `onData` hook
```js
onData: (reportData) => {
    // console.log('onData', reportData);
    reportData.name = process.env.TEST_TYPE + "report";
}
```
The `onData` function will be executed after report data generated (before `onEnd`).

**Comment by craitose** [comment]
Thanks Cenfun, the onData hook looks ideal but where should I call it in config file and should I leave the name as blank in :

reporter:
[list],
['monocart-reporter', {
name: ?
]

**Comment by craitose** [comment]
it doesn't seem to be working, I also have visitor: state: that is called before onEnd: , maybe I should onData: to top? Does this work in a specific version?

**Comment by cenfun** [comment]
yes, please try latest version.

**Comment by craitose** [comment]
Thanks Cenfun, this worked but I have add a line to get  it to work properly:

// playwright.config.js
module.exports = {
    reporter: [
        ['monocart-reporter', {  
            name: "whatever or empty",
            outputFile: './monocart-report/index.html',
           
            onData: (reportData) => {
               dotenv.config({override:true});
               reportData.name = process.env.TEST_TYPE + "report";
            }
        }]
    ]
};
