### ISSUE TITLE
[Question] Unexpected token error when exporting to TestRail

### ISSUE THREAD

**Issue by clundstedt-m** [cenfun/monocart-reporter#16]
Hey cenfun!, me again (sorry 🥲 )

I'm currently implementing the testrail integration across all my tests, but every time a test case fails OR is missing a step id idenfitication I'm getting error messages like this:

```
1 failed
    [chromium] › tests/assets/creating-assets.spec.ts:93:8 › Static Assets creation › Creating Static Asset - Other 
[MCR] generating report data ...
Unexpected token (5:13)
Unable to parse file for comments: /Users/clundstedt/Documents/zf-playwright/src/e2e/pages-objects/login.page.ts
Try use different options: https://babeljs.io/docs/babel-parser
Unexpected token (5:13)
Unable to parse file for comments: /Users/clundstedt/Documents/zf-playwright/src/e2e/pages-objects/menu-top-nav.component.ts
Try use different options: https://babeljs.io/docs/babel-parser
Unexpected token (5:13)
Unable to parse file for comments: /Users/clundstedt/Documents/zf-playwright/src/e2e/pages-objects/assets.page.ts
Try use different options: https://babeljs.io/docs/babel-parser
[MCR] generating test report ...
```
Although is not "super" critical as the scripts are running effectively, this can be misleading when integrating it on my CI/CD pipe, so I was wondering if this is something that could be related to some kind of config that I'm using.

Considerations:
- I'm not strictly using babel at any point since it's not needed so far, should I absolutely need to install it and configure it (somehow?).

Thanks for your input and sorry for pestering you again

**Comment by cenfun** [comment]
try this https://github.com/cenfun/monocart-reporter/issues/15#issuecomment-1501334055

**Comment by clundstedt-m** [comment]
That did it!
Thanks a lot again
