### ISSUE TITLE
[Feature] Add trace viewer as in html reporter

### ISSUE THREAD

**Issue by fresherr** [cenfun/monocart-reporter#17]
It would be great to be able to view traces without downloading them

**Comment by cenfun** [comment]
please try following:
1, upgrade to monocart-reporter@1.6.13
2, show report with CLI `npx monocart show-report <your-outputFile-path>`
You may able to `View trace online` without downloading the trace file.

After doing some research found that the Trace Viewer requires that the trace file must be loaded over the http:// or https:// protocols (current protocol is https:) without [CORS](https://developer.mozilla.org/en-US/docs/Glossary/CORS) issue, so we need to start a local web server, playwright official also uses the same way viewing HTML report (`npx playwright show-report`).
