### ISSUE TITLE
[Improve] Should not count error within try catch

### ISSUE THREAD

**Issue by minhpham1990** [cenfun/monocart-reporter#18]
I got this error within  try catch , but i think should not count it as error in report 
![image](https://user-images.githubusercontent.com/61374153/232663540-b1c66fd7-53ae-4adf-a28f-3f8cca2032ce.png)

**Comment by cenfun** [comment]
the step error is collected from TestStep "error" property and it decides whether to count as an error, see here:
https://playwright.dev/docs/api/class-teststep#test-step-error 

so for the reporter, the counting logic is simply and seems no way to do special count.
try to find more related answers here
https://github.com/microsoft/playwright/issues
or share some codes or demo repo to let me debug and reproduce the issue locally.
