### ISSUE TITLE
Report file name cannot be specified

### ISSUE THREAD

**Issue by oytunerdd** [cenfun/monocart-reporter#2]
Given for the examples on both playwright.dev and monocart-reporter github page input file name cannot be interfered, it creates index.html file for result like playwright's own html reporter

outputFile: 'playwright-report/grid/indexTest1.html'

**Comment by cenfun** [comment]
weird, any errors got?

It is expected to be able to customize the output name, see:
https://github.com/cenfun/monocart-reporter/blob/main/lib/generate.js#L58

or any repo/codes I can review to find out the root cause?

**Comment by oytunerdd** [comment]
I don't get errors nor any changed results to catch that I created different folders as follows

const config: PlaywrightTestConfig<TestOptions> = {
  reporter: [ ['html', { outputFolder: './playwright-report/2',outputFile:'results.html', open: 'never' }], ["dot"], ["json", { outputFile: "alure-test-results.json" }],
  ['experimental-allure-playwright'],['junit', { outputFile: 'results.xml' , outputFolder:"./playwright-report/grid"}],['monocart-reporter', {  
    outputFile: 'playwright-reportA/grid/indexOther.html'
  }] ],

**Comment by cenfun** [comment]
![image](https://user-images.githubusercontent.com/334577/190620062-a1e75dbb-e8d6-4b09-9aa1-7ac6832a1235.png)
I just test it with your config and seems it works well.

**Comment by oytunerdd** [comment]
I tried it in playwright.config.ts as it was stated in your Readme
However it doesn't create differently 
![image](https://user-images.githubusercontent.com/48505927/190623830-4685e8ee-e7cc-4d3a-838b-4055a2a6e806.png)

**Comment by cenfun** [comment]
yes it is default outputFile:
https://github.com/cenfun/monocart-reporter/blob/main/lib/generate.js#L9
So it may be that the custom configuration is not obtained correctly
do you have any chance to debug here: node_modules/monocart-reporter/lib/generate.js
https://github.com/cenfun/monocart-reporter/blob/main/lib/generate.js#L14-L31

**Comment by oytunerdd** [comment]
![image](https://user-images.githubusercontent.com/48505927/190628300-706390b9-ad70-4871-83c5-c63f7943e7d7.png)
It returns I guess the default file name on each time,

where do you give config value to the generate consts

**Comment by cenfun** [comment]
anyway I released a new version 1.0.3 with minor fixing for options, could you please install monocart-reporter@1.0.3 and try again?

**Comment by oytunerdd** [comment]
Hello, thanks for the update, I did try it but resulted the same way, I wonder why since I do not have custom playwright configurations, and also double checked the implementation. Do you reckon why it could be like this ?

**Comment by cenfun** [comment]
Technically, each reporter can customize the output path like following
https://github.com/cenfun/monocart-reporter/blob/main/tests/playwright.config.js
some of my guesses:
- there are multiples playwright configurations and wrong one choose?
- any cache? or node process not killed after running test?
- check Node.js version?
I don't know but hope it help you

**Comment by oytunerdd** [comment]
Can you share a little capture on your playwright.config.ts file since you are overwriting you my.config.ts values in there

**Comment by cenfun** [comment]
try checkout this repo https://github.com/cenfun/monocart-reporter-test
please run npm install first
test both configs are works well:
npx playwright test --config=tests/my.config.js    
npx playwright test --config=tests/playwright.config.js
