### ISSUE TITLE
How do we use the xray integration without the jira transition ?

### ISSUE THREAD

**Issue by jensencp7** [cenfun/monocart-reporter#20]
Hello ! 

Ive configured my xray secret/client id but i see the jira client is also required...

Could you please provide a way to decouple this ? I just want to execute tests and the results need to be uploaded to jira/xray

Thanks Alot

**Comment by cenfun** [comment]
https://github.com/cenfun/monocart-reporter/blob/main/tests/common/xray.js#L105-L109
did you checked the example?
you can remove the codes of Jira related.

**Comment by jensencp7** [comment]
thanks cen , please can you help me debug why im getting the following [xray] no test results for xray

`playwright.config.js

process.env.XRAY_CLIENT_ID ="123123";
process.env.XRAY_CLIENT_SECRET="123123" ;


  reporter: [['list'],['junit', { outputFile: 'playwright-report/results.xml'}],['monocart-reporter', {  
    name: "My Test Report",
    outputFile: 'playwright-report/report.html',
    // async hook after report data generated
    onEnd: async (reportData, capability) => {
 
        // jira + xray integration
         const xray = require('./common/xray.js');
         await xray(reportData, capability);

    }
}] ],`


`common/xray.js
const axios = require('axios');
const EC = require('eight-colors');
//const JiraClient = require('jira-client');

module.exports = async (reportData, capability) => {

    // https://docs.getxray.app/display/XRAYCLOUD/REST+API
    const xray_host = 'https://xray.cloud.getxray.app/api/v2/';
    const XRAY_CLIENT_ID = process.env.XRAY_CLIENT_ID;
    const XRAY_CLIENT_SECRET = process.env.XRAY_CLIENT_SECRET;
    const project = 'SPR';

    const xrayClient = await createXrayClient(xray_host, XRAY_CLIENT_ID, XRAY_CLIENT_SECRET);
    if (!xrayClient) {
        // failed to get xray token
        return;
    }

    // https://github.com/jira-node/node-jira-client
    // const JIRA_TOKEN = process.env.JIRA_TOKEN;
    // const jiraClient = new JiraClient({
    //     protocol: 'https',
    //     host: 'cenfun.atlassian.net',
    //     username: 'cenfun@gmail.com',
    //     password: JIRA_TOKEN
    // });

    // Step 1. Collect case keys
    EC.logCyan('[xray] collect test results ...');

    const {
        name, date, dateH, duration, durationH
    } = reportData;

    const summary = `${name} ${dateH} (${durationH})`;

    // Xray JSON format
    // https://docs.getxray.app/display/XRAYCLOUD/Using+Xray+JSON+format+to+import+execution+results
    const xrayResults = {
        info: {
            project,
            summary,
            startDate: new Date(date).toISOString(),
            finishDate: new Date(date + duration).toISOString()
        },
        tests: []
    };

    // 1. add xray key to comments
    /**
     * @xray MON-1
     */
    // test('Test case', async () => { });
    // 2. make sure the comments to be collected with visitor

    capability.forEach((item) => {
        if (item.type === 'case' && item.xray) {

            // [Xray] How to create another Test Status
            // https://docs.getxray.app/display/ProductKB/%5BXray%5D+How+to+create+another+Test+Status
            // the xray test run status are PASSED, FAILED, EXECUTING, TODO by default
            // please add FLAKY and SKIPPED to mapping playwright status
            const statusMap = {
                passed: 'PASSED',
                flaky: 'FLAKY',
                skipped: 'SKIPPED',
                failed: 'FAILED'
            };

            const status = statusMap[item.caseType];

            xrayResults.tests.push({
                testKey: item.xray,
                status
            });
        }
    });

    if (!xrayResults.tests.length) {
        EC.logRed('[xray] no test results for xray');
        return;
    }
    console.log(`[xray] got test results: ${xrayResults.tests.length}`);

    // Step 2. Import Execution Results
    // https://docs.getxray.app/display/XRAYCLOUD/Import+Execution+Results+-+REST+v2
    const resExecution = await xrayClient.request('post', 'import/execution', xrayResults);
    if (!resExecution) {
        return;
    }

    const executionKey = resExecution.key;
    console.log(`[xray] test execution created: ${executionKey}`);

    // Step 3. Update Jira Issue Status to Done

    // you can find out which transition id is Done
    // const res = await jiraClient.listTransitions('MON-6');
    // console.log(res);

    // id: '11', name: 'Backlog',
    // id: '31', name: 'In Progress',
    // id: '41', name: 'Done',

    // await jiraClient.transitionIssue(executionKey, {
    //     transition: {
    //         id: '41'
    //     }
    // });

    EC.logGreen('[xray] done');

};

const createXrayClient = async (host, client_id, client_secret) => {

    // request xray token
    EC.logCyan('[xray] request xray token ...');
    let errToken;
    const resToken = await axios({
        method: 'post',
        url: `${host}authenticate`,
        data: {
            client_id,
            client_secret
        }
    }).catch(function(e) {
        errToken = e;
    });

    if (errToken) {
        EC.logRed(EC.red('ERROR: Catch a error on endpoint: authenticate'));
        EC.logRed(errToken.message);
        console.log(errToken.response && errToken.response.data);
        return;
    }

    const token = resToken.data;

    return {
        request: async function(method, endpoint, data, args = {}) {
            let err;
            const res = await axios({
                ... args,
                method,
                url: host + endpoint,
                data,
                headers: {
                    Authorization: `Bearer ${token}`
                }
            }).catch(function(e) {
                err = e;
            });
            if (err) {
                //  console.log(err);
                EC.logRed(EC.red(`ERROR: Catch a error on endpoint: ${endpoint}`));
                EC.logRed(err.message);
                console.log(err.response && err.response.data);
                return;
            }
            return res.data;
        }
    };
};

`
`
tests/bounty-dashboard/demo.spec.js

const { test, expect } = require('@playwright/test');
const common = require('../../functions/common');
const db = require("../../functions/dbConnect");
const fs = require('fs');


//ENV=dev npx playwright test tests/bounty-dashboard/demo.spec.js 

/**
 * @xray SPR-67
 */

test('simple numerical test', async () => {

    var num1 = 23;
    var num2 = 2;

    var sum = num1 + num2;

    expect(sum).toBe(25);

});
`

`✗ ENV=dev npx playwright test tests/bounty-dashboard/demo.spec.js                              

Running 1 test using 1 worker

  ✓  1 bounty-dashboard/demo.spec.js:18:1 › simple numerical test (5ms)

  1 passed (210ms)
[MCR] generating report data ...
[MCR] generating test report ...
[MCR] test results: My Test Report
┌───────────────┬──────────────────────┐
│ ├ Tests       │ 1                    │
│ │ ├ Passed    │ 1 (100.0%)           │
│ │ ├ Flaky     │ 0 (0.0%)             │
│ │ ├ Skipped   │ 0 (0.0%)             │
│ │ └ Failed    │ 0 (0.0%)             │
│ ├ Steps       │ 3                    │
│ ├ Suites      │ 1                    │
│ │ ├ Projects  │ 1                    │
│ │ ├ Files     │ 1                    │
│ │ ├ Describes │ 0                    │
│ │ └ Shards    │ 0                    │
│ ├ Retries     │ 0                    │
│ ├ Errors      │ 0                    │
│ ├ Logs        │ 0                    │
│ ├ Attachments │ 0                    │
│ ├ Playwright  │ v1.32.0              │
│ ├ Date        │ 28/04/2023, 15:21:44 │
│ └ Duration    │ 1.3s                 │
└───────────────┴──────────────────────┘
[MCR] json report: playwright-report/report.json
[MCR] html report: playwright-report/report.html
[MCR] view report: npx monocart show-report playwright-report/report.html
[xray] request xray token ...
[xray] collect test results ...
[xray] no test results for xray

 `

any idea what im doing wrong here ?

**Comment by cenfun** [comment]
`[xray] no test results for xray`
the comments collection does not works well. 
please add following options to reporter config, it seems no comments visitor in your codes
```js
// playwright.config.js
module.exports = {
    reporter: [
        ['monocart-reporter', {  
            name: "My Test Report",
            outputFile: './test-results/report.html',
            // additional custom visitor for columns
            visitor: (data, metadata, collect) => {
                // auto collect data from comments
                const parserOptions = {
                    // Indicate the mode the code should be parsed in.
                    // Can be one of "script", "module", or "unambiguous". Defaults to "script".
                    // sourceType: 'module',

                    // enable typescript syntax. more https://babeljs.io/docs/babel-parser
                    // plugins: ['typescript']
                };
                const comments = collect.comments(parserOptions);
                if (comments) {
                    Object.assign(data, comments);
                }
            }
        }]
    ]
};
```

**Comment by jensencp7** [comment]
Hi Cen, thanks alot your solution worked. 

Ive noticed that the comments dont always work. For example if i comment above test.describe.serial, it doesnt get picked up.. the below doesnt work for me.. 

/**
 * add extra information for case
 * @xray MON-1
 */

test.describe.serial("A Simple Test: Happy Flow", () => {



[MCR] generating report data ...
[MCR] generating test report ...
[MCR] test results: My Test Report
┌───────────────┬──────────────────────┐
│ ├ Tests       │ 8                    │
│ │ ├ Passed    │ 0 (0.0%)             │
│ │ ├ Flaky     │ 0 (0.0%)             │
│ │ ├ Skipped   │ 7 (87.5%)            │
│ │ └ Failed    │ 1 (12.5%)            │
│ ├ Steps       │ 11                   │
│ ├ Suites      │ 1                    │
│ │ ├ Projects  │ 1                    │
│ │ ├ Files     │ 1                    │
│ │ ├ Describes │ 1                    │
│ │ └ Shards    │ 0                    │
│ ├ Retries     │ 0                    │
│ ├ Errors      │ 1                    │
│ ├ Logs        │ 2                    │
│ ├ Attachments │ 0                    │
│ ├ Playwright  │ v1.32.0              │
│ ├ Date        │ 29/04/2023, 23:04:47 │
│ └ Duration    │ 3.6s                 │
└───────────────┴──────────────────────┘
[MCR] json report: playwright-report/report.json
[MCR] html report: playwright-report/report.html
[MCR] view report: npx monocart show-report playwright-report/report.html
[xray] request xray token ...
[xray] collect test results ...

**Comment by cenfun** [comment]
Weird, your code works
![image](https://user-images.githubusercontent.com/334577/235331373-d26347fe-6787-4f8c-86a6-f881d40b4ee7.png)
```js
/**
 * add extra information for case
 * @xray MON-1
 */

test.describe.serial('A Simple Test: Happy Flow', () => {
    test('test title', () => {

    });
});
```
Anyway there are a few ways to try
1, did you got any error in console logs? (red line)
2, try following options in `visitor` if you are using typescript
```js
visitor: (data, metadata, collect) => {
              // auto collect data from comments
              const parserOptions = {
                  // Indicate the mode the code should be parsed in.
                  // Can be one of "script", "module", or "unambiguous". Defaults to "script".
                  sourceType: 'module',

                  // enable typescript syntax. more https://babeljs.io/docs/babel-parser
                  plugins: ['typescript']
              };
              const comments = collect.comments(parserOptions);
              if (comments) {
                  Object.assign(data, comments);
              }
          }
```
3, test.describe.serial seems was [DISCOURAGED](https://playwright.dev/docs/api/class-test#test-describe-serial) can you try [test.describe.configure()](https://playwright.dev/docs/api/class-test#test-describe-configure)
let me know if you have more questions

**Comment by jensencp7** [comment]
hey cen , thanks .. i didnt know .serial was deprecated .. 

the below example does not work ...


//this doesnt work

const { test, expect } = require('@playwright/test');
const common = require('../../functions/common');
const db = require("../../functions/dbConnect");
const fs = require('fs');


//ENV=dev npx playwright test tests/bounty-dashboard/demo.spec.js 

/**
* add extra information for case
* @xray MON-1
*/


test.describe.configure({ mode: 'serial' });

test.describe('group of two tests', () => {

test('simple numerical test 1', async () => {

    var num1 = 23;
    var num2 = 2;

    var sum = num1 + num2;

    expect(sum).toBe(25);

    console.log(sum)

});

test('simple numerical test 2', async () => {

    var num1 = 23;
    var num2 = 2;

    var sum = num1 + num2;

    expect(sum).toBe(25);
    const delay = ms => new Promise(resolve => setTimeout(resolve, ms))
    await delay(5000); // <-- here we wait 5s
    console.log(sum)

});

test('simple numerical test 3', async () => {

    var num1 = 23;
    var num2 = 2;

    var sum = num1 + num2;

    expect(sum).toBe(25);

    console.log(sum)

});

});



it only works if i put the comment above the test , is there a safer way to add a comment to the test file ? 

maybe in the test title ? test('[MON-1] simple numerical test 1', async () => {   

or using test.annotations ? like this 
 //Adding Xray properties
        testInfo.annotations.push({ type: 'test_key', description: 'XT-92' });
        testInfo.annotations.push({ type: 'test_summary', description: 'Successful login.' });
        testInfo.annotations.push({ type: 'requirements', description: 'XT-41' });
        testInfo.annotations.push({ type: 'test_description', description: 'Validate that the login is successful.' });

https://github.com/Xray-App/tutorial-js-playwright/blob/main/login.spec.js




//this works

/**
* add extra information for case
* @xray MON-1
*/
test('simple numerical test 1', async () => {

**Comment by cenfun** [comment]
`it only works if i put the comment above the test` you are right
1, the comments collection is similar to [JSDoc](https://jsdoc.app/about-getting-started.html), It must be placed in the correct position as required.

2, maybe in the test title? the answer is yes, but you need to parse the xray id yourself from the title
```js
capability.forEach((item) => {
        if (item.type === 'case') {
            const statusMap = {
                passed: 'PASSED',
                flaky: 'FLAKY',
                skipped: 'SKIPPED',
                failed: 'FAILED'
            };
            const status = statusMap[item.caseType];
            xrayResults.tests.push({
                testKey: getXrayIdFromTitle(item.title),
                status
            });
        }
    });
```
3, the annotations also works, and it's easier to get the xray id than from the title
```js
testInfo.annotations.push({ type: 'test_key', description: 'XT-92' });
```
```js
capability.forEach((item) => {
        if (item.type === 'case') {
            const statusMap = {
                passed: 'PASSED',
                flaky: 'FLAKY',
                skipped: 'SKIPPED',
                failed: 'FAILED'
            };
            const status = statusMap[item.caseType];
            xrayResults.tests.push({
                testKey: item.annotations.find((it) => it.type === 'text-key').description,
                status
            });
        }
    });
```
The comments should be easiest in my opinion.

**Comment by jensencp7** [comment]
thanks alot , appreciate all the help
