### ISSUE TITLE
Lots of "route.continue" generated in the Monocart report 

### ISSUE THREAD

**Issue by alex-vungle** [cenfun/monocart-reporter#22]
** Test Environment: **
- Playwright version: 1.33.0
- monocart-reporter version: 1.6.16

**How to reproduce:**

In my test framework, we have a route handler that is used to block 3rd-party plugins in order to accelerate page loading speed:
```
  page.route('**', route => {
    const url = route.request().url();
    // console.log('request url: ', request.url());
 const blackList = [
    "sentry.io",
    "segment.io",
    "segment.com",
    "fullstory.com",
    "hs-analytics.net",
    "hs-banner.com",
    "zdassets.com",
    "zendesk.com"
  ];

  if (blackList.some((kw) => url.includes(kw))) {
    return route.abort();
  }
    return route.continue();
  });
```
Current issue is the monocart report has many route.continue() generated in the steps, pls refer to below screenshot, it leads the report hard to read.

![image](https://user-images.githubusercontent.com/42924996/235859097-caa73c03-1156-41bd-94cb-0b80b27a0105.png)

Is it possible to refer to playwright HTML report solution to group those continuous **route.continue()** together?

![image](https://user-images.githubusercontent.com/42924996/235859719-d05dd9ab-48ea-4397-a5e9-2568a3ecffca.png)

**Comment by cenfun** [comment]
Is it a bug or? is it possible to reproduce it?

**Comment by alex-vungle** [comment]
Hi @cenfun thanks for your quick response, I am still editing this issue, will let you know soon.

**Comment by cenfun** [comment]
(:  看到你的linkedin了，可以直接用中文交流？

**Comment by alex-vungle** [comment]
Hi @cenfun 我们可以用中文交流。我刚刚在Playwright的Repo下搜索了相关的Issue，目前看Allure reporting也有类似的问题，所以可能需要您来尝试解决这个问题。

#https://github.com/microsoft/playwright/issues/10098

**Comment by cenfun** [comment]
嗯，既然官方的html report实现了这个功能，那应该也一样可以实现，等我弄好了再告诉你，应该不难

**Comment by alex-vungle** [comment]
Nice job, thank you!
