### ISSUE TITLE
Collapse continuous "route.continue()" message

### ISSUE THREAD

**Issue by alex-vungle** [cenfun/monocart-reporter#23]
Hi @cenfun ,

This is a follow-up ticket to #22 

Just noticed that there're still many `route.continue()` message when I expand the test case to review the test steps. Is it possible to collapse those messages like the test case detail page?

Thanks,
Alex

![image](https://user-images.githubusercontent.com/42924996/236710777-4d4ba334-4aec-4d45-add1-a717d5b951e5.png)

**Comment by cenfun** [comment]
sure, will be fixed

**Comment by cenfun** [comment]
fixed in monocart-reporter@1.6.20 please try it

**Comment by alex-vungle** [comment]
![image](https://github.com/cenfun/monocart-reporter/assets/42924996/96e41f4c-7ccc-4e00-bf82-5337ec5663c6)
