### ISSUE TITLE
Worker 0 sometimes shows in timeline graph

### ISSUE THREAD

**Issue by alex-vungle** [cenfun/monocart-reporter#24]
This issue is not always reproducible, I specify 10 workers for parallel execution, but sometimes, I saw a worker process named **Worker 0** shows in the execution timeline graph.

`npx playwright test --workers 10 --trace on`

![image](https://github.com/cenfun/monocart-reporter/assets/42924996/d24e2809-f8e7-4c9e-89bc-a7b6690e5fd3)

![image](https://github.com/cenfun/monocart-reporter/assets/42924996/fea1234b-7268-4d85-a08e-a07cc31b22a5)

**Comment by cenfun** [comment]
`Worker 0`  means that there is a case whose parallelIndex=-1
[parallelIndex](https://playwright.dev/docs/api/class-testresult#test-result-parallel-index)  is supposed to be between `0` and `workers - 1` but not `-1`, I cann't find any description about parallelIndex=-1
so it‘s not a normal situation but it should not be the reporter's issue.

Actually, I found this problem long time ago, see report [parallel-unknown](https://cenfun.github.io/monocart-reporter-test/parallel-unknown/#page=report), and [example](https://github.com/cenfun/monocart-reporter-test/blob/main/tests/parallel-unknown/example.spec.js) how to reproduce used Math.random() somewhere (should be unreasonable), so please check your tests codes if any unusual formats used.

Anyway the reporter helped us find the problem, or go [playwright/issues](https://github.com/microsoft/playwright/issues) for answers

**Comment by alex-vungle** [comment]
Thanks for your explanation
