### ISSUE TITLE
[Question] trace viewer question

### ISSUE THREAD

**Issue by Aroot42** [cenfun/monocart-reporter#27]
Hey!
I have question about trace viewer [(https://github.com/cenfun/monocart-reporter/issues/26)](https://github.com/cenfun/monocart-reporter/issues/26).

System info:
Playwright: 1.34.2
Monocart: 1.6.27
Config: 
![image](https://github.com/cenfun/monocart-reporter/assets/100360547/9f372c4b-2af6-4490-937f-13372c24d3cf)

When I run my test and it fails, I attempt to open the report file and click 'View trace'. However, the trace does not open properly. The URL that opens is as follows: https://trace.playwright.dev/?trace=file%3A%2F%2FD%3A%2FCoding%2FHHub%2FHUB2%2FAutomationTesting%2FPlaywright%2Ftest-results%2FCatalogues-CatalogueRules-Delivery-options-rul-27844-se-41716-Validation-when-saving-contact-details-Chrome%2Ftrace.zip
![image](https://github.com/cenfun/monocart-reporter/assets/100360547/9926814c-1064-490a-bcaa-62beca9ea3bb)
And I see next page
![image](https://github.com/cenfun/monocart-reporter/assets/100360547/ac381866-2b46-4c87-b549-ddcf61f41a5b)

In order to manually upload and open the file, I must use the following URL: https://trace.playwright.dev/?trace=blob%3Ahttps%3A%2F%2Ftrace.playwright.dev%2F48a36d89-4b61-480a-b0a6-b3ea104fa705&traceFileName=trace.zip.

How to fix that?

**Comment by cenfun** [comment]
The Trace Viewer requires that the trace file must be loaded over the http:// or https:// protocols
your protocol is `file:`

`file%3A%2F%2FD%3A%2FCoding%2FHHub%2FHUB2%2FAutomationTesting%2FPlaywright%2Ftest-results%2FCatalogues-CatalogueRules-Delivery-options-rul-27844-se-41716-Validation-when-saving-contact-details-Chrome%2Ftrace.zip`

try executing following CLI to show report on a local server 
```js
npx monocart show-report <your-outputFile-path>
```

**Comment by Aroot42** [comment]
Yes, I understand. When I follow the steps you provided, everything works fine. However, when I try to view the trace by clicking 'View trace' in the report.html file, it doesn't work. 

I see that I need to update my test run scripts and add a local server run to them to view the report.

**Comment by cenfun** [comment]
how did you open the report? by dbl click the html file? or?
It determines which protocol you use. 
Are you saying that the trace cannot be open correctly on the local server?

**Comment by Aroot42** [comment]
I open my report by double click on the file.

**Comment by cenfun** [comment]
> I open my report by double click on the file.

So here's the problem, if you double-click to open the html file directly, its protocol is `file` not http, it will have security issues, the trace file is zip file that can not read by tracer viewer JS directly. or like CORS issue https://developer.mozilla.org/en-US/docs/Glossary/CORS

But after run a local server with `npx monocart show-report <your-outputFile-path>`
The report will running over the protocol http like `http://localhost:8090/`
At this point, when you open the trace file, the protocol is http too, so that it can be successfully opened by the viewer

**Comment by cenfun** [comment]
If we want to successfully open the trace file protocol, I am afraid that the playwright team needs to redesign the trace-viewer. At least the trace file cannot use the zip format. For example, change the zip format into a string of base64. anyway it definitely need playwright official support.
