### ISSUE TITLE
How to embed other types of attachments  

### ISSUE THREAD

**Issue by eva-asdf** [cenfun/monocart-reporter#28]
hello，How to embed other types of attachments

**Comment by cenfun** [comment]
for example what type?
the attachments are embed by `attach` API:
https://playwright.dev/docs/api/class-testinfo#test-info-attach
for the monocart reporter, currently shows those types:
1, image
2, video
3, trace.zip
4, html link  (audit/coverage/network report)
5, link
see https://github.com/cenfun/monocart-reporter/blob/main/packages/reporter/src/modules/attachments.js
