### ISSUE TITLE
[BUG ] issue with Custom column and Collecting Data from the Title

### ISSUE THREAD

**Issue by Aroot42** [cenfun/monocart-reporter#30]
Hiya!
I think, I found a issue with Custom column and Collecting Data from the Title.
My config file:
![image](https://github.com/cenfun/monocart-reporter/assets/100360547/7e3173d5-bf08-4468-aa45-a8176c5b41ef)

In the report I see, that data collected not only from title, but also from my code, which matched regex.
![image](https://github.com/cenfun/monocart-reporter/assets/100360547/f9065269-3e61-44a4-b3d9-e0764baf5119)

**Comment by cenfun** [comment]
try adding a condition
```
visitor: (data, metadata, collect) => {
               if (data.type === "case") {
                const matchResult = metadata.title.match(/\[(.+)\]/);
                if (matchResult && matchResult[1]) {
                    data.jira = matchResult[1];
                }
              }
}
```

**Comment by cenfun** [comment]
or the formatter only return if it's case
```js
formatter: (v, rowItem, columnItem) => {
                        if (rowItem.type !== "case") {
                            return "";
                        }

                        const key = rowItem[columnItem.id];
                        return `<a href="https://your-jira-url/${key}" target="_blank">${v}</a>`;
 }

```

**Comment by Aroot42** [comment]
Great, the second case works perfectly!
