### ISSUE TITLE
[Improve] Make metadata url clickable link

### ISSUE THREAD

**Issue by Aroot42** [cenfun/monocart-reporter#31]
Hey!
My config
![image](https://github.com/cenfun/monocart-reporter/assets/100360547/80a10369-9781-4037-95c4-a4f9cd52cba9)
I propose make it clickable
![image](https://github.com/cenfun/monocart-reporter/assets/100360547/a12c7994-90e7-4973-8c54-a28117157111)

**Comment by cenfun** [comment]
got it, will be implemented in the next release

**Comment by Aroot42** [comment]
I have 1 additional question about collecting metadata in global setup.
I added next rows in my GlobalSetup
![image](https://github.com/cenfun/monocart-reporter/assets/100360547/b3b49616-453c-4dcf-8501-bab846c7f74f)
But I didn't see information about browser in my report. What I do wrong?

**Comment by cenfun** [comment]
The codes looks ok. 
I need to reproduce it locally, can you provide a demo repo for it?

**Comment by cenfun** [comment]
The type must be string, boolean or number, please try convert browserType to string, otherwise it is a non-displayable type
![image](https://github.com/cenfun/monocart-reporter/assets/334577/74669a25-be42-4596-a0da-fae61c187eda)

**Comment by cenfun** [comment]
`1.6.30` released abd resolved above issues. 
Any metadata type will be converted to string now.
