### ISSUE TITLE
[Improve] Improve trend to include test trend

### ISSUE THREAD

**Issue by Aroot42** [cenfun/monocart-reporter#32]
Hey!
What about the idea of enhancing the trend feature by extending it to the test level? Currently, the trend feature is implemented based on launches.
I suggest storing additional data for each test and, for example, displaying the test history with results in the test information and constructing a trend graph.

Additionally, I propose grouping the test retries, for example, in a separate tab. Currently, they are simply displayed one after another.

**Comment by cenfun** [comment]
Sounds good, but there is a problem, how to know which one is the right test item in the historical data?
For example, each test must have a unique id, and how about if a test removed/changed? Seems it is very difficult to implement the test-level trend. But I guess what you need is a test management tool like [Testrail](https://www.testrail.com/)  These tools may be able to implement the test-level trend graphs

**Comment by Aroot42** [comment]
I took inspiration from the Allure report to map the trend :)
![image](https://github.com/cenfun/monocart-reporter/assets/100360547/011dd6ea-1d57-4fa3-ab98-b6e2f4b36c23)
