### ISSUE TITLE
[BUG] issue with Custom column and Collecting Data when multiple cases matched

### ISSUE THREAD

**Issue by Aroot42** [cenfun/monocart-reporter#35]
Hey
My config file:
![image](https://github.com/cenfun/monocart-reporter/assets/100360547/8779c92d-a5fa-4c65-8a57-a4a544f024cb)
I have 2 testcases linked to my test
![image](https://github.com/cenfun/monocart-reporter/assets/100360547/ac51b0fe-7324-4d99-95d2-c3172a2ce0bd)

In the report I see, that all characters from first '[' till last ']' are displayed in the column.
![image](https://github.com/cenfun/monocart-reporter/assets/100360547/c30ce2f5-ade6-421d-92db-6d2e323ce280)

In my opinion (in my head) it should be parse in cycle and displayed in column separated e.g. by comma. And open as separate links
[65738, 66131]

**Comment by cenfun** [comment]
It is easy

1, match multiple results with `matchAll` and join with `,`
```js
visitor: (data, metadata, collect) => {
      const matches = Array.from(metadata.title.matchAll(/\[([^\]]+)\]/g)).map((arr) => arr[1]);
      if (matches.length) {
          data.jira = matches.join(',');
      }
 }
```

2, formatter for multiple results
```js
formatter: (v, rowItem, columnItem) => {
      if (v) {
          return v.split(',').map((key) => `<a href="https://your-jira-url/${key}" target="_blank">${key}</a>`).join(' ');
      }
}
```

**Comment by Aroot42** [comment]
Wonderful. 
You are the best.
