### ISSUE TITLE
[Improve] Mouse over on test line styling 

### ISSUE THREAD

**Issue by edumserrano** [cenfun/monocart-reporter#36]
Currently when you mouse over on a test with tags the underline style will carry on under the tags as can be seen by:

![image](https://github.com/cenfun/monocart-reporter/assets/15857357/842e45ac-7647-4877-9579-e586e667bff2)

Suggestion: if possible, consider only putting the underline style on the title of the text and not the tags

**Comment by cenfun** [comment]
please update to monocart-reporter@1.6.33 that fixes this and #37 #39 #40

**Comment by edumserrano** [comment]
Tested on version `1.6.33` and it's working as expected. 

Thank you @cenfun 🎉 
Awesome work as always.
