### ISSUE TITLE
[Improve] Metadata only works at global level

### ISSUE THREAD

**Issue by edumserrano** [cenfun/monocart-reporter#37]
In Playwright you can configure metadata for all projects by adding:

```ts
export default defineConfig({
  ...
  metadata: {
    someKey: "someValue"
  },
  projects: [
  ...
  ]
  ...
})
```

Or you can add individual metadata per project by doing:

```ts
export default defineConfig({
  ...
  projects: [
    {
      name: "chromium",
      metadata: {
        someKey: "someValue"
      },
      ...
    }
  ...
})
```

If metadata is added per project `monocart-reporter` will not display anything.

Suggestion: if possible, add per project metadata by showing it under all tests that apply to that project. So when you open the test details you can see the `metadata` similar to how you can see the `annotations`.

I mocked something up using paint xD

![image](https://github.com/cenfun/monocart-reporter/assets/15857357/86f4909a-e3dc-4f32-b6d4-0e2f8c76f3c3)

What do you think? This would allow users to define different metadata per project and it would show up on the tests for that project.

**Comment by cenfun** [comment]
![image](https://github.com/cenfun/monocart-reporter/assets/334577/7bec989c-0f08-4ab8-aa42-140085217b51)

how about moving it under project name ?

**Comment by edumserrano** [comment]
I'm fine with that yes. I think you can choose wherever you feel best it should go. I like your suggestion.

**Comment by edumserrano** [comment]
Tested on version `1.6.33` and it's working as expected.  Metadata at project level now flows to respective tests.

![image](https://github.com/cenfun/monocart-reporter/assets/15857357/05a364a0-ca36-47b9-b127-2c92fecf7967)

Thank you @cenfun 🎉 
Awesome work as always.
