### ISSUE TITLE
[Improve] Rendering multiline data collected from comments

### ISSUE THREAD

**Issue by edumserrano** [cenfun/monocart-reporter#38]
I've followed the guide for https://github.com/cenfun/monocart-reporter#collect-data-from-the-comments and I added the following comment to a test:

```
/**
 * @description multiple lines text description 1
multiple lines text description 2
multiple lines text description 3
 */
test("basic test 3 @critical", async ({ baseURL, page }) => {
...
});
```

The report produced was as follows:

![image](https://github.com/cenfun/monocart-reporter/assets/15857357/57437539-7edf-463d-a687-26db16d74430)

The `description` column in the main report page is fine I think. There's not much I think you can do there, it's only a peak into the value anyway.

However, when we open the test details we can see the  `description` and in there there's enough space to respect multiline formats. 

Suggestion: if possible, respect multiline format from columns when on the test details panel. This might mean that certain columns would start on their own line or whatever UX you feel better. For instance, the `description` column would start below the `tags` in the test details panel.

**Comment by cenfun** [comment]
the custom column will be shown inline as simple content by default. try adding column option `detailed: true` or `markdown: true` 
```js
defaultColumns.push({
    id: 'description',
    name: 'Description',
    width: 300,
    detailed: true,
    markdown: true,
    searchable: true
});
```

**Comment by edumserrano** [comment]
That almost did the trick. After doing that I got:

![image](https://github.com/cenfun/monocart-reporter/assets/15857357/03eb0190-1841-4d82-8ef5-4e39f410f885)

Then I updated the test description to be:

```ts
/**
 * @description multiple lines text description 1 </br>
multiple lines text description 2 </br>
multiple lines text description 3
 */
test("basic test 3 @critical", async ({ baseURL, page }) => {
...
});
```

and it worked 🎉 

![image](https://github.com/cenfun/monocart-reporter/assets/15857357/33d83edb-6d08-4cf6-a549-99e0c30136a1)

Thank you @cenfun. Once again, your reporter is awesome. The amount of work you put into this is incredible and it shows! For me it's the best reporter for playwright out there and it also has good docs which allowed me to test all these things.

**Comment by cenfun** [comment]
Yes, html is available, but I think markdown is more safety:
```
        /**
         * @description ### Description Title [link](https://playwright.dev/)
- description item 1
- description item 2
- description item 3
         */
        test('@critical annotations', () => { ... }
```
Note that there is no space at the beginning of the markdown line
![image](https://github.com/cenfun/monocart-reporter/assets/334577/0f2aba13-9b73-4daa-8068-0fe6ca703132)

**Comment by cenfun** [comment]
yes, the main report page is a Grid component similar to Excel but its row height is fixed, I'm afraid there's no way to display multiple lines nicely

**Comment by edumserrano** [comment]
The above only happens when the description uses `</br>` tags to do the new lines. Like:

```ts
/**
 * @description ### Description
multiple lines text description 1 </br>
multiple lines text description 2 </br>
multiple lines text description 3
 */
 test("my test", async ({ page }) => {
 ...
 });
 ```

If I use:

```ts
/**
 * @description ### Description
multiple lines text description 1

multiple lines text description 2

multiple lines text description 3
 */
 test("my test", async ({ page }) => {
 ...
 });
 ```
 
 Then I don't get 3 columns but the new lines have 1 extra new line in between.
 
![image](https://github.com/cenfun/monocart-reporter/assets/15857357/294b3670-04cb-4a78-b0c7-c439e8b9713d)

**Comment by edumserrano** [comment]
Note that I don't want to change the main report page, the Grid component you mentioned. I think the main report page should stay as is.

Ideally if I added a comment like:

```
/**
 * @description ### Description
multiple lines text description 1 </br>
multiple lines text description 2 </br>
multiple lines text description 3
 */
 test("my test", async ({ page }) => {
 ...
 });
```

I'd like to get the text formatted on the test details as it already does. Like this:

![image](https://github.com/cenfun/monocart-reporter/assets/15857357/f391196c-fc29-4c79-a60e-d3cd2875c2b2)

But then I would also like to only have one description column in the  main report page instead of the three I'm getting :

![image](https://github.com/cenfun/monocart-reporter/assets/15857357/6a80596f-61c3-4c1e-814e-25d99d242768)

Is this what you're saying can't easily be fixed?

**Comment by cenfun** [comment]
![image](https://github.com/cenfun/monocart-reporter/assets/334577/dd26b648-bce8-48ca-a137-3d05f16eb2b3)

got it. you said there are 3 same description columns. let me reproduce it locally.

**Comment by cenfun** [comment]
I cann't reproduce it locally. I guess the reason may be that the `columns` function is executed 3 times. 
You could try following to check description column already exists before inserting it:
```js
const descriptionColumn = defaultColumns.findIndex((column) => column.id === 'description');
if (!descriptionColumn) {
    defaultColumns.splice(index, 0, {
        id: 'description',
        name: 'Description'
    });
}
```

**Comment by edumserrano** [comment]
You were right. Perhaps I need to review my playwright config to see why it was happening. But if I do the check you mentioned all works well.

Thank you!.

**Comment by edumserrano** [comment]
A note for future readers. The fix from @cenfun to avoid repeated columns in case the `columns` function is executed multiple times is not exactly correct. The if condition should be:

```ts
const descriptionColumnIdx = defaultColumns.findIndex((column) => column.id === 'description');
if (descriptionColumnIdx< 0) {
    defaultColumns.splice(index, 0, {
        id: 'description',
        name: 'Description'
    });
}
```

instead of : 
```ts
const descriptionColumn = defaultColumns.findIndex((column) => column.id === 'description');
if (!descriptionColumn) {
    defaultColumns.splice(index, 0, {
        id: 'description',
        name: 'Description'
    });
}
```

**Comment by cenfun** [comment]
thanks, edited and replaced `findIndex` with `find`
