### ISSUE TITLE
[Improve] Improvements to the search/filter functionality

### ISSUE THREAD

**Issue by edumserrano** [cenfun/monocart-reporter#39]
Suggestion: if possible I think the following would enhance the search/filter functionality:

1) move `search box` and toggles on the top right closer to the top left of the page

![image](https://github.com/cenfun/monocart-reporter/assets/15857357/ad5b570f-888c-4f71-b188-520c44e76517)

Rationale: all these options are filtering options, I might want to filter by `Failed` tests and then some keyword. It doesn't make much sense to me to have as part of the filter  on the top left and another on the top right. You could even consider bring these options closer together and centre aligning them instead of left aligning.

2) Make the `search box` larger. I think a larger input would look better. Currently, you can only enter a very small amount of text and quick enough you won't be able to see your entire `query` on the `search box`. The width on the `html` reporter feels more reasonable.

![image](https://github.com/cenfun/monocart-reporter/assets/15857357/55b95b0d-e14d-4d69-923d-f3c6ee341771)

3) Similar to what `html` reporter has on their `search box`, could we have a clear text button? 

![image](https://github.com/cenfun/monocart-reporter/assets/15857357/3c8548b1-4116-48cd-a1cc-a24d116a9a27)

4) When tags exist on the test suites, then add an extra filter option which would be a dropdown of the available tags and let the user select which tags he wants from that. This would be a shortcut to the user having to manually type all the tags he wants to filter by into the `search box`.

**Comment by edumserrano** [comment]
Tested on version `1.6.33` and it's working as expected. 

Thank you @cenfun 🎉 
Awesome work as always.

**Comment by edumserrano** [comment]
Small note on the implementation of suggestion number 4.
When you have multiple tags and you use the suggestions list from the filter box to select a tag, it should add that tag to whatever exists on the filter box. For istance:

1) on the filter box type "login "
2) then select one of the tags from the list of suggested tags (for instance tag "smoke")
3) then select another tag from the list of suggested tags (for instance tag "desktop")

Expected behaviour should be:
1) filter box should contain "login "
2)  filter box should contain "login @smoke"
3)  filter box should contain "login @smoke @desktop"

Current behaviour in `1.6.33` is:
1) filter contains "login "
2)  filter box contains "@smoke"
3)  filter box contains "@desktop"

I think it's just a matter of making sure the selection of tags from the list of suggested tags concatenates with the existing content of the filter text box instead of replacing it.

**Comment by cenfun** [comment]
got it, will be fixed

**Comment by cenfun** [comment]
try monocart-reporter@1.6.34

**Comment by edumserrano** [comment]
I can confirm this is now possible on `1.6.4` 👏 

However, there's a small issue that makes it a bit cumbersome to try to do the scenario I described before. The problem is that after you've typed something on the filter box and you click away you get something like this:

![image](https://github.com/cenfun/monocart-reporter/assets/15857357/f12a6fab-1245-42c5-a5fc-4f37c683d28f)

Then when you click the filter box again, it highlights the entire text, which means that if I then click a tag it will delete the entire contents of the filter box and just add the tag instead of appending the tag to the existing filter box content.

![image](https://github.com/cenfun/monocart-reporter/assets/15857357/2d3c13fb-93a7-4068-9cf4-28eeb4e1a0aa)

I can still do the append but after I click the filter box I need to click it again at the end of the text or use the keyboard right arrow so that the cursor is at the end of the filter box text instead of having the contents higlighted and then I can click a tag to append it.

![image](https://github.com/cenfun/monocart-reporter/assets/15857357/f61bb917-b64c-4365-be33-f701901e79d8)

Is it possible to **not** highlight the entire contents of the filter box when it gains focus?

**Comment by cenfun** [comment]
just removed the selection when focused, try version `1.6.35`
