### ISSUE TITLE
[Improve] Default width for the title column

### ISSUE THREAD

**Issue by edumserrano** [cenfun/monocart-reporter#40]
Consider changing how the default size for the title column is calculated. When I run my report I'm getting something like this:

![image](https://github.com/cenfun/monocart-reporter/assets/15857357/85091a6b-e283-4a86-8c33-dbc1e20d7b61)

With the default width for the title column, the text and tag is already cropped. 

Suggestion: if possible, make it so that the default width for the title column takes as much space as possible in attempt to display all titles without cropping. So in my test case it should look like this by default:

![image](https://github.com/cenfun/monocart-reporter/assets/15857357/a10b364d-90b7-46a6-aab4-6fff73186cf9)

If the user has a very long title in some test than it would start looking like this:

![image](https://github.com/cenfun/monocart-reporter/assets/15857357/2a59ac2a-2f4b-4312-abb1-cf1c89dd26fa)

And if the user has such a long title that it can't fit on the screen because we also need space to display the other columns than we display as much of the title as possible.

![image](https://github.com/cenfun/monocart-reporter/assets/15857357/3c78acb2-0aba-470c-92d0-091923ad29e6)

**Comment by edumserrano** [comment]
I saw that on the docs, you are right. My request was to try and make the default more user friendly.
Could the default try to be set using the above logic?

**Comment by cenfun** [comment]
The title width is 300 by default. What do you think the default width should be?
Maybe we can't find a most suitable default width, because users can view the report on their mobile phones.

**Comment by Aroot42** [comment]
Maybe you should think about stretching all the columns to 100% of the width of the screen, and setting the width of the columns to %?

**Comment by edumserrano** [comment]
My suggestion was:

> if possible, make it so that the default width for the title column takes as much space as possible in attempt to display all titles without cropping. So in my test case it should look like this by default:

So the rules would be:
1) find the max column width the title column could have. This might vary depending on screen resolution and number of columns in a report.
1) find the test title with the longest width
2) try to make the title column have enough width to display the largest title
3) if the column with for the largest title is higher than the max column width then set the it to the max column width.

As @Aroot42 pointed out this might be something that can be achieved with some CSS instead of having to do any calculations. The above rules were just to explain my reasoning.

**Comment by cenfun** [comment]
@edumserrano @Aroot42 Thank you for the suggestions about the title width.
Percentage width should not work, because it is not a simple table.
I agree that the default width of title should takes as much space as possible. This should be possible if do some calculations. let me do some research first.

**Comment by edumserrano** [comment]
Tested on version `1.6.33` and it's working as expected. 

Thank you @cenfun 🎉 
Awesome work as always.
