### ISSUE TITLE
[BUG] Incorrect test time

### ISSUE THREAD

**Issue by Aroot42** [cenfun/monocart-reporter#42]
Hey,
I have launch my tests and saw the problem when incorrect test time was showed in the main grid.
![image](https://github.com/cenfun/monocart-reporter/assets/100360547/a60971a0-1ae5-485d-a439-0552578cdfdd)
But time on the diagram was corrected.
![image](https://github.com/cenfun/monocart-reporter/assets/100360547/b318a429-c672-4a0f-872e-b4002eb554ee)

**Comment by cenfun** [comment]
Can you export the data of that row and share it, I can't reproduce this locally

**Comment by Aroot42** [comment]
Hey!
I delete my test run and currently try to get this situation again.

**Comment by cenfun** [comment]
feel free to reopen this issue if have any updates
