### ISSUE TITLE
[Improve] Code coverage summary columns

### ISSUE THREAD

**Issue by edumserrano** [cenfun/monocart-reporter#44]
Hi, 

When using `V8+monocart-reporter` for collecting code coverage, the report summary table looks like so:

![image](https://github.com/cenfun/monocart-reporter/assets/15857357/a4578aed-6b33-4f63-9bac-5aec2f6ffe65)

Note that there is no column to show `lines total/covered/uncovered`. What it's shown is `bytes total/covered/uncovered`.

Suggestion: I don't think most people look at bytes as a measure of code coverage. Could you consider replacing the `bytes` columns with `lines` columns? If you feel there's value in having those columns in the summary page then I think that's fine but the `lines` columns should be there as well.

Note that you already track that information. If I open the details for a covered file I get:

![image](https://github.com/cenfun/monocart-reporter/assets/15857357/c34971ec-1698-4e41-9b3d-1a73f3478a18)

Could we get these 3 columns, `Total lines`, `Lines covered` and `Lines uncovered` showing on the code coverage summary ? What do you think?

**Comment by cenfun** [comment]
The native v8 coverage is used to count bytes coverage but not lines. Read more about v8 coverage here:
https://v8.dev/blog/javascript-code-coverage
![image](https://github.com/cenfun/monocart-reporter/assets/334577/814272ef-b9a8-4519-ae1c-210b6753a46d)

Why native v8 coverage count bytes but not lines cause v8 counts coverage for dist file at runtime, the line coverage does not make sense for dist file most of time, the dist file is not source file, and most of time are minified (may only one line)

The monocart-reporter will try to extract the source files if the related map file is found, or format the minified js to pretty print. so there is a `Formatted` button on the report. The lines coverage you see under the bytes will be re-counted after formatted or rendered.

**Comment by cenfun** [comment]
I'm afraid it's hard to implement.
It needs to be executed in Node.js if you want to count the v8 lines, but the formatter is executed in browser when use open report. There is no good solution for now. or need someone's help
