### ISSUE TITLE
[Improve] Better `type` values on the code coverage report

### ISSUE THREAD

**Issue by edumserrano** [cenfun/monocart-reporter#45]
When collecting code coverage with `V8+monocart-reporter` the code coverage report has a `type` column which will tell you if the coverage was done for a `CSS` file or a `JS` file. 

Technically I guess those are the only 2 possible values of coverage that you can get but in the scenario where you can properly identify the source file then I think you could consider changing the `type` column to be the extension of the source file. 

For instance, given this image:

![image](https://github.com/cenfun/monocart-reporter/assets/15857357/00ed2925-ba54-418c-ab1c-817e5b2636f4)

You could say that the `type` of coverage could be `html`. Although in this example, technically speaking, the code coverage all comes from the `main.js` dist file, you do know it maps to a `.html` file.

The same with a TypeScript file:

![image](https://github.com/cenfun/monocart-reporter/assets/15857357/2a8dfe4c-0aff-4565-a0ea-439337a9790e)

In the above image, you could consider showing the type as `ts` instead of  `js`.

Suggestion: my proposal would be to look at the mapped file extension and if possible use that as the value for the `type` column. If not possible fall-back to current behaviour. 

What do you think?

**Comment by cenfun** [comment]
how about remove `type` column? 
or keep empty for the source file comes from a dist file. because for the source file we don't know what type is, like `.vue` maybe a image whatever.

**Comment by edumserrano** [comment]
I really don't know what's best here. 
Technically speaking I guess the type is really either `.js` or `.css` because that's what you get in the end bundles regardless if it's an angular app or vue app etc etc. Right?

My suggestion seemed to make sense for my scenario but perhaps doesn't work well like you said for other project types. In your example wouldn't it be ok for the `type` column to say `vue`  because it knows that code is coming from a `.vue` file?

**Comment by cenfun** [comment]
it should be shown the file extension, try monocart-reporter@1.6.34

**Comment by edumserrano** [comment]
I can confirm this is working on version `1.6.4`. Thank you =)

![image](https://github.com/cenfun/monocart-reporter/assets/15857357/30c2aa9c-9a42-4fa3-89c8-a9ad7660dbbe)
