### ISSUE TITLE
Performance issues (OOM) with a lot of coverages which needs to be converted to istanbul

### ISSUE THREAD

**Issue by hklsiteimprove** [cenfun/monocart-reporter#46]
I am running into a performance issue where I get OOM killed.
It seems like merging a lot of different coverages is somehow happening in-memory, is there any way to make it happen to the disk inbetween files?

**Comment by cenfun** [comment]
which API do you used? `addCoverageReport`?

**Comment by hklsiteimprove** [comment]
Indeed the `addCoverageReport` to add the collected `v8` coverage.
Then I use the reporter in my `playwright.config.js`

**Comment by hklsiteimprove** [comment]
My custom test extention:
```
  autoTestFixture: [
    async ({ page }, use) => {
      if (
        test.info().project.name !== 'chromium' ||
        !process.env.COLLECT_COVERAGE
      ) {
        await use('autoTestFixture')
        return
      }
      await page.coverage.startJSCoverage()
      await use('autoTestFixture')
      const jsCoverage = await page.coverage.stopJSCoverage()
      await addCoverageReport(jsCoverage, test.info())
    },
    { scope: 'test', auto: true },
  ],
```
My playwright config reporter
```
[
    'monocart-reporter',
    {
      name: 'Playwright CT React',
      outputFile: 'coverage-report/index.html',
      coverage: {
        toIstanbul: true,
        excludeDistFile: true,
        inline: true,
        sourceFilter: (sourceName) => sourceName.search(/src\/.+/) !== -1,
        lcov: true,
        watermarks: {
          statements: [50, 80],
          functions: [50, 80],
          branches: [50, 80],
          lines: [50, 80],
        },
      },
    },
  ]
```

**Comment by cenfun** [comment]
got it. 
can you helo to see how the dist file size is? and how many tests?

**Comment by hklsiteimprove** [comment]
Total collected artifact size +4GB!
Total tests 2500 ish

**Comment by cenfun** [comment]
I would think about is there any way to optimize the performance since you have so many tests
will let you know if there are any updates.

**Comment by hklsiteimprove** [comment]
It works! No more memory problems. Thanks a bunch!

**Comment by cenfun** [comment]
Thanks for your feedback.
I'm still worried if the artifacts are too big since you have thousands of tests. 
Here's how it works:
1, generate coverage data for each test, and save it to artifacts folder. you have thousands of tests, I don't know how big it will be.
2, when all tests are complete, start merging all coverage data to single one. It is easier to have OOM here.
3, remove all artifacts after merged.
I'm not sure if there will be a problem if more tests are added.
