### ISSUE TITLE
[BUG] Regression: missing snapshot attachment

### ISSUE THREAD

**Issue by edumserrano** [cenfun/monocart-reporter#47]
Hi @cenfun,

Something has happened and the attachments aren't displaying properly, at least for snapshots. From version `1.6.31` until latest what I get when a test fails is the following images:

![image](https://github.com/cenfun/monocart-reporter/assets/15857357/18830818-5215-46fa-b3ce-bb8970313a55)

![image](https://github.com/cenfun/monocart-reporter/assets/15857357/ce846881-4172-4605-bc26-a9d24be9aaf7)

When I downgrade to version `1.6.30` the attachments start showing:

![image](https://github.com/cenfun/monocart-reporter/assets/15857357/d0c66088-047e-4361-ac3b-c7fb97d40187)

I've re-used a demo playwright project I had to show the bug. You can go to [edumserrano/playwright-bug-vrt-diff/tree/monocart-reporter](https://github.com/edumserrano/playwright-bug-vrt-diff/tree/monocart-reporter) and checkout the `monocart-reporter` branch.

Then from the root of the repo just do:
- npm install
- npm run test

This will give you the result above where no attachments are shown. Any ideas what might be going wrong? I don't understand how this was working and suddenly stopped.

**Comment by edumserrano** [comment]
This definitely feels like a regression since version `1.6.31` forward. 

I've been able to narrow the problem down a bit further. It seems that the snapshot attachments aren't being displayed unless there are other attachments added after them. Most of my tests are running with an auto fixture to attach code coverage on tests and that's why I didn't notice this sooner. 

I've updated the tests in the [edumserrano/playwright-bug-vrt-diff/tree/monocart-reporter](https://github.com/edumserrano/playwright-bug-vrt-diff/tree/monocart-reporter) on the `monocart-reporter` branch to show the problem.

The test [this shows attachments well](https://github.com/edumserrano/playwright-bug-vrt-diff/blob/92861349cdb71f1b89ed4bc62bad0f8c32b40254/tests/example.spec.ts#LL4C6-L4C6) works well and produces the snapshot and code coverage attachments **but only because** the code coverage attachment is added **after** the snapshot attachment.

The test [this only shows code coverage](https://github.com/edumserrano/playwright-bug-vrt-diff/blob/92861349cdb71f1b89ed4bc62bad0f8c32b40254/tests/example.spec.ts#LL31C3-L31C3) only shows code coverage. Note that here the code coverage is attached to the test **before** the snapshots.

The test [this does not show any attachment](https://github.com/edumserrano/playwright-bug-vrt-diff/blob/92861349cdb71f1b89ed4bc62bad0f8c32b40254/tests/example.spec.ts#L57) doesn't show any attachment even though it has a `await expect(page).toHaveScreenshot();` which fails and therefore the snapshots comparison should be visible on the attachments section.

This was actually hard for me to figure out but hopefully the above info helps you quickly narrow down the problem and fix it. Let me know if you need more details @cenfun

**Comment by cenfun** [comment]
the latest version is `1.6.33`, can you upgrade it?

**Comment by cenfun** [comment]
ok, it should be a bug since image diff feature adding. I will check it.

**Comment by edumserrano** [comment]
I also found what I believe is a related bug. See image below, note that the test failed, there are only 3 images generated from the test failure in the test results folder but the tabs for snapshot attachments are duplicated.

I believe (not sure) the way to reproduce this is to have the test fail and have a `retries` option in your playwright config:

```ts
export default defineConfig({
   ...
    retries: 2,
...
});
```

![image](https://github.com/cenfun/monocart-reporter/assets/15857357/8dd35465-7b62-4e7a-b56c-3a572c2ece68)

**Comment by zhukovsv** [comment]
Hi, everyone,

Possibly I have the same issue.

Config info:
1. "nodeJS": v18.16.0
2. "@playwright/test": "1.35.0"
3. "monocart-reporter": "^1.6.33"
4. monocart config: 
![image](https://github.com/cenfun/monocart-reporter/assets/36186550/0ee109fd-46b3-49d0-ae95-10e71a3b7281)

Bug Info:

- Use attached generated monocart report for more bug info:
![image](https://github.com/cenfun/monocart-reporter/assets/36186550/ba76c5f1-28f8-4646-a3ee-1a3bf10ba32c)

- Use attached "Open link in another tab." screen:
![image](https://github.com/cenfun/monocart-reporter/assets/36186550/80ee32cc-f92c-4064-b21b-1296a9d3ed9f)


Thanks.

**Comment by cenfun** [comment]
@edumserrano it should be fixed in monocart-reporter@1.6.34

**Comment by edumserrano** [comment]
@zhukovsv I think your issue is different. It looks like the problem described here #34.

If you read #34, you probably have the same issue in that you can't configure the path for your reporter like you did. Try to change the `outputFile` to `./test-results/index.html`.

In short, the index.html for your monocart-reporter must be at the same directory as your test results directory.

**Comment by edumserrano** [comment]
@cenfun it's almost fixed. I've pushed a small commit in in the [edumserrano/playwright-bug-vrt-diff/tree/monocart-reporter](https://github.com/edumserrano/playwright-bug-vrt-diff/tree/monocart-reporter) on the monocart-reporter branch to show the problem that still occurs with retries.

I've set retries to 2:
```ts
export default defineConfig({
   ...
    retries: 2,
...
});
```
and when you run `npm run test` you will see that the test `this does not show any attachment` shows multiple tabs:

![image](https://github.com/cenfun/monocart-reporter/assets/15857357/61e3cc52-e211-41ba-b977-80f849ff58eb)

> **Note**
> The test names now don't make sense, ignore them. After updating to `1.6.34` the attachments for snapshots always show. The only problem that remains is that with retries the tabs seem to sometimes be repeated.

**Comment by cenfun** [comment]
it should be fixed, see version `1.6.35`

**Comment by cenfun** [comment]
@zhukovsv Are there any special characters in the suite title?
can you share the full image path?

**Comment by zhukovsv** [comment]
@cenfun 
test.describe('DT BASE: ', () => {
 for (const [testCaseId, toolTitle] of testData) {
  test(`${testCaseId}@${toolTitle} page should be opened.`, async () => {

    page = app.setPageByName(toolTitle, userCredential);

    await page.get();

    const pageTitle = await page.getTitle();
    await expect(page.page).toHaveScreenshot();
    //expect(pageTitle, `Not "${toolTitle}" tool was opened.`).toEqual(toolTitle);
  });
}
}

**Comment by cenfun** [comment]
![image](https://github.com/cenfun/monocart-reporter/assets/334577/622ae959-06e7-49df-93b3-3750381c3cc9)
it works well with a mock page.

**Comment by cenfun** [comment]
I don't think is path length problem.
Can you open the brower DevTools? (press F12)
There would be some errors in the console if any images failed to load.

**Comment by zhukovsv** [comment]
@cenfun 

I have code like this and it raise the issue:
test.describe('Dxxx Txxxxxxx BASE: ', () => {
  const testData: Array<[number, string, string]> = [
    [1, 'Dxxx Cxxxxxx (EU)'],
    [2, 'Deal Capture (ASIA)'],
    [0, 'Deal Capture (US)']
  ];

  for (const [testCaseId, toolTitle] of testData) {
    test(`${testCaseId}@${toolTitle} page should be opened.`, async () => {

      page = app.setPageByName(toolTitle, userCredential);

      await page.get();

      const pageTitle = await page.getTitle();
      await expect(page.page).toHaveScreenshot();   
    });
  }
}); // Main Test Suite

Then I shorten names

**Comment by zhukovsv** [comment]
I shorten names in tests and received code like this and there is no issue now:

test.describe('DT BASE: ', () => {
const testData: Array<[number, string, string]> = [
[1, 'Dxxx Cxxxxxx (EU)','DC2'],
[2, 'Dxxx Cxxxxxx (ASIA)','DC2'],
[0, 'Dxxx Cxxxxxx (US)','DC2']
];

for (const [testCaseId, toolTitle, sn] of testData) {
test(${testCaseId}@${sn} page should be opened., async () => {

  page = app.setPageByName(toolTitle, userCredential);

  await page.get();

  const pageTitle = await page.getTitle();
  await expect(page.page).toHaveScreenshot();   
});
}
}); // Main Test Suite

Path Length?

Do you still need console logs?

**Comment by cenfun** [comment]
yes, the error log will tell us why image failed to load.

**Comment by zhukovsv** [comment]
@cenfun 

[console-log-error.log](https://github.com/cenfun/monocart-reporter/files/11760256/console-log-error.log)

**Comment by cenfun** [comment]
the error message is `net::ERR_FILE_NOT_FOUND` 
I note that the protocol is `file:///D:/_AG/`
Could you please try open the report with CLI
```
npx monocart show-report <your-outputFile-path>
```
the image url will be over the `http` protocol, and see if works

**Comment by zhukovsv** [comment]
@cenfun 

npx monocart show-report test-results\multiple-html\index.html

![image](https://github.com/cenfun/monocart-reporter/assets/36186550/312d7553-0ec4-4f0c-ad69-96e254e3ed33)

**Comment by zhukovsv** [comment]
![image](https://github.com/cenfun/monocart-reporter/assets/36186550/30a03942-2cdc-46bb-b72c-ac5483fdd43b)

**Comment by cenfun** [comment]
I note that the output dir should be `test-results/multiple-html` in your config
![image](https://github.com/cenfun/monocart-reporter/assets/334577/c7f222da-4d46-4652-a507-521e4f33ce49)
but your the image url shows `test-results/p-w-report/` in logs you provided
seems the image url is wrong.

**Comment by zhukovsv** [comment]
I made this because of conflict PW and HTML report. I will made changes as you say and remove html report. 2 minutes please

**Comment by zhukovsv** [comment]
Short Names is correct in both cases:
1. CLI
2. Double click

I am runing long names. Please wait 2-3 minutes

**Comment by zhukovsv** [comment]
Long names:
1. CLI  - ALL is OK.
![image](https://github.com/cenfun/monocart-reporter/assets/36186550/3da55940-1abf-4a12-a877-febb04060895)

2. Double click is not OK!
![image](https://github.com/cenfun/monocart-reporter/assets/36186550/45a1ee4c-3f9b-47d1-9331-296897971b87)

**Comment by cenfun** [comment]
Good to know short names will works, but it's unreasonable, because your url should not great than 2k, chrome should support 64k length url, see infomation about max url length here
https://stackoverflow.com/questions/417142/what-is-the-maximum-length-of-a-url-in-different-browsers

**Comment by zhukovsv** [comment]
@cenfun 

My reports are automatically saved to a network share at night. I usually just launch them in the morning and review them. 

Do you have any idea how to fix a report launched by double-clicking?

**Comment by zhukovsv** [comment]
I will do it 2-3 hours later.

**Comment by zhukovsv** [comment]
@cenfun 

Please find prepared test-results folder:
- [test-results.zip](https://github.com/cenfun/monocart-reporter/files/11762438/test-results.zip)

**Comment by edumserrano** [comment]
@cenfun I can confirm the issues I raised are now fixed. Didn't test on version `1.6.35` but on `1.6.36` all is ok, no more duplicated tabs. 🥳

**Comment by cenfun** [comment]
@zhukovsv 
Test and it works on my PC (both Chrome v112 and MS Edge v113), there is no error on image diff, actual and exprected.
I have to close this issue now since it's about another question, feel free to create a new issue if you need more discussion. Thanks
