### ISSUE TITLE
Attachments are not displayed if the following conditions are met: the report is launched by double-click + the length of the path to the attachments is greater than 259 characters.

### ISSUE THREAD

**Issue by zhukovsv** [cenfun/monocart-reporter#49]
configuration:
"OS":	Windows 10,
"@playwright/test": "1.35.0",
"monocart-reporter": "1.6.36"

How to reproduce:
1. Extrat to the root folder (4example: d:\) attached ag-test.zip file. Root folder because of in this case all attachments will have file-path length that reproduce the issue.
![image](https://github.com/cenfun/monocart-reporter/assets/36186550/76403a73-c6ec-482e-87ae-dbe32d9f091b)

2. To install all packages go to the e2e folder and exec: 
--- npm run start

3. Exec:
--- To get report where all atachments are not shown 
--- npm run nth
--- or exec 01-show-nothing-length-32xx.spec.ts

4. Open ./test-results/index.html:
--- by double click. 
--- Do not use CLI. In CLI everything is fine.
--- Diff file-path length is greter than 259 = 260
--- Actual file-path length is greter than 259 = 262
--- Expected file-path length is greter than 259 = 264
`D:/ag-test/vsts-test/pw-dxxx-txxxxxxx-tests-dev/e2e/test-results/multiple-html/tests-d-x-01-show-nothing-length-32xx-Dxxx-Txxxxxxx-BASE-1-Dxxx-Cxxxxxx-EU-page-should-be-opened--Chrome-Stable/Dxxx-Txxxxxxx-BASE-1-Dxxx-Cxxxxxx-EU-page-should-be-opened-1-diff.png`

![image](https://github.com/cenfun/monocart-reporter/assets/36186550/b55ff48a-b451-4c93-8f9a-f5c90b314d0c)

5.  Repeat steps 3-4 for npm run diff:
--- To get report where Diff is shown + Actual and Expected atachments are not shown.
--- Diff file-path length = 259
--- Actual file-path length is greter than 259 = 261
--- Expected file-path length is greter than 259 = 263
![image](https://github.com/cenfun/monocart-reporter/assets/36186550/7a0e0661-b0a2-44f8-ab31-0c3c2d4e6160)

6. When I try to copy ag-test folder to another location by using Total Commander:
![image](https://github.com/cenfun/monocart-reporter/assets/36186550/86ef6aca-4f3c-4da8-8da6-838f2a4c49b0)

Use attached: 
- [ag-test.zip](https://github.com/cenfun/monocart-reporter/files/11771275/ag-test.zip)
- [attachment-paths.txt](https://github.com/cenfun/monocart-reporter/files/11771289/attachment-paths.txt)

Thanks.

**Comment by cenfun** [comment]
Thanks for the zip example. I can reproduce the error locally on my Windows 10.
After some searching on google, found the root cause is `Maximum Path Length Limitation`
https://learn.microsoft.com/en-us/windows/win32/fileio/maximum-file-path-limitation?tabs=registry

but it still doesn't work after added the `.reg` to Registry
```
Windows Registry Editor Version 5.00
[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\FileSystem]
"LongPathsEnabled"=dword:00000001
```
seems the `file://` protocol has a MAX_PATH limit of ~256 characters, so I just try starting a local server 
```
npx monocart show-report test-results/multiple-html/index.html
```
it works well with the `http://` protocol. hope it helps you.

**Comment by zhukovsv** [comment]
@cenfun 
Thanks for your help.

I think we can create power shell script which will located in the project root that:
1. Copy report with necessary pw-result folders to the root folder
2. Run report from root folder

something like that.

**Comment by cenfun** [comment]
Compare to use shell script, why not use `outputDir` directly
```js
const name = 'multiple-html';
const outputDir = `D:/test-results/${name}`;
```
If you run tests at night and view reports in the morning, it is recommended to use a date subdirectory
```
const date = new Date().toISOString().slice(0, 10); //yyyy-mm-dd
const outputDir = `D:/test-results/${date}`;
```
If running tests multiple times in a day, you can use full date
```
const date = new Date().toISOString().slice(0, 19); //yyyy-mm-ddThh:MM:ss
const outputDir = `D:/test-results/${date}`;
```

Freel free to keep and delete any reports in the `D:/test-results/` directory.
hope it helps you.

**Comment by zhukovsv** [comment]
Hi @cenfun,

Exactly. I messed up :-). Thanks.
