### ISSUE TITLE
[BUG] test.step failures dont fail the test , appears as passed on the html report

### ISSUE THREAD

**Issue by jensencp7** [cenfun/monocart-reporter#5]
please execute the following test and then view the report ... the test case passes on the report instead of failing.. i think when you use test.step and if the failure occurs inside the test.step it does not fail the test

const { test, expect } = require("@playwright/test");

const config = require("../../config/environment_manager");

//run command  

//ENV=dev npx playwright test tests/training/test.spec.js

var number_one = 3;

var number_two = 4;

var total = "";

test("most basic test: add two numbers", async () => {

    test.step("add two numbers", async () => {

        //adding two numbers

        total= number_one + number_two;

        console.log( "the total is: ",total);

        });

    test.step("verify total", async () => {

    //Assertion

    expect(total).toBe(6);

    });

 

  });

**Comment by cenfun** [comment]
Try using soft assertions in step: 
https://playwright.dev/docs/test-assertions#soft-assertions
```js
expect.soft(total).toBe(6);
```
I don't know why but works. and this should not be a bug of the report, but the logic of Playwright itself.
