### ISSUE TITLE
[BUG] Incorrect code coverage when converting from V8 to istanbul

### ISSUE THREAD

**Issue by edumserrano** [cenfun/monocart-reporter#50]
Hi @cenfun,

## Bug description

I mainly use the V8 code coverage when working in my dev machine and all works great. However, I have a requirement to upload code coverage to SonarQube and it requires an `lcov` file. When I enable the `monocart-reporter` option to get the `lcov` file as such:
```ts
coverage: {
    toIstanbul: true,
    lcov: true,
    ...
},
```

The code coverage that I get is incorrect. Please see screenshots below for more information. The code coverage screenshots were produced by running with:
- **babel + istanbul**: `this shows correct code coverage`.
- **v8 + monocart reporter without the `toIstanbul` property set which defaults to `false`**:  `this shows correct code coverage`.
- **v8 + monocart reporter with the `toIstanbul` property set to `true`**:  `this shows INCORRECT code coverage`.

<details>
  <summary>babel+istanbul</summary>

> **Note**
> The code coverage below is correct

`app/core/ui-services/ui-helper-functions.ts`
![image](https://github.com/cenfun/monocart-reporter/assets/15857357/0fb9dc64-614a-4c9e-b498-440c924b7f30)

`app/features/find-institution/institutions-list/institutions-list.component.ts`
![image](https://github.com/cenfun/monocart-reporter/assets/15857357/7f6cb2b8-4c24-463f-9979-fbaef617397d)
</details>

<details>
  <summary>v8 + monocart reporter without the toIstanbul property set which defaults to false</summary>

> **Note**
> The code coverage below is correct

`src/app/core/ui-services/ui-helper-functions.ts`
![image](https://github.com/cenfun/monocart-reporter/assets/15857357/d01926fc-3b5b-4a20-bec2-3a5b31fcaf31)

`src/app/features/find-institution/institutions-list/institutions-list.component.ts`
![image](https://github.com/cenfun/monocart-reporter/assets/15857357/00ca22f3-0922-451c-9f49-2c112e64e661)
</details>

<details>
  <summary>v8 + monocart reporter with the toIstanbul property set to true</summary>

> **Warning**
> The code coverage below is INCORRECT. Some lines are showed as covered when they should not be.

`app/core/ui-services/ui-helper-functions.ts`
![image](https://github.com/cenfun/monocart-reporter/assets/15857357/19b4a9db-d587-445f-b6b7-f44ef229917e)

`app/features/find-institution/institutions-list/institutions-list.component.ts`
![image](https://github.com/cenfun/monocart-reporter/assets/15857357/28142023-17f3-4aee-a42f-41ff7871fda7)
</details>

## How to reproduce

1) Checkout the temp branch at [edumserrano/monocart-code-coverage-demo/tree/temp](https://github.com/edumserrano/monocart-code-coverage-demo/tree/temp).
2) run `npm install` to install all the required packages

To get the **babel+istanbul** code coverage:

3) run `npm run test-istanbul`. The first time tests will fail because of missing snapshots, you can ignore this.
4) run `npm run nyc-report`.
5) run `npm run open-istanbul-coverage`.

To get the **v8 + monocart reporter without the toIstanbul property set which defaults to false** code coverage:

3) run `npm run test-monocart`. The first time tests will fail because of missing snapshots, you can ignore this.
4) run `npm run open-monocart-coverage`.

To get the **v8 + monocart reporter with the toIstanbul property set to true** code coverage:

3) go to the [playwright.confi.ts for the monocart setup](https://github.com/edumserrano/monocart-code-coverage-demo/blob/28d963d4b4a684c1dfcae06ccae3ba7c41512e12/tests/monocart/playwright.config.ts#L52-L53) and uncomment the lines:
```ts
// toIstanbul: true,
// lcov: true,
```
4) run `npm run test-monocart`. The first time tests will fail because of missing snapshots, you can ignore this.
5) run `npm run open-monocart-coverage`.

## More notes

To clarify, the problem is that when using `toIstanbul` set to true the code coverage conversion marks some lines as covered when they should not be.

Let me know if you need more information.

**Comment by cenfun** [comment]
if `toIstanbul = true`, the [v8-to-istanbul](https://github.com/istanbuljs/v8-to-istanbul) will take the conversion work.
seems it has bug, i'm not very familiar with it, could you please go here to find out if this bug already exists
https://github.com/istanbuljs/v8-to-istanbul/issues

**Comment by edumserrano** [comment]
Got it, I've reported this issue at istanbuljs/v8-to-istanbul#216.
Let's see what they say.

**Comment by edumserrano** [comment]
For anyone else reading this thread, I'd like to leave here feedback about how the workaround I've used until the issue the the `v8-to-istanbul` conversion is solved.

What I did was have a 2 fixtures as part of my playwright tests:
- one of the fixtures instruments the code with `v8` and I also use `monocart-reporter` configured with global code coverage which makes use of the `v8` instrumentation. This is my preferred code coverage reporting experience and the one I use on the day to day dev. 
- one of the fixture instruments the code with `istanbul`. To do this I use the `babel-plugin-istanbul` to get `istanbul` instrumentation added to my Angular app and then the fixture saves that code coverage into a folder which is then used by the `nyc` tool to produce a `cobertura` and `lcov` files. These files are what I need to upload to my Azure DevOps pipeline and SonarQ.

To understand more about how you could implement the above please read [this comment](https://github.com/microsoft/playwright/issues/7030#issuecomment-1575606073) on microsoft/playwright#7030.

For a code example read the README and see the code on the [edumserrano/monocart-code-coverage-demo](https://github.com/edumserrano/monocart-code-coverage-demo) repo. My workaround is essentially the merging of both configurations and fixtures on [/tests/babel-istanbul](https://github.com/edumserrano/monocart-code-coverage-demo/tree/main/tests/babel-istanbul) and [/tests/monocart(https://github.com/edumserrano/monocart-code-coverage-demo/tree/main/tests/monocart).

Potential downsides of this workaround is that I'm instrumenting the code twice. I haven't noticed any added slowness when running the tests but your mileage may vary. You could argue that instrumenting the code via `istanbul` only is enough since it gives me a code coverage report which I could attach to the `monocart-reporter` but I really like the user experience given by the `monocart-reporter` when a `v8` report is available.

**Comment by azamat-sharapov** [comment]
@edumserrano I'm guessing you are using the workaround for normal playwright tests, not [Component Testing](https://playwright.dev/docs/test-components) right?

**Comment by cenfun** [comment]
@edumserrano It's been a week, but there is no update on the issue. 
I did some research and found that the conversion is really complicated, it seems that the `v8-to-istanbul` library can't resolve this issue, so I rewrote a new own converter, which should fix this issue.
please try monocart-reporter@1.7.2

**Comment by edumserrano** [comment]
@cenfun you're a genius! 👏 

I can confirm this is now all working properly! Well done, thank you very much 🎉
