### ISSUE TITLE
[QUESTION] Is it possible to group everything by describe blocks rather than by file?

### ISSUE THREAD

**Issue by d-ryabtsev** [cenfun/monocart-reporter#51]
We run a lot of our tests in parallel and we really miss a feature of being able to aggregate tests by describe block. I had a quick look at the docs and can't find anything related to that. See below screenshot 

![image](https://github.com/cenfun/monocart-reporter/assets/16368445/89678c46-3871-46dc-ba87-1960fd043826)

Here I want the grouping to be by `ABC articles` and in general I want all common describe blocks on the same level grouped. Is this something you have planned in the works or are you aware of other reporters giving this functionality?

**Comment by cenfun** [comment]
you want to temporarily remove the file level suites and merge all common describe suites?
for example
☑ project
🔲 file
☑ describe
when I unchecked the file level, all file groups will be removed, and all describe groups will be merged by describe name?

**Comment by d-ryabtsev** [comment]
> you want to temporarily remove the file level suites and merge all common describe suites? for example ☑ project 🔲 file ☑ describe when I unchecked the file level, all file groups will be removed, and all describe groups will be merged by describe name?

Yes that is correct. We kinda built our own version of this but it was very rudimentary and nowhere near as detailed as monocart.

I am a little confused by the checkboxes, is this already a feature?

**Comment by cenfun** [comment]
no, it's not a feature.
I'm just imagining how it could be done if it could be a feature.
![image](https://github.com/cenfun/monocart-reporter/assets/334577/3fcf85f3-e06a-4405-a9a5-322ba1b4ced3)
You may have noticed that there is a drop down next to the title, how about adding the checkbox for each of the suite level?

**Comment by d-ryabtsev** [comment]
> no, it's not a feature. I'm just imagining how it could be done if it could be a feature. ![image](https://user-images.githubusercontent.com/334577/246666998-3fcf85f3-e06a-4405-a9a5-322ba1b4ced3.png) You may have noticed that there is a drop down next to the title, how about adding the checkbox for each of the suite level?

yeah I mean for us having the project level or file level is not useful. So it would be great if we could just see aggregated describes.

**Comment by cenfun** [comment]
![image](https://github.com/cenfun/monocart-reporter/assets/334577/2cc4896e-7c5f-4fe0-acde-92394f03280c)
Please try version monocart-reporter@1.7.1
You will find a drop down list in the top right corner, the group's switch button can be used to show or hide the group, an additional switch button is used to merge groups by title.

**Comment by d-ryabtsev** [comment]
> ![image](https://user-images.githubusercontent.com/334577/247006561-2cc4896e-7c5f-4fe0-acde-92394f03280c.png) Please try version monocart-reporter@1.7.1 You will find a drop down list in the top right corner, the group's switch button can be used to show or hide the group, an additional switch button is used to merge groups by title.

Thanks! We will try this out
