### ISSUE TITLE
Question: Attatching a sceenshot on the reporter

### ISSUE THREAD

**Issue by emihlentinzi** [cenfun/monocart-reporter#55]
I have a function for screenshots that I call on my tests but I want to attach the screenshots that I take on the reporter as well instead of just saving it in my local path. How can I attach the screenshots on the reporter?

**Comment by cenfun** [comment]
try `attach` API https://playwright.dev/docs/api/class-testinfo#test-info-attach
```js
import { test, expect } from '@playwright/test';

test('basic test', async ({ page }, testInfo) => {
  await page.goto('https://playwright.dev');
  const screenshot = await page.screenshot();
  await testInfo.attach('screenshot', { body: screenshot, contentType: 'image/png' });
});
```
