### ISSUE TITLE
Improve screenshot/diff compare

### ISSUE THREAD

**Issue by hampsterx** [cenfun/monocart-reporter#56]
hi there, great reporter well done, loving it!

Using it to fault find/check test failures particularly the image diffs is a bit painful and time consuming however.

Eg

![diff](https://github.com/cenfun/monocart-reporter/assets/1887721/77cad9ee-6dca-4ccc-8710-d7bc95961f78)

My workflow currently is to 

- open each image
- align/resize side by side
- start eye balling

This could be done in the reporter. eg one row per fail (diff, expected, actual) and a zoom handle that was linked to all 3 so you could move to the diff area and then easily eye ball the actual vs expected. This is probably easier implemented than an onion skin comparison like github uses for example and would be reasonably effective.

open to ideas/thoughts, much appreciated~

**Comment by cenfun** [comment]
Could you please try the latest version? This feature should be like following
![image](https://github.com/cenfun/monocart-reporter/assets/334577/9e10c33b-55d1-4334-9bc4-91a99099a4b0)
https://cenfun.github.io/monocart-reporter/#page=detail%2F4a507151529b7a034a55%2Fimage+comparison

**Comment by hampsterx** [comment]
wow this is great @cenfun 

Still requires a bit of toggling back and forth to pick up diffs but its pretty sweet thnx

**Comment by hampsterx** [comment]
doh I should have tested on some bigger fails haha

![playwright-t1](https://github.com/cenfun/monocart-reporter/assets/1887721/c69946c1-8b0b-4f58-99bc-109f1607ee32)

the tab names are orderd by the type ("diff" "actual" "expected") and does not work well when more than one :(
 
I think you need to sort alpha filename first then iterate 3 tabs each or something :)

**Comment by cenfun** [comment]
It looks like a bug, if there are some special data. 
Can you provide us reproduction steps? So we can reproduce it locally?
1. create a mini repo which it can reproduce the issue.
2. or provide the report html/json which we can debug it.

Thanks

**Comment by hampsterx** [comment]
hi @cenfun 

Ahh I probably should have mentioned we are using soft fail hence there can be more than one image per test fail! 

We have quite large E2E tests with many screen comparisons, sometimes its just a field shifting or label changed or something hence we dont want to fail the test.

Here is a demo repo: https://github.com/hampsterx/playwright-monocart-image-test

![image](https://github.com/cenfun/monocart-reporter/assets/1887721/eec7d45d-42fa-4aa5-abbf-99145d3580f5)

Much appreciated,

**Comment by cenfun** [comment]
hi @hampsterx thanks for the demo repo
The bug should be fixed, please try version monocart-reporter@1.7.5
You are right, the root cause is multiple soft fails.

**Comment by hampsterx** [comment]
works great thanks for that fix @cenfun :)

The click down to toggle diff/actual works OK, still a bit hard to find the issues sometimes but doable. kudos~

**Comment by cenfun** [comment]
Do you have a chance to tell us details why there is a bit hard to find the issues sometimes?
Maybe I can make some improvements for it, thanks

**Comment by hampsterx** [comment]
a couple of reasons..

- the "diff" toggles with "actual"
- "actual" toggles with "expected"

The problem is you need to see both "actual" and "expected" at the same time so you end up clicking a couple of times on "diff" to see the issue, then you have to change to "actual" and click a few more times to get a feel for it. Then you have to do a bit of a mental map in your head to figure out whats actually going on. Anyway that is my workflow, clicky clicky, toggle, clicky clicky.. THINK. 

we also have heaps of very long (vertical) screenshots so then it involves another step of scroll back to top to change the tab.

Another issue is its just hard to see the change when its at normal/1x zoom, having an enlarged view of the area in question would make it much easier.

To expand on the 3 way viewer with zoom idea..

Something like this (excuse my poor design skills)

![Blank diagram (2)](https://github.com/cenfun/monocart-reporter/assets/1887721/2e98cca9-639d-45ac-8476-349a5e06dee9)

Eg you mouse over and the zoom handle is locked to the other 2x images:

One downside though is having 3x image will mean the images would be quite small to fit them in and if its only a very small diff (ie a few pixels) it might be hard to even spot. 

thoughts appreciated~

**Comment by cenfun** [comment]
Thanks. It is reasonable.
1, Currently, mouse down/up on the image(not tab) will be able to quickly switch tab between neighbors.  
And I plan to add a feature is that when hold on the mouse down, if move the mouse to the left or right, it can change the tab to left one or right one. The purpose is to quickly switch between 3 tabs instead of 2 tabs. 

2, Yes, it is hard to see the details if a big image is reduced to the container.
And I plan to add a Zoom In/Out feature, it uses mouse wheels to control.

what do you think?

**Comment by hampsterx** [comment]
yeah that would allow to toggle all 3 tab I guess.
Zoom in/out (full size) will make it easier to see for sure.

I still think its going to be a lot of clicky click to see the diff tho I would rather see all 3 view in one then alternate between 3

**Comment by cenfun** [comment]
for the seeing the 3 view together, do you have any UI and interactive reference demo or link?

**Comment by cenfun** [comment]
Thanks for the demo.  Please try monocart-reporter@1.7.6 for the improments.

**Comment by hampsterx** [comment]
hi @cenfun I appreciate the effort!

ok so the zoom works but with one small side effect in that you cannot use the scroll wheel now to move down the report because its being trapped in the image so its a little bit difficult usability wise.

The other issue is of course the tab approach (1 image at a time) is just a lot of clicking/toggling between diff and actual tabs and the reconciling in your brain required to figure out the changes which just makes the process very time consuming and prone to giving me a seizure haha.
