### ISSUE TITLE
[Question] Possible to input timezone parameter?

### ISSUE THREAD

**Issue by xyngfei** [cenfun/monocart-reporter#59]
Hi @cenfun 

Is there any way to configure the timezone for displaying the test result? bcos my test agent is running at the timezone UTC+00:00 and currently we are not allowed to modify the time setting due to some restriction.

currently i m using https://www.npmjs.com/package/date-fns to handle my datetime format
![image](https://github.com/cenfun/monocart-reporter/assets/17619539/9267c059-009b-4312-944a-23c683da99c9)

**Comment by cenfun** [comment]
good question.  how about adding one more option "timezoneOffset" like
```
// playwright.config.js
module.exports = {
    reporter: [
        ['list'],
        ['monocart-reporter', {  
            name: "My Test Report",
            outputFile: './test-results/report.html',
            timezoneOffset: 480,
        }]
    ]
};
```
any idea?

**Comment by xyngfei** [comment]
tried, cant work as expected, still remain utc+0

**Comment by xyngfei** [comment]
tried with 1.7.9, cant work as expected

**Comment by cenfun** [comment]
no, it is not completed yet, just discuss whether the idea is OK

**Comment by xyngfei** [comment]
roger that, should be okay. This is a good way to modify it. 

Actually, I am also thinking of adding the application version number into reporter name, I just don't have any idea how to do it, because it will require launching the application to get the value in the global-setup. Do you have any suggestions?

**Comment by cenfun** [comment]
ok, I will think about how to support dynamic report name.

**Comment by cenfun** [comment]
Please update version to monocart-reporter@1.7.10
1, new option `timezoneOffset`
```
// playwright.config.js
module.exports = {
    reporter: [
        ['list'],
        ['monocart-reporter', {  
            name: "My Test Report",
            outputFile: './test-results/report.html',
            timezoneOffset: -480, // timezone offset in minutes, GMT+0800 = -480
        }]
    ]
};
```
2, change report name dynamically by using [global state](https://github.com/cenfun/monocart-reporter#global-state-management)
first, setup global state with custom onReceive function
```
module.exports = {
    reporter: [
        ['list'],
        ['monocart-reporter', {  
            name: "My Test Report",
            outputFile: './test-results/report.html',
            state: {
                onReceive: function(message) {
                    if (message && message.reportName) {
                        this.options.name = message.reportName; // change report name
                        return;
                    }
                }
            }
        }]
    ]
};
```
using state API in your test file like in global-setup.js
```
const { useState } = require('monocart-reporter');
const state = useState();
module.exports = async (config) => {
    await state.send({
        reportName: 'My new report name'
    });

};

```
actually you can change everything with state API.

**Comment by xyngfei** [comment]
@cenfun you are really impressive, especially with your fast response and resolution. It works as expected. 
I will migrate to your reporter for reporting purposes. tqvm
