### ISSUE TITLE
[Question] Is it possible to use custom test step names?

### ISSUE THREAD

**Issue by Aenz99** [cenfun/monocart-reporter#6]
Hello, my name is Andres, I'm quite new to this reporter.

Is it possible to use custom test step names?
What I mean is if it is possible to change the names in the title column, e.g: "page.goto", "locator.fill" "waitforloadstate"
I would like to have other titles like "accessing the login page" "completing phone number"

Thanks in advance.
Cheers

**Comment by cenfun** [comment]
Anyway, I thougth that there was a way to replace these titles with config programming in reporter.
```js
// playwright.config.js
module.exports = {
    reporter: [
        ['monocart-reporter', {  
            name: "My Test Report",
            outputFile: './test-results/report.html',
            columns: (defaultColumns) => {
                // custom reporter data with invisible column visitor
                defaultColumns.push({
                    id: 'my-invisible-column-id',
                    invisible: true,
                    visitor: (data, metadata) => {
                        if (data.type === 'step') {
                            if (data.title === 'Before Hooks') {
                                data.title = 'My custom step title 1';
                            } else if (data.title.startsWith('page.goto')) {
                                data.title = 'My custom step title 2';
                            }
                        }
                    }
                });
            }
        }]
    ]
};
```

**Comment by Aenz99** [comment]
Hi Cenfun, thanks for your quick reply!
I will try to use your recommendations and see how it goes.

Thanks a lot.

**Comment by Aenz99** [comment]
Actually what worked better for me was your second solution. That was what I was looking for.
Thanks Cenfun.
