### ISSUE TITLE
Is it possible to use it with other runners?

### ISSUE THREAD

**Issue by ptol** [cenfun/monocart-reporter#61]
I use playwright but I dont use playwright test runner.
I would like to use V8 test coverage functionality but it depends on TestInfo from playwright test runner.
Is it possible to use it with other runners somehow?

**Comment by cenfun** [comment]
which test runner you used?
currently, the v8 test coverage functionality includes two parts:
1, nodejs codes: generate coverage report data https://github.com/cenfun/monocart-reporter/tree/main/lib/plugins/coverage
2, coverage report: already is UI component https://github.com/cenfun/monocart-reporter/tree/main/packages/v8
Technically, it can be used alone, but the nodejs part requires some changes

**Comment by ptol** [comment]
I use cucumber.js
I am interested in https://github.com/cenfun/monocart-reporter/tree/main/lib/plugins/coverage
I did some local changes to remove testInfo, and I can create report for one test, but it's hard to figure out to how do global report with merge. There is
[const mergeV8Coverage = async (dataList, options) => {](https://github.com/cenfun/monocart-reporter/blob/65d6c1cef0b29609b56dd06c700768d5bd34da77/lib/plugins/coverage/v8/v8.js#L109C7-L109C23)
but I don't know how to create dataList form v8list
I think it would be useful if some core login doesn't depend from test runner

**Comment by cenfun** [comment]
1, I don't think removing testInfo is good way, actually testInfo just provide some infomation or options, it may be better to mock a testinfo
```
testinfo : {
  title: "test title",
  testId: "test-id",
  retry: 0,
  attachments:[],
  project: {
    outputDir: "output_path_here"
  },
  config: {
    reporter: [
      ["monocart-reporter", {
        //options
      }]
    ]
  }
}
```
2, global report
- call addCoverageReport to save a single time report data to local artifacts, append the path info to testinfo.attachments, the artifacts doese not remove if reporter option `logging` type is `debug`
example `coverage\.artifacts`
![image](https://github.com/cenfun/monocart-reporter/assets/334577/67f51547-a6a8-4fca-8a8d-a370e8acaad6)

- after all tests done, will generateing global report, see function `generateGlobalCoverageReport(dataList, reporterOptions)`
the dataList should be the list of testinfo.attachments, reporterOptions should be global coverage options.
first, it read all artifacts, then merge them to a single data list, and generate html report with merged data list

seems it is separated from test runner but only depends on testInfo. I haven't used cucumber.js, but if you need any help please  let me know, for example adding some API to reporter, or exporting some API from reporter.

**Comment by user753** [comment]
Thanks. Mocking TestInfo really helps.
Now I have all this json file in `coverage\.artifacts`
How can I use them to generate report? `generateGlobalCoverageReport` is not exported from the package

**Comment by ptol** [comment]
Thanks. Mocking TestInfo really helps.
Now I have all this json file in coverage\.artifacts
How can I use them to generate report? `generateGlobalCoverageReport` is not exported from the package.
I try to export `generateGlobalCoverageReport` and use it ```generateGlobalCoverageReport(testInfo.attachments, reporterOptions)```
but it generates empty istanbul report.

**Comment by cenfun** [comment]
Good progress.
1, read them all, see [artifactHandler](https://github.com/cenfun/monocart-reporter/blob/main/lib/visitor.js#L520)
2, pass them to [generateGlobalCoverageReport](https://github.com/cenfun/monocart-reporter/blob/main/lib/generate-data.js#L23)

try following (I didn't test)
```
var globalList = [];
testInfo.attachments.forEach(item=> {
  const json = readJSON(item.path);
  globalList.push(json.data)
})

await generateGlobalCoverageReport(globalList, reporterOptions)
```

**Comment by ptol** [comment]
It works. Thanks.
I think some public function like `addGlobalCoverageReport(data, testInfo)` could be useful.

**Comment by cenfun** [comment]
Great, I will exporting some public methods for coverage report.

**Comment by cenfun** [comment]
please try monocart-reporter@1.7.12, a new public API `addGlobalCoverageReport` added.
 
1, improvement for `addCoverageReport(v8list, testInfo, options)`:
```
var testInfo = {
  title: "test title",
  testId: "test-id",
  retry: 0,
  attachments:[]
}
var options = {
  outputDir: "mydir",
  outputName: "coverage"
}
await addCoverageReport(v8list, testInfo, options);
```

2, `addGlobalCoverageReport`
```
export function addGlobalCoverageReport(
    dataList: any[],
    options: CoverageReportOptions
): Promise<any>;
```
- dataList is above `globalList`, please read all data from attachments json file.
- options is coverage options see https://github.com/cenfun/monocart-reporter/blob/main/lib/index.d.ts#L31

**Comment by ptol** [comment]
It works. Thanks.
