### ISSUE TITLE
Support all istanbul-reports reports instead of only lcov

### ISSUE THREAD

**Issue by ptol** [cenfun/monocart-reporter#63]
` istanbul-reports` has many report types, but coverage options support only lcov
 I think the options could be 
 ```
 istanbulReportName: "clover" | "cobertura" | "html-spa" | "html" | "json" | "json-summary" | "lcov" | "lcovonly" | "none" | "teamcity" | "text" | "text-lcov" | "text-summary"
 instanbulReportOptions: any
```

**Comment by cenfun** [comment]
it should be supported in version monocart-reporter@1.7.13

please use the option `toIstanbul`:
- `toIstanbul: true` defaults to html-spa
- `toIstanbul: 'html'` html report
- `toIstanbul: ['html', 'json']`  multiple reports
- multiple reports with report options
```
toIstanbul: ['html', 'json', {
            name: 'json',
            options: {
                file: 'my-json-file-name.json'
            }
}]
```
