### ISSUE TITLE
[Question]When report is sent to email, the attachments in the report has the local path and unable to access/open them

### ISSUE THREAD

**Issue by kiran1503** [cenfun/monocart-reporter#65]
[Question]can you please, suggest a way? how to achieve the screenshots in the report, which is sent via email

**Comment by cenfun** [comment]
How many screenshots in your report usually? 
Obviously it is not recommended to send a large number of screenshots through email, but following should be wok:
[monocart-reporter](https://github.com/cenfun/monocart-reporter) send email with [Nodemailer](https://nodemailer.com/), so you need sending all screenshots with configuration [attachments](https://nodemailer.com/message/attachments/), then you need replacing all screenshots path with email attachment path (see [Embedded images](https://nodemailer.com/message/embedded-images/))
```js
// playwright.config.js
module.exports = {
    reporter: [
        ['list'],
        ['monocart-reporter', {  
            name: "My Test Report",
            outputFile: './test-results/report.html',
            attachmentPath: (currentPath, extras) => `cid:${currentPath}`
        }]
    ]
};
```

But we also recommend using remote services to store screenshots (includes trace.zip and video files)
1, replace all screenshots path with url 
2, upload all screenshots to own web server after test
```js
// playwright.config.js
module.exports = {
    reporter: [
        ['list'],
        ['monocart-reporter', {  
            name: "My Test Report",
            outputFile: './test-results/report.html',
            attachmentPath: (currentPath, extras) => `http://www.myreport.com/my-project/the-date/${currentPath}`,
            onEnd: async (reportData, capability) => {
                // upload all screenshots to own web server with your scripts
                
            }
        }]
    ]
};
```
hope it helps you
