### ISSUE TITLE
[Question] Coverage data with source maps for Electron app

### ISSUE THREAD

**Issue by rkristof** [cenfun/monocart-reporter#66]
I managed to get coverage data (V8) for my Electron tests in an Electron + Angular app, but the coverage only shows the .js files built by Angular, instead of the original .ts source files (which works for my normal, browser based tests):

![kép](https://github.com/cenfun/monocart-reporter/assets/43443461/9561c23d-785b-460f-93f4-56b2c936e347)

Is it possible to actually map this coverage information to the original source files? I included the Angudar source maps (inline) when building the Electron app. If I start my Electron app and open the devtools, I can see the original source files under webpack://, and I can even set breakpoints in them. I thought this would be enough to see the coverage data for the original source, but it didn't really help. Do you have any ideas how this could be solved?

Great library by the way, the coverage data has been really helpful for my browser based tests :)

**Comment by cenfun** [comment]
Yes, we must generate the sourcemaps when building if we want to generate the coverage reports of the source files.
I'm not sure if the inline sourcemaps works, but the sourcemap files should be working.
for example, there is a file "main.js" in your list, if it's url is:
http://localhost/www/main.js
and it's sourcemap file should be:
http://localhost/www/main.js.map 
any chance to replace the inline sourcemap with the separation sourcemap file?
or could you please create a minimal repo to reproduce the problem, thanks.
