### ISSUE TITLE
[Improve] Allow choosing which global code coverage report to use with the monocart test results report

### ISSUE THREAD

**Issue by edumserrano** [cenfun/monocart-reporter#69]
## Request

Would it be possible that we could choose the html report to use for the global code coverage instead of defaulting to whatever is at `coverage/index.html` ?

To be more specific, what I'd like to do is be able to use with the `toIstanbul` [code coverage option](https://github.com/cenfun/monocart-reporter#coverage-options) but still get the monocart html report for code coverage. The only reason I use the `toIstanbul` is to produce a `cobertura` and `lcov` files which I then upload to Azure Devops and Sonarqube respectively. However, when I'm looking at the code coverage I much rather the built in report from monocart, instead of the one I get from istanbul.

## Basic suggestion to exemplify the request

1) Perhaps there could be an extra parameter on the [code coverage option](https://github.com/cenfun/monocart-reporter#coverage-options) that would let us specify the path to the global code coverage file and if not specified default it to `coverage/index.html` ? 

2) Furthermore, even if the `toIstanbul` is configured, could there be some option to still keep the `monocart` global code coverage report? In addition to this option, another option to specify the path the html report would be nice, something similar to the istanbul `subDir` that is mentioned on #68 but that would apply to the monocart global code coverage report.

With the above 2 points we could do something like this:

```ts
{
  name: 'playwright code coverage with monocart reporter',
  outputFile: ...,  
  coverage: {
    reportFile: '<playwright configuration output dir>/coverage/monocart-code-coverage-report/global-coverage.html' 
    report: {
      overwriteWithIstanbul: false,
      outputFile: '<playwright configuration output dir>/coverage/monocart-code-coverage-report/global-coverage.html'
    },
    toIstanbul: [
      {
        name: 'html-spa',
        options: {
          subdir: 'code-coverage-html-spa-report' // note that this is a valid option for the html-spa istanbul reporter
        }
      }
    ],
  },
},
```

Where:
- `coverage.report.overwriteWithIstanbul`: would determine if we keep the monocart code coverage report if we're also using the `toIstanbul` set to anything other than `false`. The `overwriteWithIstanbul` could default to `true` to keep existing behavior.
- `coverage.report.outputFile`: would define the path for the entry point html file and all related files for the monocart global code coverage report.

With the above configuration I'd get the following output for global code coverage:
- folder at `<playwright configuration output dir>/coverage/code-coverage-html-spa-report` with the code coverage report from `html-spa` istanbul reporter.
- folder at  `<playwright configuration output dir>/coverage/monocart-code-coverage-report` with the monocart code coverage report with the entry html file named `global-coverage.html` and all other related files inside this folder.
- because I specified  `coverage.reportFile` to be `<playwright configuration output dir>/coverage/monocart-code-coverage-report/global-coverage.html` then I'd get the monocart global code coverage when I browsed the test results. But I could have set this property to `<playwright configuration output dir>/coverage/code-coverage-html-spa-report/index.html` and I would get the code coverage report from the `html-spa` istanbul reporter.

## Further notes

1) This is a bit related with #68. If you agree with implementing something similar to what was suggested then #68 should likely be possible to close.
2) The istanbul reporter options can be found [here](
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/276d95e4304b3670eaf6e8e5a7ea9e265a14e338/types/istanbul-reports/index.d.ts#L42).
3) The basic suggestion is just that, a simple idea. However it gets done I think it's fine as long as I could generate istanbul reports and still keep the monocart reporter plus then be able to choose which global code coverage report to be linked in the monocart tests report.  Perhaps we wouldn't need an option like the `coverage.report.overwriteWithIstanbul` or the `coverage.report.outputFile` if it was decided that the monocart global code coverage would always be placed in its own folder inside the `coverage` folder and that it would always be named `index.html`. This way it would solve most of this problem and we would only need an option like `coverage.reportFile` to be able to specify which global code coverage report to use (and this could default to the monocart global code coverage path).

Please let me know your thoughts or if I haven't made the request clear or if you think it's not worth it etc.

**Comment by cenfun** [comment]
It's good time to think about this featrue, because i am planning to separate the coverage related features to a standalone project [monocart-coverage-reports](https://github.com/cenfun/monocart-coverage-reports)

**Comment by edumserrano** [comment]
I think we can close this one in favour of the work that you did to release `v2.0.0` and this [comment](https://github.com/cenfun/monocart-reporter/issues/68#issuecomment-1845657933) in #68.
