### ISSUE TITLE
Where is the Jira Key link stored?

### ISSUE THREAD

**Issue by emihlentinzi** [cenfun/monocart-reporter#7]
When I click on my Jira ticket under the Jira Key column I want it to take me to my Jira ticket. Where would I store my Jira ticket link in order to achieve this?

Link for the screenshot:
https://user-images.githubusercontent.com/76787646/225252177-7053c774-e0cb-4b48-9544-0d139e01fe9f.png

I would appreciate your assistance. Thank you.

**Comment by cenfun** [comment]
please try to specify a formatter for the Jira Key column:
https://github.com/cenfun/monocart-reporter/blob/main/tests/playwright.config.js#L92-L94

```js
{
    id: 'jira',
    name: 'JIRA Key',
    width: 100,
    searchable: true,
    styleMap: 'font-weight:normal;',
    formatter: (valueFormatted, rowItem, columnItem) => {
        const key = rowItem[columnItem.id];
        return `<a href="https://your-jira-link.com/${key}" target="_blank">${valueFormatted}</a>`;
    }
}

```

**Comment by emihlentinzi** [comment]
Thanks a lot, that worked.

**Comment by emihlentinzi** [comment]
Thanks a lot, that worked.
