### ISSUE TITLE
Report not loading ( undefined (reading 'Util'))

### ISSUE THREAD

**Issue by jefbarn** [cenfun/monocart-reporter#75]
Wanted to try out the code coverage stuff, but can't even get the basic report to load.

Uncaught TypeError: Cannot read properties of undefined (reading 'Util')
    at (index):48:14656
    at (index):48:15400
    at (index):48:15406
    at (index):48:282
    at (index):48:297

```javascript
;const k={...y.Util,...T(),isTouchDevice:function(){return"ontouchstart"in window||navigator.maxTouchPoints>0||navigator.msMaxTouchPoints>0}},A=()=>{const e=document.querySelector('link[rel="icon"
```

```typescript
  reporter: [
    ['list'],
    ['monocart-reporter', {
      name: "Monocart Test Report",
      outputFile: './test/report/index.html'
    }],
  ],
```

**Comment by cenfun** [comment]
seems there is a lib haven't loaded.

which version did you installed? could you please try clean node modules and reinstall it?

or provide demo repo and reproduction steps.

**Comment by debasisj** [comment]
I am getting same issue 
<img width="1220" alt="image" src="https://github.com/cenfun/monocart-reporter/assets/17722879/90229259-e990-46b0-b66b-f927cb4239b0">
There is no error on console 
version : `2.0.1`
playwright version : `1.35`

**Comment by cenfun** [comment]
checking ...

**Comment by debasisj** [comment]
I will try and let you know asap

**Comment by jefbarn** [comment]
Yeah that seems to be the issue. Manually installed turbogrid dependency and now it's working.
I think this is because I'm using pnpm and its dependency resolution doesn't put everything in the root node_modules, so if you are hard linking to there it will break. If needed you could add turbogrid as a peer dependency.

**Comment by cenfun** [comment]
@jefbarn  thanks for your feedback. actually the `turbogrid` already is in production dependence, see latest [package.json](https://github.com/cenfun/monocart-reporter/blob/main/package.json#L54)
so it's no need to add turbogrid as a peer dependency.

I guess the root cause is because the `turbogrid` is the new dependency added in the version 2.0+, the node modules haven't uddated normally.

**Comment by jefbarn** [comment]
@cenfun Thanks for looking. I think the problem is anyone using 'non-standard' node_modules layout is going run into. Instead of linking to the version of turbogrid that is under this module in the dependency tree, it's trying to link to the root node_modules...which doesn't have turbogrid (because turbogrid isn't a direct dependency of my project).

I'm guessing that it's just one too many "../../../" levels in the import statement somewhere.

**Comment by azamat-sharapov** [comment]
I had the same problem. @cenfun you can actually reproduce this in my [repo](https://github.com/azamat-sharapov/monocart-coverage-repro) that I reported for #74. From the root of project, run:
```
pnpm up --latest --recursive monocart-reporter
cd apps/web
pnpm e2e
```
and when tests are running, you should see some errors in terminal already. If you then open `test-results/index.html`, there are JS errors in console.

**Comment by cenfun** [comment]
@azamat-sharapov I note that there is [pnpm-lock.yaml](https://github.com/azamat-sharapov/monocart-coverage-repro/blob/main/pnpm-lock.yaml) in the root dir, can you delete it and reinstall again?

**Comment by azamat-sharapov** [comment]
@cenfun it didn't change anything unfortunately. I removed pnpm-lock.yaml, deleted all node_modules dirs and then changed `monocart-reporter` version to `^2.0.1` manually in `apps/web/package.json` file. Then ran `pnpm install` from root dir. Nothing changed, same error. This is the error from terminal btw:

```
[MR] generating report data ...
[MCR] write file: /Users/Admin/code/monocart-coverage-repro/apps/web/test-results/assets/monocart-code-viewer.js The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received undefined
[MCR] write file: /Users/Admin/code/monocart-coverage-repro/apps/web/test-results/assets/monocart-formatter.js The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received undefined
[MCR] write file: /Users/Admin/code/monocart-coverage-repro/apps/web/test-results/assets/turbogrid.js The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received undefined
```

**Comment by debasisj** [comment]
> I found it's a `pnpm` issue, see [stackoverflow](https://stackoverflow.com/questions/70597494/pnpm-does-not-resolve-dependencies) I don't know why pnpm need this , but the `turbogrid` will be installed after using following CLI
> 
> ```shell
> pnpm i --shamefully-hoist=true
> ```
> 
> @azamat-sharapov @jefbarn @debasisj I guess you are using `pnpm`, please have a try.

yes we are using the pnpm and i guess this is causing the issue ..

**Comment by jefbarn** [comment]
The workaround to avoid using the "shamefully-hoist" setting is to add these lines to your .npmrc:
```ini
# These two are defaults
public-hoist-pattern[]=*eslint*
public-hoist-pattern[]=*prettier*
# These cause the monocart dependencies to be hoisted to the root node_modules
public-hoist-pattern[]=*monocart*
public-hoist-pattern[]=*turbogrid*
```

**Comment by debasisj** [comment]
i have to manually install `turbogrid` to make it work - our .npmrc already has the flag `shamefully-hoist=true`

**Comment by cenfun** [comment]
Please try version monocart-reporter@2.0.2 which has fixing for `pnpm` issue. @azamat-sharapov @jefbarn @jefbarn 

After some research, I found that the structure of `pnpm` is different from the conventional `npm`, so the new version can be compatible with two structures. Let me know if you have any questions, thanks.

**Comment by azamat-sharapov** [comment]
@cenfun I can confirm it's working well now. Thanks!

**Comment by debasisj** [comment]
> Please try version monocart-reporter@2.0.2 which has fixing for `pnpm` issue. @azamat-sharapov @jefbarn @jefbarn
> 
> After some research, I found that the structure of `pnpm` is different from the conventional `npm`, so the new version can be compatible with two structures. Let me know if you have any questions, thanks.

thanks
