### ISSUE TITLE
(fix) coverage: sourceFilter not filtering out all undesired paths

### ISSUE THREAD

**Issue by vespoli95** [cenfun/monocart-reporter#78]
The `sourceFilter` parameter under `coverage` in `playwright.config.ts` does not seem to be filtering out certain paths properly.

Here is my sourceFilter: 
![image](https://github.com/cenfun/monocart-reporter/assets/20251812/9617a16b-5564-45b0-bf57-312f28f26e99)

According to this, only `.tsx` files under `/src/components` should be used for coverage, yet I get the following coverage report:

![image](https://github.com/cenfun/monocart-reporter/assets/20251812/cba6b633-6d77-462c-af17-497ed09f33e6)

I am still receiving `.js` bundle files as part of the report.

**Comment by cenfun** [comment]
please try one more option `entryFilter` which will filter unnecessary files like 3th bundles, vendors etc.

**Comment by vespoli95** [comment]
> please try one more option `entryFilter` which will filter unnecessary files like 3th bundles, vendors etc. a example here [#77 (comment)](https://github.com/cenfun/monocart-reporter/issues/77#issuecomment-1851264803)

This worked! Thank you!
