### ISSUE TITLE
Not the issue, but a request. Is it possible to have some integration with Slack?

### ISSUE THREAD

**Issue by i-novo** [cenfun/monocart-reporter#8]
I saw the feature to send emails with attached report and summary to some email address. But just wondering if it's possible to implement something to have pretty same report in Slack channel. Thanks for answer in advance.

**Comment by cenfun** [comment]
I think it should be okay, but I need to know what the Slack Channel is first, is there any Open API? Or a typical use scenario, or screenshot? demo? thanks

**Comment by cenfun** [comment]
just post a example: [slack-webhook.js](/tests/common/slack-webhook.js)
```js
// playwright.config.js
module.exports = {
    reporter: [
        ['monocart-reporter', {  
            name: "My Test Report",
            outputFile: './test-results/report.html',
            onEnd: async (reportData, capacity) => {
                const slackWebhook = require('./common/slack-webhook.js');
                await slackWebhook(reportData, capacity);
            }
        }]
    ]
};
```

**Comment by i-novo** [comment]
Thank you for adding that!
