### ISSUE TITLE
Improvement Ideas

### ISSUE THREAD

**Issue by Aroot42** [cenfun/monocart-reporter#80]
Hi!
I have couple of ideas for improvements readability of testing result.

1. I have a simple test - create an entity and check correct status
![image](https://github.com/cenfun/monocart-reporter/assets/100360547/65ddb830-18bf-44b7-b1f7-d7b3006c4581)
In the tests result in the report I see my expect check as simple **expect.toBe**
![image](https://github.com/cenfun/monocart-reporter/assets/100360547/58a7eaca-da5d-4afb-8d4a-e94d98faa987)
My proposal - add extra information for expect command:
- in column Status - print status for expect - Pass/Fail
- in column Expected - extract (I don't know how :)) expected value from expect construction from test
- in column Outcome - actual value from expect construction from test
![image](https://github.com/cenfun/monocart-reporter/assets/100360547/9c84c73b-6882-4a4e-b3d9-31b72e5f9154)

2. In my another test I see in test result error message instead of **expect.toBe** from expect beside of test passed
![image](https://github.com/cenfun/monocart-reporter/assets/100360547/de82f63e-5b96-4bb4-a4fe-b0cebe503023)
![image](https://github.com/cenfun/monocart-reporter/assets/100360547/4b779932-158b-4e82-bbcf-7ac81279f171)

3. And last point - if it possible extract data from test (point 1 about extra data in test results), for methods (steps) which return value print it in the report
![image](https://github.com/cenfun/monocart-reporter/assets/100360547/440a4d8b-1d60-4ea5-bf5f-3e29febf8164)

**Comment by cenfun** [comment]
Yes, those extra data are good for readability of testing result, but we can only get title of step, see documentation: https://playwright.dev/docs/api/class-teststep
any idea to collect those extra data?

**Comment by Aroot42** [comment]
I have no idea about extracting data for point 1 and 3.
How about point 2 - error message instead of expect.toBe construction? Maybe smells like bug?

**Comment by cenfun** [comment]
I will looking into how to get the error message in expect.toBe,   BTW, you can try this feature: [Collect Data from the Comments](https://github.com/cenfun/monocart-reporter?tab=readme-ov-file#collect-data-from-the-comments)
example for step:
```
    /**
     * rewrite assert step title "expect.toBe" to
     * @title my custom assert step title
     * @annotations important
     * @status it's OK
     */
    expect(testInfo).toBe(test.info());

```
![image](https://github.com/cenfun/monocart-reporter/assets/334577/54a5d8be-59d2-4d6e-8c14-c8d0566f6a7a)

**Comment by cenfun** [comment]
@Aroot42 Sorry I misunderstood the point 2, the step title will be replaced with custom expect message, see here 
https://github.com/microsoft/playwright/pull/26752

**Comment by Aroot42** [comment]
I create [this topic](https://github.com/microsoft/playwright/issues/28622) about extra data in expect construction. Let's wait for the implementation.
