### ISSUE TITLE
Is it possible to print the test log in real time when running playwright?

### ISSUE THREAD

**Issue by jiawen94** [cenfun/monocart-reporter#81]
Hi, cenfun.
when I use monocart, the output log is not in real time. Only the end of the test will output the results.
Is it possible to print the test log in real time when running playwright?
![image](https://github.com/cenfun/monocart-reporter/assets/29114225/88746fd9-6446-4a28-946c-5f941a222496)

**Comment by cenfun** [comment]
using one more `list` reporter
```js
// playwright.config.js
module.exports = {
    reporter: [
        ['list'],
        ['monocart-reporter', {  
            name: "My Test Report",
            outputFile: './test-results/report.html'
        }]
    ]
};

```

**Comment by jiawen94** [comment]
Thanks. I missed list attribute in config file.
