### ISSUE TITLE
[BUG] Incorrect OS when running the Playwright tests in a docker container

### ISSUE THREAD

**Issue by edumserrano** [cenfun/monocart-reporter#83]
Hi @cenfun,

## Bug

When you [run the Playwright tests in a docker container](https://playwright.dev/docs/docker), the OS displayed in the monocart-reporter html report is weird. For instance, when running on the [mcr.microsoft.com/playwright:v1.40.1-jammy](https://hub.docker.com/_/microsoft-playwright) I get this:

![image](https://github.com/cenfun/monocart-reporter/assets/15857357/368dbfc1-2490-44f4-851f-59d47b8f78ef)

Note that the OS is set to `#1 SMP PREEMPT_DYNAMIC Thu Nov 16 10:55:59 UTC 2023 (x64)`.

## How to reproduce

You can use the [docker demo](https://github.com/edumserrano/playwright-adventures/blob/main/demos/docker/README.md#how-to-build-run-the-app-run-tests-and-view-the-test-results) in the [edumserrano/playwright-adventures repo](https://github.com/edumserrano/playwright-adventures) to replicate the bug.

1) Clone the [edumserrano/playwright-adventures repo](https://github.com/edumserrano/playwright-adventures).
2) Using your favorite shell go to `/demos/docker`.
3) Install the required npm packages with:
    ```
    npm install
    ```
4) Install the [playwright browsers](https://playwright.dev/docs/browsers) with:
    ```
    npx playwright install
    ```
5) Run the tests with:
    ```
    npm test
    ```
    This will start a docker container which will run the app and then run the [playwright tests](/demos/docker/tests/example.spec.ts) against it.
6) After running the tests with `npm test` you can view test results with:
    ```
    npm run test:show-report
    ```

## Other notes

This is a very minor bug of course but perhaps it's also easy to fix. I believe the OS should display the fact that it ran in an Ubuntu Linux OS. For example:
- when I ran the tests on my Windows laptop I get: `Windows 10 Enterprise (x64)`
- when I ran the tests on a CI server that is using Ubuntu I get: `#55~20.04.1-Ubuntu SMP Mon Nov 6 12:15:34 UTC 2023 (x64)`. Even this is doesn't seem to be the best for the OS description so perhaps there's some room for improvement in how the report is getting the OS info for Unix platforms.

**Comment by cenfun** [comment]
It can be reproduced to [Github Actions](https://github.com/cenfun/monocart-reporter/blob/main/.github/workflows/static.yml#L30), see report [here](https://cenfun.github.io/monocart-reporter/#page=report)

 How does the current `OS` work:
1, OS = `${system.version} (${system.arch})`
2, system.version = os.version() and system.arch = os.arch()
see Node.js [os](https://nodejs.org/docs/latest/api/os.html) API [os.version()](https://nodejs.org/docs/latest/api/os.html#osversion) and [os.arch()](https://nodejs.org/docs/latest/api/os.html#osarch), both are native Node.js API that fast, compatible and no need to load dependencies.
I found that there is a lib [systeminformation](https://github.com/sebhildebrandt/systeminformation) very popular, seems that its [osInfo.distro](https://[systeminformation](https://systeminformation.io/os.html).io/os.html) is what we want, but it should be slow, see implementation:
- linux: https://github.com/sebhildebrandt/systeminformation/blob/master/lib/osinfo.js#L252
- darwin: https://github.com/sebhildebrandt/systeminformation/blob/master/lib/osinfo.js#L298
- windows: https://github.com/sebhildebrandt/systeminformation/blob/master/lib/osinfo.js#L349

any better idea?

**Comment by edumserrano** [comment]
Unfortunately I can't help you much here. My expertise is not on Node.js. 
What I can say is that I don't think this is a big issue. If you feel that you haven't found a good solution yet then you can leave the OS as is and close this issue until you find a good solution. I reported it because I thought at least it should be on your radar.

You mentioned that `systeminformation` library but you seem to be afraid that it's going to slow down the report. Have you tested it somehow?

**Comment by cenfun** [comment]
yes, I previously used  `systeminformation` in another Node.js project, it is slow and large even slow down the main process.
