### ISSUE TITLE
jenkins archived html report shows exception

### ISSUE THREAD

**Issue by jiawen94** [cenfun/monocart-reporter#84]
Hi,cenfun.
I want to archive monocart  report as jenkins html report, but when I open this report In jenkins, It shows empty(There is no problem to open it locally after downloading).
I think this may be a limitation of jenkins, are you experiencing the same situation? How did you solve it?
![image](https://github.com/cenfun/monocart-reporter/assets/29114225/7378cd8e-7a42-4c64-b2da-915692b0ba7b)
![image](https://github.com/cenfun/monocart-reporter/assets/29114225/51260f01-31ec-4767-969d-9d1101693700)

**Comment by cenfun** [comment]
Could open the the html report and trun on devtools (F12) to see if any errors in console?

**Comment by jiawen94** [comment]
![image](https://github.com/cenfun/monocart-reporter/assets/29114225/587e924f-d64b-4fe0-8b86-3c5d53adabb1)
Maybe because of the 'allow-scripts' permission I think

**Comment by cenfun** [comment]
嗯，直接用中文了，你不能直接在Jenkins上打开连接，安全起见它禁用脚本了，连图片样式也禁用了
试试下载下来再打开，或者要上传到一个web server就行

**Comment by jiawen94** [comment]
已经定位到禁用脚本的原因，我在jenkins 启动参数添加-Dhudson.model.DirectoryBrowserSupport.CSP 参数解决了
![image](https://github.com/cenfun/monocart-reporter/assets/29114225/5706afdd-d77f-47d8-86b4-cf611ce9c03b)

**Comment by jiawen94** [comment]
完整启动命令，大家遇到同样的问题可以借鉴一下
java -Dfile.encoding=UTF8   -Dhudson.model.DirectoryBrowserSupport.CSP=   -jar jenkins.war --httpPort=8081
