### ISSUE TITLE
求助，关于在测试报告中打开trace viewer的问题

### ISSUE THREAD

**Issue by jiawen94** [cenfun/monocart-reporter#86]
你好晨风
我npx monocart show-report 本地localhost起一个服务，浏览器可以正常访问trace viewer
如果在服务器上npx monocart show-report （或者把报告归档到jenkins html reporter中），浏览器访问服务器上的报告，点击trace viewer似乎出现了CORS跨站访问的限制。这种问题你有啥好的解决方法，我虚心借鉴一下
![image](https://github.com/cenfun/monocart-reporter/assets/29114225/117fd415-eb65-4970-b369-8eb5226771f1)
我最终的想法是报告和trace.zip都在服务器上，浏览器查看报告和trace viewer

**Comment by cenfun** [comment]
目前trace viewer用的只能是playwright官方提供的页面去打开，在线的就是这个  https://trace.playwright.dev/
但问题就是只能手动上传trace.zip，指定url会有跨域打开zip的问题
试试这个解决方案，可以自己部署一个自己的trace viewer到自己的域名里，这样就没有跨域问题了：
1，先使用官方的html报告，会自动生成一个trace目录，就是trace viewer的应用
2，将这个文件夹部署到自己的一个服务上，比如 http://localhot:3000/trace
3，在monocart的配置指定trace viewer的url到自己本地的 http://localhot:3000/trace
```
// playwright.config.js
module.exports = {
    reporter: [
        ['list'],
        ['monocart-reporter', {  
            name: "My Test Report",
            traceViewerUrl: "http://localhot:3000/trace/?trace={traceUrl}",
            outputFile: './test-results/report.html'
        }]
    ]
};
```

**Comment by jiawen94** [comment]
我大概看懂了思路：自己部署trace viewer应用和trace资源属于同一个域，这样规避掉了跨域冲突的问题。
不过我之前也尝试过私有化部署trace viewer，好像需要域名和SSL证书，还是挺麻烦的https://github.com/microsoft/playwright/issues/27771  我估计要想想办法从代码里面去掉这些限制

**Comment by cenfun** [comment]
之前有用户有同样的问题，就是这样解决的。
忘记了，还有个办法就是存放trace.zip的服务器开启跨域访问即可。

使用这个CLI打开报告，你能看到调用的就是playwright官方的页面打开的trace
npx monocart show-report .temp/monocart/index.html

我使用的是koa，在http headers里面放开跨域限制即可
```
headers: {
     'Access-Control-Allow-Origin': '*'
},
```
这样其他任何域的访问都没有限制

**Comment by jiawen94** [comment]
我目前验证方法2 遇到一些问题，需要花点时间解决和验证
1. web服务用的nginx，NGINX上按网上教程启用cors（koa没用过，我trace文件放nginx里面，测试能不能跨站访问），但是并没有生效，正在排查
2. Jenkins不清楚怎么开启cors跨域访问支持，正在问Jenkins社区
不过感觉这个方案2应该是可行的，我看有成功的例子https://trace.playwright.dev/?trace=https://alisterscott.github.io/media/trace.zip

**Comment by cenfun** [comment]
是否成功直接用浏览器打开，查一下网络的请求头即可
![image](https://github.com/cenfun/monocart-reporter/assets/334577/dfd0ee28-469d-463e-8e45-b4262a1bb095)

**Comment by cenfun** [comment]
这个例子用的是github.io的服务，居然也可以设置请求头
![image](https://github.com/cenfun/monocart-reporter/assets/334577/5c8c180d-6798-40eb-8082-db39290a4ae4)

**Comment by jiawen94** [comment]
1. NGINX 上的trace.zip，按照你的方法看，确实是开启了跨域访问。
直接访问本地 http://192.168.80.93:8083/trace.zip资源
![image](https://github.com/cenfun/monocart-reporter/assets/29114225/3b072fbe-7520-4e34-b781-c116680a0da7)
**但是trace viewer无法直接调用trace.zip资源，不明白为什么**
![image](https://github.com/cenfun/monocart-reporter/assets/29114225/663dec41-0c6a-411a-9cdb-5c2e4b02009e)
![image](https://github.com/cenfun/monocart-reporter/assets/29114225/01fb43ec-182c-41cb-97eb-0a2a8b8c089d)

2. jenkins上的资源，用你的方法验证，他确实没有带Access-Control-Allow-Headers 的属性
直接访问trace.zip资源
![image](https://github.com/cenfun/monocart-reporter/assets/29114225/0bf4aa02-7e68-4975-b33c-2c0436759b18)

**Comment by cenfun** [comment]
看到请求头多了几个设置，可能是限制，去掉试试
![image](https://github.com/cenfun/monocart-reporter/assets/334577/0f13c886-7ad7-43f1-8f52-2ce7853c59ea)

**Comment by jiawen94** [comment]
去掉了，不过还是无法跨域访问。看上去trace viewer对跨域的资源有https限制？
![image](https://github.com/cenfun/monocart-reporter/assets/29114225/6667a000-73e3-4e12-8723-e1cbc6854dd4)
![image](https://github.com/cenfun/monocart-reporter/assets/29114225/e266d7da-e197-4585-b8f9-f8c5ccaa6e8b)

**Comment by cenfun** [comment]
可是这里用也是普通http的：
![image](https://github.com/cenfun/monocart-reporter/assets/334577/0bc2f058-3283-488a-aa6c-21eafa2264a6)

还有个不同就是，这里用的是localhost的域名，而你的是ip地址
localhost域名自动能转换成了ipv6的地址，而你的应该还是ipv4，你可以切换一下试试
还有就是你的zip包好像有点大，9M？换个小的试试，是不是加载大文件超时了
![image](https://github.com/cenfun/monocart-reporter/assets/334577/44aa9cce-d38e-4b39-8cec-1abc06fbb12a)

**Comment by jiawen94** [comment]
试了一下，用SSL网关（自签名证书）代理了原来nginx http，在浏览器信任站点证书的情况下，是可以正常打开trace viewer（浏览器不信任站点证书，一样打开trace viewer失败）
![image](https://github.com/cenfun/monocart-reporter/assets/29114225/001fe070-37a8-4b86-83e3-a83022d70c87)

我猜测trace viewer站点允许http:localhost:XXXX，如果是IP地址或者域名，可能强制要求跨站资源走https，而且必须可信证书。

**Comment by jiawen94** [comment]
我晚上用macOS平台看了下报告。报告是本地起的`npx monocart show-report test-results/report.html`,通过报告右侧的trace view 按钮跳转到https://trace.playwright.dev/?trace=XXX 页面，edge浏览器是正常的，但是Safari浏览器不知道为啥展示不了。其实上周safari试过从monocart打开trace viewer是可以的，今晚就重新拉了仓库代码导了最新的包，edge能打开，Safari不行。
目前playwright:1.40.1, monocrat:2.2.2

![image](https://github.com/cenfun/monocart-reporter/assets/29114225/89312cc5-965d-482a-aa65-e834a257c3ce)
![image](https://github.com/cenfun/monocart-reporter/assets/29114225/d54b22e0-f5ee-4a35-abc3-b749880d3087)

**Comment by cenfun** [comment]
404是文件未找到
要么路径问题，要么那个文件不在，是否被清除了还是，检查一下
理论上新版没有改啥，试试退回旧版是否依旧有问题

**Comment by cenfun** [comment]
https://trace.playwright.dev/?trace=https%3A%2F%2Fcenfun.github.io%2Fmonocart-reporter%2Fexample-example-parent-group-sanity-case-steps-slow-Desktop-Chromium-retry1%2Ftrace.zip

上面这个链接是部署在github上的，你看看不同浏览器能否打开

**Comment by jiawen94** [comment]
上面Safari那个报的500（trace通过url打开失败），下面404那个是edge的图（打开正常的）。
降到2.1.0，Safari打开还是有问题

**Comment by jiawen94** [comment]
> https://trace.playwright.dev/?trace=https%3A%2F%2Fcenfun.github.io%2Fmonocart-reporter%2Fexample-example-parent-group-sanity-case-steps-slow-Desktop-Chromium-retry1%2Ftrace.zip
> 
> 上面这个链接是部署在github上的，你看看不同浏览器能否打开

Safari和edge都是可以打开的

**Comment by cenfun** [comment]
你把那个有问题的trace.zip文件传上来，我下载到本地试试

**Comment by jiawen94** [comment]
> 你把那个有问题的trace.zip文件传上来，我下载到本地试试

[trace-4.zip](https://github.com/cenfun/monocart-reporter/files/13921726/trace-4.zip)
访问百度的一个case。

**Comment by cenfun** [comment]
@jiawen94 试了你提供的zip包，在edge浏览器没问题，但我没有mac系统，无非测试Safari，有ipad但它没法启动本地server

所以经过一番研究，发布了新版 monocart-reporter@2.2.3 
新支持用https来启动server
``sh
npx monocart show-report test-results/index.html --ssl ssl/key.pem,/ssl/cert.pem
```
如果你有现成域名的证书，可以直接用
如果没有，可以生成一个本地的证书，我用的是[mkcert](https://mkcert.dev)这个工具
```sh
# 创建证书
mkcert example.com "*.example.com" example.test localhost 127.0.0.1 ::1
# 安装证书到本机
mkcert -install
```
这样本机用浏览器可以成功打开服务的https地址，但其他电脑打开，会提示证书未验证不安全，这是当然的，不过可以点击继续浏览，我用ipad的Safari测试也能成功打开trace，用的是 https://192.168.31.195:8090 这样的地址
你可以试试

**Comment by jiawen94** [comment]
用--ssl参数试了下，在浏览器信任证书的情况下，Safari 能顺利打开trace viewer
