### ISSUE TITLE
[BUG] Collected comments don't show on report

### ISSUE THREAD

**Issue by edumserrano** [cenfun/monocart-reporter#87]
Hi @cenfun ,

I'm following your the docs about [Collect Data from the Comments](https://github.com/cenfun/monocart-reporter?tab=readme-ov-file#collect-data-from-the-comments) but I'm not getting any comments.

## Steps to reproduce

1) Clone the `temp-collect-comments` tag from [playwright-adventures repo](https://github.com/edumserrano/playwright-adventures/tree/temp-collect-comments)
2) Use your favourite shell to go to ./demos/monocart-reporter.
3) Run `npm i` to install all required npm packages.
4) Run `npm test` to run the tests.
5) Run `npm run test:show-report` to open the monocart-reporter html report and see that no comments are shown on the tests.

## Expected

Comments should show as columns and when opening the details of a test.  For instance if I have a test with a comment like this:

```
/**
* @description <some text>
*/
test("my test", async ({ page }) => {
   ...  
});
```

Then the `description` comment item should be collected and displayed as a column and also when opening the test details like the screenshots below:

![image](https://github.com/cenfun/monocart-reporter/assets/15857357/ed2f40fa-736f-4755-b1e9-f76dc9ec43c4)

![image](https://github.com/cenfun/monocart-reporter/assets/15857357/9fdf0922-3c9c-4791-884b-8abe3757d5ec)

> [!NOTE]
> The above expected screenshot was generated from an app using monocart-reporter `1.7.5` and Playwright `1.36.2`. 

## Other notes

- This bug is happening with monocart-reporter version `2.1.0` and Playwright `1.40.1`.
- The monocart-reporter configuration on the demo app is at [/demos/monocart-reporter/playwright.monocart-reporter.ts](https://github.com/edumserrano/playwright-adventures/blob/temp-collect-comments/demos/monocart-reporter/playwright.monocart-reporter.ts).
- On the `/demos/monocart-reporter` demo app from the `temp-collect-comments` tag from [playwright-adventures repo](https://github.com/edumserrano/playwright-adventures/tree/temp-collect-comments) I rolled back to monocart-reporter `1.7.5` and Playwright `1.36.2`, which are the version I have on another project where this is working, but I still don't get any comments. There might be something else on this demo app causing an issue?
- If it helps I've left a couple of `console.log` on the `visitor` function on the monocart-reporter configuration at [/demos/monocart-reporter/playwright.monocart-reporter.ts](https://github.com/edumserrano/playwright-adventures/blob/temp-collect-comments/demos/monocart-reporter/playwright.monocart-reporter.ts) to print the `comments` and the `data` objects and they seem ok. 
   <details>
     <summary>See console.logs</summary>
   
   log from `comments` object on `visitor` function
   ```
   {
     description: "Tests that the 'press me' button opens a dialog with the correct message    when the\r\n" +
       'ctrl modifier is used.'
   }
   ```
   
   log from `data` object on `visitor` function
   ```
   {
     id: '1c49a31851aedf54ebac',
     title: 'press me with ctrl modifier @press-me-button @with-ctrl-modifier',
     type: 'case',
     caseType: 'passed',
     ok: true,
     outcome: 'expected',
     expectedStatus: 'passed',
     location: 'tests/example.spec.ts:38:5',
     logs: undefined,
     timestamps: [ 1703855785262, 1703855795094 ],
     duration: 9832,
     annotations: undefined,
     timeout: 30000,
     retry: 0,
     status: 'passed',
     stepNum: 14,
     stepFailed: 0,
     stepSubs: true,
     subs: [
       {
         id: '1ynvby5xnbwvqwo8vyu8',
         title: 'Before Hooks',
         type: 'step',
         stepType: 'hook',
         duration: 2135,
         location: '',
         subs: [Array]
       },
       {
         id: 'lux4zxbj8k5jrvq9wp9n',
         title: 'page.goto(/)',
         type: 'step',
         stepType: 'pw:api',
         duration: 7100,
         location: 'tests/example.spec.ts:45:14'
       },
       {
         id: 'cx2ssug9uksfrasx3fpb',
         title: "locator.getByRole('button', { name: 'Press me' }).click",
         type: 'step',
         stepType: 'pw:api',
         duration: 557,
         location: 'tests/example.spec.ts:47:23',
         subs: [Array]
       },
       {
         id: 'gfj0h3bzhlfokko1shn1',
         title: 'expect.toBe',
         type: 'step',
         stepType: 'expect',
         duration: 2,
         location: 'tests/example.spec.ts:49:25'
       },
       {
         id: 'meex3dw0uw41ol12z1p6',
         title: 'After Hooks',
         type: 'step',
         stepType: 'hook',
         duration: 22,
         location: '',
         subs: [Array]
       }
     ],
     description: "Tests that the 'press me' button opens a dialog with the correct message    when the\r\n" +
       'ctrl modifier is used.'
   }
   ```
   </details>
- I also looked at the `monocart-report.json` file and I can see the `description` comment items in there. Here's the html report being produced from the demo app where you can also inspect the `monocart-report.json` file yourself: [monocart-report.zip](https://github.com/cenfun/monocart-reporter/files/13793862/monocart-report.zip)

**Comment by cenfun** [comment]
Looks like you haven't added the `description` column
```
columns: (defaultColumns) => {
      const typeIndex = defaultColumns.findIndex((column: any) => column.id === 'type');
      defaultColumns.splice(typeIndex, 0, {
          id: 'description',
          name: 'Description',
          width: 300,
          markdown: true,
          searchable: true
      });
    },
```
beacause the `description` is custom column, after added it and the description shows:
![image](https://github.com/cenfun/monocart-reporter/assets/334577/ad929efb-0dca-4b17-aae9-a722c355e7a1)

**Comment by edumserrano** [comment]
Yes, that was it. On my other project where the collect comments was working I also had defined the `columns` function:

```
/* See https://github.com/cenfun/monocart-reporter#custom-columns */
columns: (defaultColumns: any) => {
  const descriptionColumn = defaultColumns.find((column: any) => column.id === "description");
  if (!descriptionColumn) {
    const index = defaultColumns.findIndex((column: any) => column.id === "duration");
    defaultColumns.splice(index, 0, {
      id: "description",
      name: "Description",
      align: "left",
      searchable: true,
      detailed: true,
      markdown: true,
      styleMap: {
        "font-weight": "normal",
      },
    });
  }
},
```

I'll mark this as closed but I'll leave you with a suggestion for improving the docs. 

My suggestion is:

As a consumer of your library, I was reading the [Collect Data from the Comments](https://github.com/cenfun/monocart-reporter?tab=readme-ov-file#collect-data-from-the-comments) docs and it only has 2 steps: one to `add the collection of comments in the visitor` and another to `add comments to your tests`. 

It doesn't call out the fact that you need to have the custom column defined as well, except for a tiny detail which is a comment on the playwright.config.ts example for this above the `visitor` function which says `// additional custom visitor for columns`.

I think it would be nice to update the `Collect Data` documents to indicate that a custom column must be defined and that the `id` field of the custom `column` is important. For instance, in my case the id must be `description` because that's the comment item I'm using `@description`. If I used `@jira` then the `id` field should be `jira` right? 

This suggestion applies to all the `Collect Data` docs: `Collect Data from the Title`, `Collect Data from the Annotations` and `Collect Data from the Comments`. All of these are under the `Custom Data Visitor` section so perhaps it makes sense to add this information there so that people understand that if they augment the `data` object of the `visitor` function, they will need a custom column with a matching `id`.

Creating documentation is hard and yours is already pretty good, I'll leave it up to you to decide whether or not you want to improve this bit.

Thank you @cenfun.

**Comment by cenfun** [comment]
I will improve the doc, thank you for the suggestion.

**Comment by cenfun** [comment]
BTW, the new [coverage report](https://github.com/cenfun/monocart-coverage-reports) have some new features, like functions and branches column, feel free to try it.
