### ISSUE TITLE
页面是否提供测试自定义键值对信息的地方

### ISSUE THREAD

**Issue by jiawen94** [cenfun/monocart-reporter#88]
你好，晨风。
场景：
比如测试一个XXX系统，我最好在测试报告中展现：待测试设备的硬件信息、固件版本、操作系统、操作人信息等（都通过环境变量注入）。
目前playwright提供了Annotation的功能，但是Annotation只能作用于单个 tase case，无法作用于整个测试报告。
期望：
如果monocart能提供需求对应的功能，那最好不过。
如果monocart没有此需求对应的功能，您可以评估一下需求，是否可以作为后续版本的新功能加入。
比如加在这里，通过在playwright.config.ts中自定义键值对
![image](https://github.com/cenfun/monocart-reporter/assets/29114225/986e7fc0-c15c-4ff0-9668-f96d6e9c9b36)

**Comment by jiawen94** [comment]
在allure reporter中，有类似的功能
![image](https://github.com/cenfun/monocart-reporter/assets/29114225/8070115a-4ca5-4509-8e0a-5ba6b608f439)

**Comment by cenfun** [comment]
可以通过全局 metadata 实现
![image](https://github.com/cenfun/monocart-reporter/assets/334577/745a18d6-bb83-485a-9863-3fcdc55e472b)
如何将数据插入全局metadata
1，在playwright的config里，可以直接填写metadata信息，这些信息可以自行获取，比如从Jenkins环境变量获取等
```js
module.exports = {
    metadata: {
        // test global-setup error
        // baseURL: 'https://example.coma/',
        product: 'Monocart',
        env: 'STG',
        type: 'Regression',
        executor: 'Mono',

        // test home page object model
        url: 'https://www.npmjs.org/package/monocart-reporter'
    },
```
2，在playwright测试过程中，实时获取并添加metadata信息
- 比如在globalSetup里获取浏览器版本并添加到metadata， 例子： https://github.com/cenfun/monocart-reporter/blob/main/tests/common/global-setup.js
- 同用办法就是，只要能在playwright获得到主进程的config对象，直接操作它的metadata即可


```

**Comment by jiawen94** [comment]
谢谢。通过配置metadata确实解决了我的问题。第二点实时获取metadata我后面再研究研究
