### ISSUE TITLE
[BUG] Wrong data in test run summary

### ISSUE THREAD

**Issue by Aroot42** [cenfun/monocart-reporter#9]
I wrote and run(debug) 1 test.
In console I see test run summary
![image](https://user-images.githubusercontent.com/100360547/229109852-b46ea411-5709-4868-972a-5ee5357198b3.png)
and I see 2 bugs:

1. Suites      │ 2 - Why run 2 suites when 1 run only 1 test from 1 test file?
2. Duration    │ 2m 156s - Strange duration. Total time was 156sec = 2 min 36 sec. Or display in sec, or correctly convert to min.

**Comment by cenfun** [comment]
1, should be misunderstanding of name, Suites = projects + files + describes
see here https://playwright.dev/docs/api/class-suite
2, I will fix it next release

**Comment by Aroot42** [comment]
I have only one test in my project, so why should the number of test suites be equal to the sum of projects and files (2)? I believe that if I have one test file with one test, it should be considered as one suite. Similarly, if I have two test files and I run tests from both files, it should be counted as two suites (Suites = touched test files).

**Comment by cenfun** [comment]
reasonable, how about following counting?
1, each case have a only parent suite
2, count all parent suites without duplicate suite

**Comment by Aroot42** [comment]
Correct

**Comment by cenfun** [comment]
fixed in monocart-reporter@1.6.1 please have a try

**Comment by Aroot42** [comment]
In debug al, displayed cool
![image](https://user-images.githubusercontent.com/100360547/229159927-82288c0c-9c30-400b-a2c2-816b1b4c6d24.png)
After normal run not cool :)
![image](https://user-images.githubusercontent.com/100360547/229160143-a038a4d7-91fa-4d98-b5d1-4e6f38e0cafa.png)
