### ISSUE TITLE
[QUESTION] How do you add the web app version or url under test to the report?

### ISSUE THREAD

**Issue by craitose** [cenfun/monocart-reporter#90]
Just as the versions of playwright and monocart-reporter are included in the html report. I would like to include the url that  playwright was running the tests on to be included in the report. This is especially useful in the failed step for bug logging.

**Comment by cenfun** [comment]
Using [`metadata` ](https://github.com/cenfun/monocart-reporter?tab=readme-ov-file#metadata)
```
// playwright.config.js
module.exports = {
    metadata: {
        // test global-setup error
        // baseURL: 'https://example.coma/',
        product: 'Monocart',
        env: 'STG',
        type: 'Regression',
        executor: 'Mono',

        // test home page object model
        url: 'https://www.npmjs.org/package/monocart-reporter'
    },
```
![image](https://github.com/cenfun/monocart-reporter/assets/334577/37190e0f-314d-4f4c-9f05-1f30bf1d1ff3)

**Comment by craitose** [comment]
Thank you but what about at test level, if different tests are testing different URLs?

**Comment by cenfun** [comment]
For test level, see [Custom Fields Report](https://github.com/cenfun/monocart-reporter?tab=readme-ov-file#custom-fields-report)
both markdown and [Mermaid](https://mermaid.js.org/) are available.
![image](https://github.com/cenfun/monocart-reporter/assets/334577/391e4e85-a51b-474d-9297-e1c1fc6abffc)

**Comment by cenfun** [comment]
Playwright Test runs tests in parallel with isolate test data by default(in worker or sub process), so it doesn't work if metadata is modified in this way.
 ```js
test('test metadata url', async ({ page }, testInfo) => {
  const metadata = testInfo.config.metadata;
  metadata.url = await page.evaluate(() => window.locstion.href);  // not work in the test
});
 ```
Try using the [global state](https://github.com/cenfun/monocart-reporter?tab=readme-ov-file#global-state-management) feature of `monocart-reporter`:
- Enable global state
```js
// playwright.config.js
module.exports = {
    reporter: [
        ['list'],
        ['monocart-reporter', {  
            name: "My Test Report",
            outputFile: './test-results/report.html',
            state: {
                data: {
                },
                server: {
                    // port: 8130
                },
                onClose: (data, config) => {
                    // save state data to global metadata
                    Object.assign(config.metadata, data);
                }
            }
        }]
    ]
};
```
- Update global state in the test
```js
const { test } = require('@playwright/test');
const { useState } = require('monocart-reporter');

const state = useState({
  // port: 8130
});

test('test metadata url', async ({ page }) => {
    const url = await page.evaluate(() => window.locstion.href);
    await state.set('url', url);
});
```
