### ISSUE TITLE
[QUESTION] Why I am seeing unexpected token error

### ISSUE THREAD

**Issue by craitose** [cenfun/monocart-reporter#91]
I have observed two errors after generating report ... . I would like to know what the errors are and what caused them.

```
[MR] generating report ...
[MR] Unexpected token (11:8)
[MR] failed to parse source file: page_object/login.ts
```

>

**Comment by cenfun** [comment]
Which version did you used? monocart-reporter@2.3.1?
Please try latest version which should not occur this error.

**Comment by craitose** [comment]
I had version 2.0.4 and have now updated to 2.3.1 but now I get  different error: 
Cannot read properties of Undefined (reading 'comments')

**Comment by craitose** [comment]
The new option works and is much cleaner, thanks again
