### ISSUE TITLE
Malformed Cobertura Coverage XML

### ISSUE THREAD

**Issue by shuckster** [cenfun/monocart-reporter#92]
I have come across an issue with generated Cobertura XML files.

The `filename` field will contain unescaped ampersands if it contains a path generated from a URL with a query-string with multiple parameters.

ie; we will see:

    filename="http://localhost:3000/test?one&two"

Instead of:

    filename="http://localhost:3000/test?one&amp;two"

This causes SonarQube to disregard the entire file.

Now, this did not turn out to be a major issue in my particular case because I added configuration to accept only `webpack://` URLs, which correspond directly with the files on the disk.

I bring it up as an issue only because it took some time to debug, so perhaps it may help others if the `&` was either handled, or if a warning was thrown saying the `filename` fields are being generated from URLs.

Apologies, I am currently unable to provide a repo to reproduce the issue. I may be able to do so next week.

**Comment by cenfun** [comment]
The source url/path will be a virtual path if it comes from the sourcemap. like it starts with `webpack://`, I guess you are looking for is option `sourcePath`, see [Resolve sourcePath for the Source Files](https://github.com/cenfun/monocart-coverage-reports?tab=readme-ov-file#resolve-sourcepath-for-the-source-files)
```js
// escape characters & with &amp;
const coverageOptions = {
    sourcePath: (filePath) => {
        return filePath.replace(/&/g, "&amp;");
    }
};
```

**Comment by shuckster** [comment]
Thank you for the info, I'll try out your suggestion.
