### ISSUE TITLE
Suggestion: provide addEmptyCoverage function

### ISSUE THREAD

**Issue by stevez** [cenfun/monocart-reporter#94]
I tried to implement the add empty coverage for all the source files, but I found it has too many dependencies, I feel it would be nice to provide an additional function besides attachCoverage and addCoverage, or even can be configured as an option

**Comment by cenfun** [comment]
Thanks for the suggestion.
Please try new version monocart-reporter@2.3.4, it supports new option `all` for the empty coverage for all files
```js
{
  coverage: {
    all: {
            dir: ['./src'],
            filter: '**/*.js'
        }
  }
}
```
see https://github.com/cenfun/monocart-coverage-reports?tab=readme-ov-file#adding-empty-coverage-for-untested-files
