### ISSUE TITLE
[QUESTION] How to to pull the test title for each test item into the test rail report

### ISSUE THREAD

**Issue by craitose** [cenfun/monocart-reporter#96]
Hi again cenfun , 

Previous you helped me put the test project name into the test rail comment by using :

```
if (item.type === ''suite && item.suiteType === 'project') {
projectName = item.title;

return projectName;
}
```
But I am trying to get the case title which is in a subs[array] and when I try to get properties of subs, I get undefined returns

I have tried : 

 ```
if (item.type === ''case' && item.expectedStatus === 'passed' ) {
testName = item.title;

return testName;
}
```
which results in no test results for testrail.

I have also tried : 

 ```
if (item.type === ''suite' && item.suiteType === 'describe' ) {
testName = item.subs[item].title;

return testName;
}
``` 
which results in undefined.

testName = item.subs[0].title results in the first record

**Comment by cenfun** [comment]
Did you get those data in `onEnd` hook?
In fact, `rows` is a tree structure, and I suggest getting information in this way:
```js
{
  onEnd: async (reportData, capability) => {
    capability.forEach((item) => {
            if (item.type === 'case' && item.caseType === 'passed') {
                // your code
                return;
            }
            if (item.type === 'suite') {
                // your code
                return;
            }
        });
  }
}
```

**Comment by craitose** [comment]
All I needed was to call item.title in the default if statement 
```
if (item.type === 'case' && item.testrail) {
const status_id = item.ok ? : 5;
results.push({comment : `${item.title}`})
}
```
