### ISSUE TITLE
Screen shots not attached to email report

### ISSUE THREAD

**Issue by craitose** [cenfun/monocart-reporter#97]
Hi cenfun,
After running a test that fails, the report is generated and sent to the email inbox. On downloading then opening the report on the browser , the screenshot thumbail is present but when clicked , an error that the file does not exist is thrown in the browser. When the report is accessed by running npx monocart show-report test-results/report.html, the report then displays the screenshot of the error step.

**Comment by cenfun** [comment]
Attachments such as screenshots, videos, and traces will not be included in the HTML report, because there may be hundreds and could be big size. I believe that they are not suitable for sending to email inboxes.

It is suggested to upload the attachments to a server and then access them via http address.

```js
// playwright.config.js
// attachments outputDir and report outputFile used same folder
const date = new Date().toISOString().slice(0, 10); //2022-10-10
const outputDir = `./test-results/${date}`;
module.exports = {
    outputDir: outputDir,
    reporter: [
        ['monocart-reporter', {  
            name: `My Test Report ${date}`,
            outputFile: `${outputDir}/index.html`,
            attachmentPath: (currentPath, extras) => `http://your.report.site/test-results/2022-10-10/${currentPath}`,
        }]
    ]
};
// deploy the folder to your report site and easy checking online
// http://your.report.site/test-results/2022-10-10
```

**Comment by craitose** [comment]
Ok , that makes sense but I still need the email to be sent .How will I include the URL to the server in the email?
