### ISSUE TITLE
Question: is onEnd() hook invoked after the playwright global teardown function or before?

### ISSUE THREAD

**Issue by stevez** [cenfun/monocart-reporter#98]
It is important to make sure onEnd is called after the global teardown, how can we prove that?

**Comment by cenfun** [comment]
The Monocart `onEnd` is called after the Playwright cutsom reporter `onEnd`, see https://playwright.dev/docs/api/class-reporter#reporter-on-end
It should be called after the global teardown, but Im not sure, you can ask the Playwright developers for the answer.  https://github.com/microsoft/playwright/issues
