### ISSUE TITLE
Add metadata as a column

### ISSUE THREAD

**Issue by mikestreety** [cenfun/monocart-reporter#99]
Hey,

Thank you so much for this reporter 🙏 It's got _so_ many good things.

One thing I can't work out (and apologies if it's in the docs or if I misunderstood) is how to expose `metadata` as a column.

I have some `metadata` on each project (such as device name - e.g. "Desktop Edge") which I'd like as a column on the main report, so I can sort by it or quickly see if there is commonality between the failings.

Thanks again

**Comment by cenfun** [comment]
I added a example here https://github.com/cenfun/monocart-reporter-examples/tree/main/custom/metadata-column
Please have a try.
```js

const name = 'metadata-column';

import { devices } from '@playwright/test';

export default {
    testDir: './',
    outputDir: `../../docs/${name}`,

    projects: [
        {
            name: 'chromium',
            use: devices['Desktop Chrome'],
            metadata: {
                device: 'Desktop Chrome'
            }
        },
        {
            name: 'firefox',
            use: devices['Desktop Firefox'],
            metadata: {
                device: 'Desktop Firefox'
            }
        },
        {
            name: 'Mobile Safari',
            use: devices['iPhone 12'],
            metadata: {
                device: 'iPhone 12'
            }
        }
    ],

    reporter: [
        ['list'],
        ['monocart-reporter', {
            name,
            outputFile: `docs/${name}/index.html`,

            columns: (defaultColumns) => {

                // add `device` column after `duration` column
                const index = defaultColumns.findIndex((column) => column.id === 'duration');
                defaultColumns.splice(index, 0, {
                    id: 'device',
                    name: 'Device',
                    width: 150,
                    formatter: (v, rowItem, columnItem) => {
                        if (v) {
                            return `<b style="color:green">${v}</b>`;
                        }
                        return '';
                    }
                });

            },

            visitor: (data, pwData) => {

                // add `device` for project data
                if (data.type === 'suite' && data.suiteType === 'project') {
                    data.device = data.metadata && data.metadata.device;
                }

            }
        }]
    ]
};

```

**Comment by mikestreety** [comment]
Wow, thanks for the quick response. 

Is there a way of getting the device from the project onto the case? 

E.g. below, you can see the same test ran for two devices: 

<img width="787" alt="image" src="https://github.com/cenfun/monocart-reporter/assets/354085/b34ea4c5-a2d2-4003-bd3f-783657dafd02">

But it isn't visible in the ungrouped view:

<img width="983" alt="image" src="https://github.com/cenfun/monocart-reporter/assets/354085/729908d8-0594-4b47-9700-768934e3bb8e">

If it's not possible, don't worry - just a wish!

**Comment by mikestreety** [comment]
You are my hero. Thank you!
